import Sieve

/-! Kernel certificate part 6 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [12359, 14495), 37 blocks, estimated cost 1277985 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace Collatz

theorem sieve25_6_0 : svRange 400 32 16777216 20 14 12359 66 = true := by decide +kernel
theorem sieve25_6_1 : svRange 400 32 16777216 20 14 12425 32 = true := by decide +kernel
theorem sieve25_6_2 : svRange 400 32 16777216 20 14 12457 70 = true := by decide +kernel
theorem sieve25_6_3 : svRange 400 32 16777216 20 14 12527 15 = true := by decide +kernel
theorem sieve25_6_4 : svRange 400 32 16777216 20 14 12542 65 = true := by decide +kernel
theorem sieve25_6_5 : svRange 400 32 16777216 20 14 12607 128 = true := by decide +kernel
theorem sieve25_6_6 : svRange 400 32 16777216 20 14 12735 48 = true := by decide +kernel
theorem sieve25_6_7 : svRange 400 32 16777216 20 14 12783 48 = true := by decide +kernel
theorem sieve25_6_8 : svRange 400 32 16777216 20 14 12831 60 = true := by decide +kernel
theorem sieve25_6_9 : svRange 400 32 16777216 20 14 12891 36 = true := by decide +kernel
theorem sieve25_6_10 : svRange 400 32 16777216 20 14 12927 32 = true := by decide +kernel
theorem sieve25_6_11 : svRange 400 32 16777216 20 14 12959 32 = true := by decide +kernel
theorem sieve25_6_12 : svRange 400 32 16777216 20 14 12991 42 = true := by decide +kernel
theorem sieve25_6_13 : svRange 400 32 16777216 20 14 13033 22 = true := by decide +kernel
theorem sieve25_6_14 : svRange 400 32 16777216 20 14 13055 104 = true := by decide +kernel
theorem sieve25_6_15 : svRange 400 32 16777216 20 14 13159 24 = true := by decide +kernel
theorem sieve25_6_16 : svRange 400 32 16777216 20 14 13183 106 = true := by decide +kernel
theorem sieve25_6_17 : svRange 400 32 16777216 20 14 13289 54 = true := by decide +kernel
theorem sieve25_6_18 : svRange 400 32 16777216 20 14 13343 72 = true := by decide +kernel
theorem sieve25_6_19 : svRange 400 32 16777216 20 14 13415 34 = true := by decide +kernel
theorem sieve25_6_20 : svRange 400 32 16777216 20 14 13449 32 = true := by decide +kernel
theorem sieve25_6_21 : svRange 400 32 16777216 20 14 13481 56 = true := by decide +kernel
theorem sieve25_6_22 : svRange 400 32 16777216 20 14 13537 14 = true := by decide +kernel
theorem sieve25_6_23 : svRange 400 32 16777216 20 14 13551 44 = true := by decide +kernel
theorem sieve25_6_24 : svRange 400 32 16777216 20 14 13595 100 = true := by decide +kernel
theorem sieve25_6_25 : svRange 400 32 16777216 20 14 13695 64 = true := by decide +kernel
theorem sieve25_6_26 : svRange 400 32 16777216 20 14 13759 31 = true := by decide +kernel
theorem sieve25_6_27 : svRange 400 32 16777216 20 14 13790 61 = true := by decide +kernel
theorem sieve25_6_28 : svRange 400 32 16777216 20 14 13851 76 = true := by decide +kernel
theorem sieve25_6_29 : svRange 400 32 16777216 20 14 13927 66 = true := by decide +kernel
theorem sieve25_6_30 : svRange 400 32 16777216 20 14 13993 85 = true := by decide +kernel
theorem sieve25_6_31 : svRange 400 32 16777216 20 14 14078 29 = true := by decide +kernel
theorem sieve25_6_32 : svRange 400 32 16777216 20 14 14107 140 = true := by decide +kernel
theorem sieve25_6_33 : svRange 400 32 16777216 20 14 14247 66 = true := by decide +kernel
theorem sieve25_6_34 : svRange 400 32 16777216 20 14 14313 22 = true := by decide +kernel
theorem sieve25_6_35 : svRange 400 32 16777216 20 14 14335 92 = true := by decide +kernel
theorem sieve25_6_36 : svRange 400 32 16777216 20 14 14427 68 = true := by decide +kernel

theorem sieve25_part6 : RootsOK 400 32 16777216 20 14 12359 14495 :=
  rootsOK_cons sieve25_6_0 <|
  rootsOK_cons sieve25_6_1 <|
  rootsOK_cons sieve25_6_2 <|
  rootsOK_cons sieve25_6_3 <|
  rootsOK_cons sieve25_6_4 <|
  rootsOK_cons sieve25_6_5 <|
  rootsOK_cons sieve25_6_6 <|
  rootsOK_cons sieve25_6_7 <|
  rootsOK_cons sieve25_6_8 <|
  rootsOK_cons sieve25_6_9 <|
  rootsOK_cons sieve25_6_10 <|
  rootsOK_cons sieve25_6_11 <|
  rootsOK_cons sieve25_6_12 <|
  rootsOK_cons sieve25_6_13 <|
  rootsOK_cons sieve25_6_14 <|
  rootsOK_cons sieve25_6_15 <|
  rootsOK_cons sieve25_6_16 <|
  rootsOK_cons sieve25_6_17 <|
  rootsOK_cons sieve25_6_18 <|
  rootsOK_cons sieve25_6_19 <|
  rootsOK_cons sieve25_6_20 <|
  rootsOK_cons sieve25_6_21 <|
  rootsOK_cons sieve25_6_22 <|
  rootsOK_cons sieve25_6_23 <|
  rootsOK_cons sieve25_6_24 <|
  rootsOK_cons sieve25_6_25 <|
  rootsOK_cons sieve25_6_26 <|
  rootsOK_cons sieve25_6_27 <|
  rootsOK_cons sieve25_6_28 <|
  rootsOK_cons sieve25_6_29 <|
  rootsOK_cons sieve25_6_30 <|
  rootsOK_cons sieve25_6_31 <|
  rootsOK_cons sieve25_6_32 <|
  rootsOK_cons sieve25_6_33 <|
  rootsOK_cons sieve25_6_34 <|
  rootsOK_cons sieve25_6_35 <|
  rootsOK_cons sieve25_6_36 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve25_6_0
#print axioms Collatz.sieve25_part6
