import Sieve

/-! Kernel certificate part 1 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [2047, 4167), 36 blocks,
  estimated cost 1178612 units. Generated by a script; `decide +kernel` only. -/

namespace Collatz

theorem sieve24_1_0 : svRange 400 16 2 20 14 2047 64 = true := by decide +kernel
theorem sieve24_1_1 : svRange 400 16 2 20 14 2111 48 = true := by decide +kernel
theorem sieve24_1_2 : svRange 400 16 2 20 14 2159 48 = true := by decide +kernel
theorem sieve24_1_3 : svRange 400 16 2 20 14 2207 10 = true := by decide +kernel
theorem sieve24_1_4 : svRange 400 16 2 20 14 2217 70 = true := by decide +kernel
theorem sieve24_1_5 : svRange 400 16 2 20 14 2287 88 = true := by decide +kernel
theorem sieve24_1_6 : svRange 400 16 2 20 14 2375 120 = true := by decide +kernel
theorem sieve24_1_7 : svRange 400 16 2 20 14 2495 40 = true := by decide +kernel
theorem sieve24_1_8 : svRange 400 16 2 20 14 2535 24 = true := by decide +kernel
theorem sieve24_1_9 : svRange 400 16 2 20 14 2559 128 = true := by decide +kernel
theorem sieve24_1_10 : svRange 400 16 2 20 14 2687 64 = true := by decide +kernel
theorem sieve24_1_11 : svRange 400 16 2 20 14 2751 92 = true := by decide +kernel
theorem sieve24_1_12 : svRange 400 16 2 20 14 2843 76 = true := by decide +kernel
theorem sieve24_1_13 : svRange 400 16 2 20 14 2919 24 = true := by decide +kernel
theorem sieve24_1_14 : svRange 400 16 2 20 14 2943 64 = true := by decide +kernel
theorem sieve24_1_15 : svRange 400 16 2 20 14 3007 48 = true := by decide +kernel
theorem sieve24_1_16 : svRange 400 16 2 20 14 3055 44 = true := by decide +kernel
theorem sieve24_1_17 : svRange 400 16 2 20 14 3099 76 = true := by decide +kernel
theorem sieve24_1_18 : svRange 400 16 2 20 14 3175 24 = true := by decide +kernel
theorem sieve24_1_19 : svRange 400 16 2 20 14 3199 32 = true := by decide +kernel
theorem sieve24_1_20 : svRange 400 16 2 20 14 3231 66 = true := by decide +kernel
theorem sieve24_1_21 : svRange 400 16 2 20 14 3297 30 = true := by decide +kernel
theorem sieve24_1_22 : svRange 400 16 2 20 14 3327 48 = true := by decide +kernel
theorem sieve24_1_23 : svRange 400 16 2 20 14 3375 56 = true := by decide +kernel
theorem sieve24_1_24 : svRange 400 16 2 20 14 3431 130 = true := by decide +kernel
theorem sieve24_1_25 : svRange 400 16 2 20 14 3561 54 = true := by decide +kernel
theorem sieve24_1_26 : svRange 400 16 2 20 14 3615 96 = true := by decide +kernel
theorem sieve24_1_27 : svRange 400 16 2 20 14 3711 28 = true := by decide +kernel
theorem sieve24_1_28 : svRange 400 16 2 20 14 3739 52 = true := by decide +kernel
theorem sieve24_1_29 : svRange 400 16 2 20 14 3791 48 = true := by decide +kernel
theorem sieve24_1_30 : svRange 400 16 2 20 14 3839 92 = true := by decide +kernel
theorem sieve24_1_31 : svRange 400 16 2 20 14 3931 20 = true := by decide +kernel
theorem sieve24_1_32 : svRange 400 16 2 20 14 3951 114 = true := by decide +kernel
theorem sieve24_1_33 : svRange 400 16 2 20 14 4065 29 = true := by decide +kernel
theorem sieve24_1_34 : svRange 400 16 2 20 14 4094 1 = true := by decide +kernel
theorem sieve24_1_35 : svRange 400 16 2 20 14 4095 72 = true := by decide +kernel

theorem sieve24_part1 : RootsOK 400 16 2 20 14 2047 4167 :=
  rootsOK_cons sieve24_1_0 <|
  rootsOK_cons sieve24_1_1 <|
  rootsOK_cons sieve24_1_2 <|
  rootsOK_cons sieve24_1_3 <|
  rootsOK_cons sieve24_1_4 <|
  rootsOK_cons sieve24_1_5 <|
  rootsOK_cons sieve24_1_6 <|
  rootsOK_cons sieve24_1_7 <|
  rootsOK_cons sieve24_1_8 <|
  rootsOK_cons sieve24_1_9 <|
  rootsOK_cons sieve24_1_10 <|
  rootsOK_cons sieve24_1_11 <|
  rootsOK_cons sieve24_1_12 <|
  rootsOK_cons sieve24_1_13 <|
  rootsOK_cons sieve24_1_14 <|
  rootsOK_cons sieve24_1_15 <|
  rootsOK_cons sieve24_1_16 <|
  rootsOK_cons sieve24_1_17 <|
  rootsOK_cons sieve24_1_18 <|
  rootsOK_cons sieve24_1_19 <|
  rootsOK_cons sieve24_1_20 <|
  rootsOK_cons sieve24_1_21 <|
  rootsOK_cons sieve24_1_22 <|
  rootsOK_cons sieve24_1_23 <|
  rootsOK_cons sieve24_1_24 <|
  rootsOK_cons sieve24_1_25 <|
  rootsOK_cons sieve24_1_26 <|
  rootsOK_cons sieve24_1_27 <|
  rootsOK_cons sieve24_1_28 <|
  rootsOK_cons sieve24_1_29 <|
  rootsOK_cons sieve24_1_30 <|
  rootsOK_cons sieve24_1_31 <|
  rootsOK_cons sieve24_1_32 <|
  rootsOK_cons sieve24_1_33 <|
  rootsOK_cons sieve24_1_34 <|
  rootsOK_cons sieve24_1_35 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve24_1_0
#print axioms Collatz.sieve24_part1
