import Sieve

/-! Kernel certificate part 51 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [13040, 13344), 14 blocks, estimated cost 2315305 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_51_0 : svRange 400 280 33554432 20 14 13040 15 = true := by decide +kernel
theorem sieve29_51_1 : svRange 400 280 33554432 20 14 13055 1 = true := by decide +kernel
theorem sieve29_51_2 : svRange 400 280 33554432 20 14 13056 103 = true := by decide +kernel
theorem sieve29_51_3 : svRange 400 280 33554432 20 14 13159 1 = true := by decide +kernel
theorem sieve29_51_4 : svRange 400 280 33554432 20 14 13160 22 = true := by decide +kernel
theorem sieve29_51_5 : svRange 400 280 33554432 20 14 13182 1 = true := by decide +kernel
theorem sieve29_51_6 : svRange 400 280 33554432 20 14 13183 1 = true := by decide +kernel
theorem sieve29_51_7 : svRange 400 280 33554432 20 14 13184 94 = true := by decide +kernel
theorem sieve29_51_8 : svRange 400 280 33554432 20 14 13278 1 = true := by decide +kernel
theorem sieve29_51_9 : svRange 400 280 33554432 20 14 13279 31 = true := by decide +kernel
theorem sieve29_51_10 : svRange 400 280 33554432 20 14 13310 1 = true := by decide +kernel
theorem sieve29_51_11 : svRange 400 280 33554432 20 14 13311 1 = true := by decide +kernel
theorem sieve29_51_12 : svRange 400 280 33554432 20 14 13312 31 = true := by decide +kernel
theorem sieve29_51_13 : svRange 400 280 33554432 20 14 13343 1 = true := by decide +kernel

theorem sieve29_part51 : RootsOK 400 280 33554432 20 14 13040 13344 :=
  rootsOK_cons sieve29_51_0 <|
  rootsOK_cons sieve29_51_1 <|
  rootsOK_cons sieve29_51_2 <|
  rootsOK_cons sieve29_51_3 <|
  rootsOK_cons sieve29_51_4 <|
  rootsOK_cons sieve29_51_5 <|
  rootsOK_cons sieve29_51_6 <|
  rootsOK_cons sieve29_51_7 <|
  rootsOK_cons sieve29_51_8 <|
  rootsOK_cons sieve29_51_9 <|
  rootsOK_cons sieve29_51_10 <|
  rootsOK_cons sieve29_51_11 <|
  rootsOK_cons sieve29_51_12 <|
  rootsOK_cons sieve29_51_13 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_51_0
#print axioms Collatz.sieve29_part51
