import Sieve

/-! Kernel certificate part 7 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [1792, 2044), 13 blocks, estimated cost 2382405 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_7_0 : svRange 400 280 33554432 20 14 1792 27 = true := by decide +kernel
theorem sieve29_7_1 : svRange 400 280 33554432 20 14 1819 1 = true := by decide +kernel
theorem sieve29_7_2 : svRange 400 280 33554432 20 14 1820 63 = true := by decide +kernel
theorem sieve29_7_3 : svRange 400 280 33554432 20 14 1883 12 = true := by decide +kernel
theorem sieve29_7_4 : svRange 400 280 33554432 20 14 1895 1 = true := by decide +kernel
theorem sieve29_7_5 : svRange 400 280 33554432 20 14 1896 22 = true := by decide +kernel
theorem sieve29_7_6 : svRange 400 280 33554432 20 14 1918 1 = true := by decide +kernel
theorem sieve29_7_7 : svRange 400 280 33554432 20 14 1919 1 = true := by decide +kernel
theorem sieve29_7_8 : svRange 400 280 33554432 20 14 1920 39 = true := by decide +kernel
theorem sieve29_7_9 : svRange 400 280 33554432 20 14 1959 2 = true := by decide +kernel
theorem sieve29_7_10 : svRange 400 280 33554432 20 14 1961 1 = true := by decide +kernel
theorem sieve29_7_11 : svRange 400 280 33554432 20 14 1962 81 = true := by decide +kernel
theorem sieve29_7_12 : svRange 400 280 33554432 20 14 2043 1 = true := by decide +kernel

theorem sieve29_part7 : RootsOK 400 280 33554432 20 14 1792 2044 :=
  rootsOK_cons sieve29_7_0 <|
  rootsOK_cons sieve29_7_1 <|
  rootsOK_cons sieve29_7_2 <|
  rootsOK_cons sieve29_7_3 <|
  rootsOK_cons sieve29_7_4 <|
  rootsOK_cons sieve29_7_5 <|
  rootsOK_cons sieve29_7_6 <|
  rootsOK_cons sieve29_7_7 <|
  rootsOK_cons sieve29_7_8 <|
  rootsOK_cons sieve29_7_9 <|
  rootsOK_cons sieve29_7_10 <|
  rootsOK_cons sieve29_7_11 <|
  rootsOK_cons sieve29_7_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_7_0
#print axioms Collatz.sieve29_part7
