import Sieve

/-! Kernel certificate part 7 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [14495, 16384), 38 blocks, estimated cost 1244329 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace Collatz

theorem sieve25_7_0 : svRange 400 32 16777216 20 14 14495 10 = true := by decide +kernel
theorem sieve25_7_1 : svRange 400 32 16777216 20 14 14505 56 = true := by decide +kernel
theorem sieve25_7_2 : svRange 400 32 16777216 20 14 14561 26 = true := by decide +kernel
theorem sieve25_7_3 : svRange 400 32 16777216 20 14 14587 68 = true := by decide +kernel
theorem sieve25_7_4 : svRange 400 32 16777216 20 14 14655 64 = true := by decide +kernel
theorem sieve25_7_5 : svRange 400 32 16777216 20 14 14719 64 = true := by decide +kernel
theorem sieve25_7_6 : svRange 400 32 16777216 20 14 14783 48 = true := by decide +kernel
theorem sieve25_7_7 : svRange 400 32 16777216 20 14 14831 16 = true := by decide +kernel
theorem sieve25_7_8 : svRange 400 32 16777216 20 14 14847 112 = true := by decide +kernel
theorem sieve25_7_9 : svRange 400 32 16777216 20 14 14959 44 = true := by decide +kernel
theorem sieve25_7_10 : svRange 400 32 16777216 20 14 15003 14 = true := by decide +kernel
theorem sieve25_7_11 : svRange 400 32 16777216 20 14 15017 62 = true := by decide +kernel
theorem sieve25_7_12 : svRange 400 32 16777216 20 14 15079 24 = true := by decide +kernel
theorem sieve25_7_13 : svRange 400 32 16777216 20 14 15103 64 = true := by decide +kernel
theorem sieve25_7_14 : svRange 400 32 16777216 20 14 15167 64 = true := by decide +kernel
theorem sieve25_7_15 : svRange 400 32 16777216 20 14 15231 106 = true := by decide +kernel
theorem sieve25_7_16 : svRange 400 32 16777216 20 14 15337 22 = true := by decide +kernel
theorem sieve25_7_17 : svRange 400 32 16777216 20 14 15359 63 = true := by decide +kernel
theorem sieve25_7_18 : svRange 400 32 16777216 20 14 15422 49 = true := by decide +kernel
theorem sieve25_7_19 : svRange 400 32 16777216 20 14 15471 48 = true := by decide +kernel
theorem sieve25_7_20 : svRange 400 32 16777216 20 14 15519 32 = true := by decide +kernel
theorem sieve25_7_21 : svRange 400 32 16777216 20 14 15551 63 = true := by decide +kernel
theorem sieve25_7_22 : svRange 400 32 16777216 20 14 15614 49 = true := by decide +kernel
theorem sieve25_7_23 : svRange 400 32 16777216 20 14 15663 79 = true := by decide +kernel
theorem sieve25_7_24 : svRange 400 32 16777216 20 14 15742 65 = true := by decide +kernel
theorem sieve25_7_25 : svRange 400 32 16777216 20 14 15807 63 = true := by decide +kernel
theorem sieve25_7_26 : svRange 400 32 16777216 20 14 15870 1 = true := by decide +kernel
theorem sieve25_7_27 : svRange 400 32 16777216 20 14 15871 32 = true := by decide +kernel
theorem sieve25_7_28 : svRange 400 32 16777216 20 14 15903 96 = true := by decide +kernel
theorem sieve25_7_29 : svRange 400 32 16777216 20 14 15999 42 = true := by decide +kernel
theorem sieve25_7_30 : svRange 400 32 16777216 20 14 16041 38 = true := by decide +kernel
theorem sieve25_7_31 : svRange 400 32 16777216 20 14 16079 48 = true := by decide +kernel
theorem sieve25_7_32 : svRange 400 32 16777216 20 14 16127 28 = true := by decide +kernel
theorem sieve25_7_33 : svRange 400 32 16777216 20 14 16155 76 = true := by decide +kernel
theorem sieve25_7_34 : svRange 400 32 16777216 20 14 16231 34 = true := by decide +kernel
theorem sieve25_7_35 : svRange 400 32 16777216 20 14 16265 117 = true := by decide +kernel
theorem sieve25_7_36 : svRange 400 32 16777216 20 14 16382 1 = true := by decide +kernel
theorem sieve25_7_37 : svRange 400 32 16777216 20 14 16383 1 = true := by decide +kernel

theorem sieve25_part7 : RootsOK 400 32 16777216 20 14 14495 16384 :=
  rootsOK_cons sieve25_7_0 <|
  rootsOK_cons sieve25_7_1 <|
  rootsOK_cons sieve25_7_2 <|
  rootsOK_cons sieve25_7_3 <|
  rootsOK_cons sieve25_7_4 <|
  rootsOK_cons sieve25_7_5 <|
  rootsOK_cons sieve25_7_6 <|
  rootsOK_cons sieve25_7_7 <|
  rootsOK_cons sieve25_7_8 <|
  rootsOK_cons sieve25_7_9 <|
  rootsOK_cons sieve25_7_10 <|
  rootsOK_cons sieve25_7_11 <|
  rootsOK_cons sieve25_7_12 <|
  rootsOK_cons sieve25_7_13 <|
  rootsOK_cons sieve25_7_14 <|
  rootsOK_cons sieve25_7_15 <|
  rootsOK_cons sieve25_7_16 <|
  rootsOK_cons sieve25_7_17 <|
  rootsOK_cons sieve25_7_18 <|
  rootsOK_cons sieve25_7_19 <|
  rootsOK_cons sieve25_7_20 <|
  rootsOK_cons sieve25_7_21 <|
  rootsOK_cons sieve25_7_22 <|
  rootsOK_cons sieve25_7_23 <|
  rootsOK_cons sieve25_7_24 <|
  rootsOK_cons sieve25_7_25 <|
  rootsOK_cons sieve25_7_26 <|
  rootsOK_cons sieve25_7_27 <|
  rootsOK_cons sieve25_7_28 <|
  rootsOK_cons sieve25_7_29 <|
  rootsOK_cons sieve25_7_30 <|
  rootsOK_cons sieve25_7_31 <|
  rootsOK_cons sieve25_7_32 <|
  rootsOK_cons sieve25_7_33 <|
  rootsOK_cons sieve25_7_34 <|
  rootsOK_cons sieve25_7_35 <|
  rootsOK_cons sieve25_7_36 <|
  rootsOK_cons sieve25_7_37 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve25_7_0
#print axioms Collatz.sieve25_part7
