import Sieve

/-! Kernel certificate part 0 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [0, 224), 16 blocks, estimated cost 2380789 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_0_0 : svRange 400 280 33554432 20 14 0 31 = true := by decide +kernel
theorem sieve29_0_1 : svRange 400 280 33554432 20 14 31 1 = true := by decide +kernel
theorem sieve29_0_2 : svRange 400 280 33554432 20 14 32 15 = true := by decide +kernel
theorem sieve29_0_3 : svRange 400 280 33554432 20 14 47 15 = true := by decide +kernel
theorem sieve29_0_4 : svRange 400 280 33554432 20 14 62 1 = true := by decide +kernel
theorem sieve29_0_5 : svRange 400 280 33554432 20 14 63 8 = true := by decide +kernel
theorem sieve29_0_6 : svRange 400 280 33554432 20 14 71 20 = true := by decide +kernel
theorem sieve29_0_7 : svRange 400 280 33554432 20 14 91 12 = true := by decide +kernel
theorem sieve29_0_8 : svRange 400 280 33554432 20 14 103 8 = true := by decide +kernel
theorem sieve29_0_9 : svRange 400 280 33554432 20 14 111 1 = true := by decide +kernel
theorem sieve29_0_10 : svRange 400 280 33554432 20 14 112 47 = true := by decide +kernel
theorem sieve29_0_11 : svRange 400 280 33554432 20 14 159 8 = true := by decide +kernel
theorem sieve29_0_12 : svRange 400 280 33554432 20 14 167 1 = true := by decide +kernel
theorem sieve29_0_13 : svRange 400 280 33554432 20 14 168 54 = true := by decide +kernel
theorem sieve29_0_14 : svRange 400 280 33554432 20 14 222 1 = true := by decide +kernel
theorem sieve29_0_15 : svRange 400 280 33554432 20 14 223 1 = true := by decide +kernel

theorem sieve29_part0 : RootsOK 400 280 33554432 20 14 0 224 :=
  rootsOK_cons sieve29_0_0 <|
  rootsOK_cons sieve29_0_1 <|
  rootsOK_cons sieve29_0_2 <|
  rootsOK_cons sieve29_0_3 <|
  rootsOK_cons sieve29_0_4 <|
  rootsOK_cons sieve29_0_5 <|
  rootsOK_cons sieve29_0_6 <|
  rootsOK_cons sieve29_0_7 <|
  rootsOK_cons sieve29_0_8 <|
  rootsOK_cons sieve29_0_9 <|
  rootsOK_cons sieve29_0_10 <|
  rootsOK_cons sieve29_0_11 <|
  rootsOK_cons sieve29_0_12 <|
  rootsOK_cons sieve29_0_13 <|
  rootsOK_cons sieve29_0_14 <|
  rootsOK_cons sieve29_0_15 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_0_0
#print axioms Collatz.sieve29_part0
