import Sieve

/-! Kernel certificate part 52 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [13344, 13552), 18 blocks, estimated cost 2485179 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_52_0 : svRange 400 280 33554432 20 14 13344 59 = true := by decide +kernel
theorem sieve29_52_1 : svRange 400 280 33554432 20 14 13403 1 = true := by decide +kernel
theorem sieve29_52_2 : svRange 400 280 33554432 20 14 13404 11 = true := by decide +kernel
theorem sieve29_52_3 : svRange 400 280 33554432 20 14 13415 1 = true := by decide +kernel
theorem sieve29_52_4 : svRange 400 280 33554432 20 14 13416 23 = true := by decide +kernel
theorem sieve29_52_5 : svRange 400 280 33554432 20 14 13439 10 = true := by decide +kernel
theorem sieve29_52_6 : svRange 400 280 33554432 20 14 13449 1 = true := by decide +kernel
theorem sieve29_52_7 : svRange 400 280 33554432 20 14 13450 21 = true := by decide +kernel
theorem sieve29_52_8 : svRange 400 280 33554432 20 14 13471 1 = true := by decide +kernel
theorem sieve29_52_9 : svRange 400 280 33554432 20 14 13472 31 = true := by decide +kernel
theorem sieve29_52_10 : svRange 400 280 33554432 20 14 13503 31 = true := by decide +kernel
theorem sieve29_52_11 : svRange 400 280 33554432 20 14 13534 1 = true := by decide +kernel
theorem sieve29_52_12 : svRange 400 280 33554432 20 14 13535 2 = true := by decide +kernel
theorem sieve29_52_13 : svRange 400 280 33554432 20 14 13537 1 = true := by decide +kernel
theorem sieve29_52_14 : svRange 400 280 33554432 20 14 13538 5 = true := by decide +kernel
theorem sieve29_52_15 : svRange 400 280 33554432 20 14 13543 1 = true := by decide +kernel
theorem sieve29_52_16 : svRange 400 280 33554432 20 14 13544 7 = true := by decide +kernel
theorem sieve29_52_17 : svRange 400 280 33554432 20 14 13551 1 = true := by decide +kernel

theorem sieve29_part52 : RootsOK 400 280 33554432 20 14 13344 13552 :=
  rootsOK_cons sieve29_52_0 <|
  rootsOK_cons sieve29_52_1 <|
  rootsOK_cons sieve29_52_2 <|
  rootsOK_cons sieve29_52_3 <|
  rootsOK_cons sieve29_52_4 <|
  rootsOK_cons sieve29_52_5 <|
  rootsOK_cons sieve29_52_6 <|
  rootsOK_cons sieve29_52_7 <|
  rootsOK_cons sieve29_52_8 <|
  rootsOK_cons sieve29_52_9 <|
  rootsOK_cons sieve29_52_10 <|
  rootsOK_cons sieve29_52_11 <|
  rootsOK_cons sieve29_52_12 <|
  rootsOK_cons sieve29_52_13 <|
  rootsOK_cons sieve29_52_14 <|
  rootsOK_cons sieve29_52_15 <|
  rootsOK_cons sieve29_52_16 <|
  rootsOK_cons sieve29_52_17 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_52_0
#print axioms Collatz.sieve29_part52
