import Sieve

/-! Kernel certificate part 29 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [7647, 7850), 15 blocks, estimated cost 2225470 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_29_0 : svRange 400 280 33554432 20 14 7647 16 = true := by decide +kernel
theorem sieve29_29_1 : svRange 400 280 33554432 20 14 7663 15 = true := by decide +kernel
theorem sieve29_29_2 : svRange 400 280 33554432 20 14 7678 1 = true := by decide +kernel
theorem sieve29_29_3 : svRange 400 280 33554432 20 14 7679 1 = true := by decide +kernel
theorem sieve29_29_4 : svRange 400 280 33554432 20 14 7680 27 = true := by decide +kernel
theorem sieve29_29_5 : svRange 400 280 33554432 20 14 7707 1 = true := by decide +kernel
theorem sieve29_29_6 : svRange 400 280 33554432 20 14 7708 13 = true := by decide +kernel
theorem sieve29_29_7 : svRange 400 280 33554432 20 14 7721 1 = true := by decide +kernel
theorem sieve29_29_8 : svRange 400 280 33554432 20 14 7722 85 = true := by decide +kernel
theorem sieve29_29_9 : svRange 400 280 33554432 20 14 7807 1 = true := by decide +kernel
theorem sieve29_29_10 : svRange 400 280 33554432 20 14 7808 27 = true := by decide +kernel
theorem sieve29_29_11 : svRange 400 280 33554432 20 14 7835 4 = true := by decide +kernel
theorem sieve29_29_12 : svRange 400 280 33554432 20 14 7839 1 = true := by decide +kernel
theorem sieve29_29_13 : svRange 400 280 33554432 20 14 7840 9 = true := by decide +kernel
theorem sieve29_29_14 : svRange 400 280 33554432 20 14 7849 1 = true := by decide +kernel

theorem sieve29_part29 : RootsOK 400 280 33554432 20 14 7647 7850 :=
  rootsOK_cons sieve29_29_0 <|
  rootsOK_cons sieve29_29_1 <|
  rootsOK_cons sieve29_29_2 <|
  rootsOK_cons sieve29_29_3 <|
  rootsOK_cons sieve29_29_4 <|
  rootsOK_cons sieve29_29_5 <|
  rootsOK_cons sieve29_29_6 <|
  rootsOK_cons sieve29_29_7 <|
  rootsOK_cons sieve29_29_8 <|
  rootsOK_cons sieve29_29_9 <|
  rootsOK_cons sieve29_29_10 <|
  rootsOK_cons sieve29_29_11 <|
  rootsOK_cons sieve29_29_12 <|
  rootsOK_cons sieve29_29_13 <|
  rootsOK_cons sieve29_29_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_29_0
#print axioms Collatz.sieve29_part29
