import Sieve

/-! Kernel certificate part 49 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [12540, 12891), 14 blocks, estimated cost 2358449 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_49_0 : svRange 400 280 33554432 20 14 12540 66 = true := by decide +kernel
theorem sieve29_49_1 : svRange 400 280 33554432 20 14 12606 1 = true := by decide +kernel
theorem sieve29_49_2 : svRange 400 280 33554432 20 14 12607 1 = true := by decide +kernel
theorem sieve29_49_3 : svRange 400 280 33554432 20 14 12608 127 = true := by decide +kernel
theorem sieve29_49_4 : svRange 400 280 33554432 20 14 12735 31 = true := by decide +kernel
theorem sieve29_49_5 : svRange 400 280 33554432 20 14 12766 1 = true := by decide +kernel
theorem sieve29_49_6 : svRange 400 280 33554432 20 14 12767 8 = true := by decide +kernel
theorem sieve29_49_7 : svRange 400 280 33554432 20 14 12775 8 = true := by decide +kernel
theorem sieve29_49_8 : svRange 400 280 33554432 20 14 12783 1 = true := by decide +kernel
theorem sieve29_49_9 : svRange 400 280 33554432 20 14 12784 15 = true := by decide +kernel
theorem sieve29_49_10 : svRange 400 280 33554432 20 14 12799 32 = true := by decide +kernel
theorem sieve29_49_11 : svRange 400 280 33554432 20 14 12831 10 = true := by decide +kernel
theorem sieve29_49_12 : svRange 400 280 33554432 20 14 12841 1 = true := by decide +kernel
theorem sieve29_49_13 : svRange 400 280 33554432 20 14 12842 49 = true := by decide +kernel

theorem sieve29_part49 : RootsOK 400 280 33554432 20 14 12540 12891 :=
  rootsOK_cons sieve29_49_0 <|
  rootsOK_cons sieve29_49_1 <|
  rootsOK_cons sieve29_49_2 <|
  rootsOK_cons sieve29_49_3 <|
  rootsOK_cons sieve29_49_4 <|
  rootsOK_cons sieve29_49_5 <|
  rootsOK_cons sieve29_49_6 <|
  rootsOK_cons sieve29_49_7 <|
  rootsOK_cons sieve29_49_8 <|
  rootsOK_cons sieve29_49_9 <|
  rootsOK_cons sieve29_49_10 <|
  rootsOK_cons sieve29_49_11 <|
  rootsOK_cons sieve29_49_12 <|
  rootsOK_cons sieve29_49_13 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_49_0
#print axioms Collatz.sieve29_part49
