import Sieve

/-! Kernel certificate part 37 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [9695, 9888), 13 blocks, estimated cost 2213748 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_37_0 : svRange 400 280 33554432 20 14 9695 1 = true := by decide +kernel
theorem sieve29_37_1 : svRange 400 280 33554432 20 14 9696 30 = true := by decide +kernel
theorem sieve29_37_2 : svRange 400 280 33554432 20 14 9726 1 = true := by decide +kernel
theorem sieve29_37_3 : svRange 400 280 33554432 20 14 9727 1 = true := by decide +kernel
theorem sieve29_37_4 : svRange 400 280 33554432 20 14 9728 41 = true := by decide +kernel
theorem sieve29_37_5 : svRange 400 280 33554432 20 14 9769 1 = true := by decide +kernel
theorem sieve29_37_6 : svRange 400 280 33554432 20 14 9770 5 = true := by decide +kernel
theorem sieve29_37_7 : svRange 400 280 33554432 20 14 9775 1 = true := by decide +kernel
theorem sieve29_37_8 : svRange 400 280 33554432 20 14 9776 55 = true := by decide +kernel
theorem sieve29_37_9 : svRange 400 280 33554432 20 14 9831 24 = true := by decide +kernel
theorem sieve29_37_10 : svRange 400 280 33554432 20 14 9855 1 = true := by decide +kernel
theorem sieve29_37_11 : svRange 400 280 33554432 20 14 9856 31 = true := by decide +kernel
theorem sieve29_37_12 : svRange 400 280 33554432 20 14 9887 1 = true := by decide +kernel

theorem sieve29_part37 : RootsOK 400 280 33554432 20 14 9695 9888 :=
  rootsOK_cons sieve29_37_0 <|
  rootsOK_cons sieve29_37_1 <|
  rootsOK_cons sieve29_37_2 <|
  rootsOK_cons sieve29_37_3 <|
  rootsOK_cons sieve29_37_4 <|
  rootsOK_cons sieve29_37_5 <|
  rootsOK_cons sieve29_37_6 <|
  rootsOK_cons sieve29_37_7 <|
  rootsOK_cons sieve29_37_8 <|
  rootsOK_cons sieve29_37_9 <|
  rootsOK_cons sieve29_37_10 <|
  rootsOK_cons sieve29_37_11 <|
  rootsOK_cons sieve29_37_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_37_0
#print axioms Collatz.sieve29_part37
