import Sieve

/-! Kernel certificate part 10 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [2558, 2887), 13 blocks, estimated cost 2268274 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_10_0 : svRange 400 280 33554432 20 14 2558 1 = true := by decide +kernel
theorem sieve29_10_1 : svRange 400 280 33554432 20 14 2559 1 = true := by decide +kernel
theorem sieve29_10_2 : svRange 400 280 33554432 20 14 2560 127 = true := by decide +kernel
theorem sieve29_10_3 : svRange 400 280 33554432 20 14 2687 28 = true := by decide +kernel
theorem sieve29_10_4 : svRange 400 280 33554432 20 14 2715 14 = true := by decide +kernel
theorem sieve29_10_5 : svRange 400 280 33554432 20 14 2729 1 = true := by decide +kernel
theorem sieve29_10_6 : svRange 400 280 33554432 20 14 2730 61 = true := by decide +kernel
theorem sieve29_10_7 : svRange 400 280 33554432 20 14 2791 20 = true := by decide +kernel
theorem sieve29_10_8 : svRange 400 280 33554432 20 14 2811 3 = true := by decide +kernel
theorem sieve29_10_9 : svRange 400 280 33554432 20 14 2814 29 = true := by decide +kernel
theorem sieve29_10_10 : svRange 400 280 33554432 20 14 2843 1 = true := by decide +kernel
theorem sieve29_10_11 : svRange 400 280 33554432 20 14 2844 35 = true := by decide +kernel
theorem sieve29_10_12 : svRange 400 280 33554432 20 14 2879 8 = true := by decide +kernel

theorem sieve29_part10 : RootsOK 400 280 33554432 20 14 2558 2887 :=
  rootsOK_cons sieve29_10_0 <|
  rootsOK_cons sieve29_10_1 <|
  rootsOK_cons sieve29_10_2 <|
  rootsOK_cons sieve29_10_3 <|
  rootsOK_cons sieve29_10_4 <|
  rootsOK_cons sieve29_10_5 <|
  rootsOK_cons sieve29_10_6 <|
  rootsOK_cons sieve29_10_7 <|
  rootsOK_cons sieve29_10_8 <|
  rootsOK_cons sieve29_10_9 <|
  rootsOK_cons sieve29_10_10 <|
  rootsOK_cons sieve29_10_11 <|
  rootsOK_cons sieve29_10_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_10_0
#print axioms Collatz.sieve29_part10
