import Sieve

/-! Kernel certificate part 22 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [5760, 6057), 15 blocks, estimated cost 2265824 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_22_0 : svRange 400 280 33554432 20 14 5760 31 = true := by decide +kernel
theorem sieve29_22_1 : svRange 400 280 33554432 20 14 5791 1 = true := by decide +kernel
theorem sieve29_22_2 : svRange 400 280 33554432 20 14 5792 71 = true := by decide +kernel
theorem sieve29_22_3 : svRange 400 280 33554432 20 14 5863 23 = true := by decide +kernel
theorem sieve29_22_4 : svRange 400 280 33554432 20 14 5886 1 = true := by decide +kernel
theorem sieve29_22_5 : svRange 400 280 33554432 20 14 5887 1 = true := by decide +kernel
theorem sieve29_22_6 : svRange 400 280 33554432 20 14 5888 27 = true := by decide +kernel
theorem sieve29_22_7 : svRange 400 280 33554432 20 14 5915 1 = true := by decide +kernel
theorem sieve29_22_8 : svRange 400 280 33554432 20 14 5916 75 = true := by decide +kernel
theorem sieve29_22_9 : svRange 400 280 33554432 20 14 5991 1 = true := by decide +kernel
theorem sieve29_22_10 : svRange 400 280 33554432 20 14 5992 7 = true := by decide +kernel
theorem sieve29_22_11 : svRange 400 280 33554432 20 14 5999 1 = true := by decide +kernel
theorem sieve29_22_12 : svRange 400 280 33554432 20 14 6000 15 = true := by decide +kernel
theorem sieve29_22_13 : svRange 400 280 33554432 20 14 6015 40 = true := by decide +kernel
theorem sieve29_22_14 : svRange 400 280 33554432 20 14 6055 2 = true := by decide +kernel

theorem sieve29_part22 : RootsOK 400 280 33554432 20 14 5760 6057 :=
  rootsOK_cons sieve29_22_0 <|
  rootsOK_cons sieve29_22_1 <|
  rootsOK_cons sieve29_22_2 <|
  rootsOK_cons sieve29_22_3 <|
  rootsOK_cons sieve29_22_4 <|
  rootsOK_cons sieve29_22_5 <|
  rootsOK_cons sieve29_22_6 <|
  rootsOK_cons sieve29_22_7 <|
  rootsOK_cons sieve29_22_8 <|
  rootsOK_cons sieve29_22_9 <|
  rootsOK_cons sieve29_22_10 <|
  rootsOK_cons sieve29_22_11 <|
  rootsOK_cons sieve29_22_12 <|
  rootsOK_cons sieve29_22_13 <|
  rootsOK_cons sieve29_22_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_22_0
#print axioms Collatz.sieve29_part22
