import Sieve

/-! Kernel certificate part 3 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [6313, 8359), 36 blocks,
  estimated cost 1187834 units. Generated by a script; `decide +kernel` only. -/

namespace Collatz

theorem sieve24_3_0 : svRange 400 16 2 20 14 6313 56 = true := by decide +kernel
theorem sieve24_3_1 : svRange 400 16 2 20 14 6369 29 = true := by decide +kernel
theorem sieve24_3_2 : svRange 400 16 2 20 14 6398 64 = true := by decide +kernel
theorem sieve24_3_3 : svRange 400 16 2 20 14 6462 9 = true := by decide +kernel
theorem sieve24_3_4 : svRange 400 16 2 20 14 6471 120 = true := by decide +kernel
theorem sieve24_3_5 : svRange 400 16 2 20 14 6591 32 = true := by decide +kernel
theorem sieve24_3_6 : svRange 400 16 2 20 14 6623 32 = true := by decide +kernel
theorem sieve24_3_7 : svRange 400 16 2 20 14 6655 156 = true := by decide +kernel
theorem sieve24_3_8 : svRange 400 16 2 20 14 6811 52 = true := by decide +kernel
theorem sieve24_3_9 : svRange 400 16 2 20 14 6863 32 = true := by decide +kernel
theorem sieve24_3_10 : svRange 400 16 2 20 14 6895 44 = true := by decide +kernel
theorem sieve24_3_11 : svRange 400 16 2 20 14 6939 76 = true := by decide +kernel
theorem sieve24_3_12 : svRange 400 16 2 20 14 7015 120 = true := by decide +kernel
theorem sieve24_3_13 : svRange 400 16 2 20 14 7135 31 = true := by decide +kernel
theorem sieve24_3_14 : svRange 400 16 2 20 14 7166 29 = true := by decide +kernel
theorem sieve24_3_15 : svRange 400 16 2 20 14 7195 100 = true := by decide +kernel
theorem sieve24_3_16 : svRange 400 16 2 20 14 7295 40 = true := by decide +kernel
theorem sieve24_3_17 : svRange 400 16 2 20 14 7335 72 = true := by decide +kernel
theorem sieve24_3_18 : svRange 400 16 2 20 14 7407 16 = true := by decide +kernel
theorem sieve24_3_19 : svRange 400 16 2 20 14 7423 64 = true := by decide +kernel
theorem sieve24_3_20 : svRange 400 16 2 20 14 7487 128 = true := by decide +kernel
theorem sieve24_3_21 : svRange 400 16 2 20 14 7615 48 = true := by decide +kernel
theorem sieve24_3_22 : svRange 400 16 2 20 14 7663 44 = true := by decide +kernel
theorem sieve24_3_23 : svRange 400 16 2 20 14 7707 20 = true := by decide +kernel
theorem sieve24_3_24 : svRange 400 16 2 20 14 7727 112 = true := by decide +kernel
theorem sieve24_3_25 : svRange 400 16 2 20 14 7839 48 = true := by decide +kernel
theorem sieve24_3_26 : svRange 400 16 2 20 14 7887 48 = true := by decide +kernel
theorem sieve24_3_27 : svRange 400 16 2 20 14 7935 28 = true := by decide +kernel
theorem sieve24_3_28 : svRange 400 16 2 20 14 7963 76 = true := by decide +kernel
theorem sieve24_3_29 : svRange 400 16 2 20 14 8039 88 = true := by decide +kernel
theorem sieve24_3_30 : svRange 400 16 2 20 14 8127 63 = true := by decide +kernel
theorem sieve24_3_31 : svRange 400 16 2 20 14 8190 1 = true := by decide +kernel
theorem sieve24_3_32 : svRange 400 16 2 20 14 8191 28 = true := by decide +kernel
theorem sieve24_3_33 : svRange 400 16 2 20 14 8219 36 = true := by decide +kernel
theorem sieve24_3_34 : svRange 400 16 2 20 14 8255 64 = true := by decide +kernel
theorem sieve24_3_35 : svRange 400 16 2 20 14 8319 40 = true := by decide +kernel

theorem sieve24_part3 : RootsOK 400 16 2 20 14 6313 8359 :=
  rootsOK_cons sieve24_3_0 <|
  rootsOK_cons sieve24_3_1 <|
  rootsOK_cons sieve24_3_2 <|
  rootsOK_cons sieve24_3_3 <|
  rootsOK_cons sieve24_3_4 <|
  rootsOK_cons sieve24_3_5 <|
  rootsOK_cons sieve24_3_6 <|
  rootsOK_cons sieve24_3_7 <|
  rootsOK_cons sieve24_3_8 <|
  rootsOK_cons sieve24_3_9 <|
  rootsOK_cons sieve24_3_10 <|
  rootsOK_cons sieve24_3_11 <|
  rootsOK_cons sieve24_3_12 <|
  rootsOK_cons sieve24_3_13 <|
  rootsOK_cons sieve24_3_14 <|
  rootsOK_cons sieve24_3_15 <|
  rootsOK_cons sieve24_3_16 <|
  rootsOK_cons sieve24_3_17 <|
  rootsOK_cons sieve24_3_18 <|
  rootsOK_cons sieve24_3_19 <|
  rootsOK_cons sieve24_3_20 <|
  rootsOK_cons sieve24_3_21 <|
  rootsOK_cons sieve24_3_22 <|
  rootsOK_cons sieve24_3_23 <|
  rootsOK_cons sieve24_3_24 <|
  rootsOK_cons sieve24_3_25 <|
  rootsOK_cons sieve24_3_26 <|
  rootsOK_cons sieve24_3_27 <|
  rootsOK_cons sieve24_3_28 <|
  rootsOK_cons sieve24_3_29 <|
  rootsOK_cons sieve24_3_30 <|
  rootsOK_cons sieve24_3_31 <|
  rootsOK_cons sieve24_3_32 <|
  rootsOK_cons sieve24_3_33 <|
  rootsOK_cons sieve24_3_34 <|
  rootsOK_cons sieve24_3_35 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve24_3_0
#print axioms Collatz.sieve24_part3
