import Sieve

/-! Kernel certificate part 56 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [14428, 14655), 15 blocks, estimated cost 2264435 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_56_0 : svRange 400 280 33554432 20 14 14428 35 = true := by decide +kernel
theorem sieve29_56_1 : svRange 400 280 33554432 20 14 14463 32 = true := by decide +kernel
theorem sieve29_56_2 : svRange 400 280 33554432 20 14 14495 1 = true := by decide +kernel
theorem sieve29_56_3 : svRange 400 280 33554432 20 14 14496 47 = true := by decide +kernel
theorem sieve29_56_4 : svRange 400 280 33554432 20 14 14543 15 = true := by decide +kernel
theorem sieve29_56_5 : svRange 400 280 33554432 20 14 14558 1 = true := by decide +kernel
theorem sieve29_56_6 : svRange 400 280 33554432 20 14 14559 2 = true := by decide +kernel
theorem sieve29_56_7 : svRange 400 280 33554432 20 14 14561 1 = true := by decide +kernel
theorem sieve29_56_8 : svRange 400 280 33554432 20 14 14562 13 = true := by decide +kernel
theorem sieve29_56_9 : svRange 400 280 33554432 20 14 14575 1 = true := by decide +kernel
theorem sieve29_56_10 : svRange 400 280 33554432 20 14 14576 14 = true := by decide +kernel
theorem sieve29_56_11 : svRange 400 280 33554432 20 14 14590 1 = true := by decide +kernel
theorem sieve29_56_12 : svRange 400 280 33554432 20 14 14591 28 = true := by decide +kernel
theorem sieve29_56_13 : svRange 400 280 33554432 20 14 14619 35 = true := by decide +kernel
theorem sieve29_56_14 : svRange 400 280 33554432 20 14 14654 1 = true := by decide +kernel

theorem sieve29_part56 : RootsOK 400 280 33554432 20 14 14428 14655 :=
  rootsOK_cons sieve29_56_0 <|
  rootsOK_cons sieve29_56_1 <|
  rootsOK_cons sieve29_56_2 <|
  rootsOK_cons sieve29_56_3 <|
  rootsOK_cons sieve29_56_4 <|
  rootsOK_cons sieve29_56_5 <|
  rootsOK_cons sieve29_56_6 <|
  rootsOK_cons sieve29_56_7 <|
  rootsOK_cons sieve29_56_8 <|
  rootsOK_cons sieve29_56_9 <|
  rootsOK_cons sieve29_56_10 <|
  rootsOK_cons sieve29_56_11 <|
  rootsOK_cons sieve29_56_12 <|
  rootsOK_cons sieve29_56_13 <|
  rootsOK_cons sieve29_56_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_56_0
#print axioms Collatz.sieve29_part56
