import Sieve

/-! Kernel certificate part 23 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [6057, 6304), 15 blocks, estimated cost 2377564 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_23_0 : svRange 400 280 33554432 20 14 6057 22 = true := by decide +kernel
theorem sieve29_23_1 : svRange 400 280 33554432 20 14 6079 31 = true := by decide +kernel
theorem sieve29_23_2 : svRange 400 280 33554432 20 14 6110 1 = true := by decide +kernel
theorem sieve29_23_3 : svRange 400 280 33554432 20 14 6111 10 = true := by decide +kernel
theorem sieve29_23_4 : svRange 400 280 33554432 20 14 6121 1 = true := by decide +kernel
theorem sieve29_23_5 : svRange 400 280 33554432 20 14 6122 20 = true := by decide +kernel
theorem sieve29_23_6 : svRange 400 280 33554432 20 14 6142 1 = true := by decide +kernel
theorem sieve29_23_7 : svRange 400 280 33554432 20 14 6143 1 = true := by decide +kernel
theorem sieve29_23_8 : svRange 400 280 33554432 20 14 6144 47 = true := by decide +kernel
theorem sieve29_23_9 : svRange 400 280 33554432 20 14 6191 15 = true := by decide +kernel
theorem sieve29_23_10 : svRange 400 280 33554432 20 14 6206 1 = true := by decide +kernel
theorem sieve29_23_11 : svRange 400 280 33554432 20 14 6207 28 = true := by decide +kernel
theorem sieve29_23_12 : svRange 400 280 33554432 20 14 6235 1 = true := by decide +kernel
theorem sieve29_23_13 : svRange 400 280 33554432 20 14 6236 67 = true := by decide +kernel
theorem sieve29_23_14 : svRange 400 280 33554432 20 14 6303 1 = true := by decide +kernel

theorem sieve29_part23 : RootsOK 400 280 33554432 20 14 6057 6304 :=
  rootsOK_cons sieve29_23_0 <|
  rootsOK_cons sieve29_23_1 <|
  rootsOK_cons sieve29_23_2 <|
  rootsOK_cons sieve29_23_3 <|
  rootsOK_cons sieve29_23_4 <|
  rootsOK_cons sieve29_23_5 <|
  rootsOK_cons sieve29_23_6 <|
  rootsOK_cons sieve29_23_7 <|
  rootsOK_cons sieve29_23_8 <|
  rootsOK_cons sieve29_23_9 <|
  rootsOK_cons sieve29_23_10 <|
  rootsOK_cons sieve29_23_11 <|
  rootsOK_cons sieve29_23_12 <|
  rootsOK_cons sieve29_23_13 <|
  rootsOK_cons sieve29_23_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_23_0
#print axioms Collatz.sieve29_part23
