import Sieve

/-! Kernel certificate part 9 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [2216, 2558), 15 blocks, estimated cost 2307867 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_9_0 : svRange 400 280 33554432 20 14 2216 1 = true := by decide +kernel
theorem sieve29_9_1 : svRange 400 280 33554432 20 14 2217 1 = true := by decide +kernel
theorem sieve29_9_2 : svRange 400 280 33554432 20 14 2218 69 = true := by decide +kernel
theorem sieve29_9_3 : svRange 400 280 33554432 20 14 2287 1 = true := by decide +kernel
theorem sieve29_9_4 : svRange 400 280 33554432 20 14 2288 87 = true := by decide +kernel
theorem sieve29_9_5 : svRange 400 280 33554432 20 14 2375 1 = true := by decide +kernel
theorem sieve29_9_6 : svRange 400 280 33554432 20 14 2376 83 = true := by decide +kernel
theorem sieve29_9_7 : svRange 400 280 33554432 20 14 2459 4 = true := by decide +kernel
theorem sieve29_9_8 : svRange 400 280 33554432 20 14 2463 32 = true := by decide +kernel
theorem sieve29_9_9 : svRange 400 280 33554432 20 14 2495 31 = true := by decide +kernel
theorem sieve29_9_10 : svRange 400 280 33554432 20 14 2526 1 = true := by decide +kernel
theorem sieve29_9_11 : svRange 400 280 33554432 20 14 2527 1 = true := by decide +kernel
theorem sieve29_9_12 : svRange 400 280 33554432 20 14 2528 9 = true := by decide +kernel
theorem sieve29_9_13 : svRange 400 280 33554432 20 14 2537 6 = true := by decide +kernel
theorem sieve29_9_14 : svRange 400 280 33554432 20 14 2543 15 = true := by decide +kernel

theorem sieve29_part9 : RootsOK 400 280 33554432 20 14 2216 2558 :=
  rootsOK_cons sieve29_9_0 <|
  rootsOK_cons sieve29_9_1 <|
  rootsOK_cons sieve29_9_2 <|
  rootsOK_cons sieve29_9_3 <|
  rootsOK_cons sieve29_9_4 <|
  rootsOK_cons sieve29_9_5 <|
  rootsOK_cons sieve29_9_6 <|
  rootsOK_cons sieve29_9_7 <|
  rootsOK_cons sieve29_9_8 <|
  rootsOK_cons sieve29_9_9 <|
  rootsOK_cons sieve29_9_10 <|
  rootsOK_cons sieve29_9_11 <|
  rootsOK_cons sieve29_9_12 <|
  rootsOK_cons sieve29_9_13 <|
  rootsOK_cons sieve29_9_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_9_0
#print axioms Collatz.sieve29_part9
