import Sieve

/-! Kernel certificate part 50 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [12891, 13040), 16 blocks, estimated cost 2373162 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_50_0 : svRange 400 280 33554432 20 14 12891 1 = true := by decide +kernel
theorem sieve29_50_1 : svRange 400 280 33554432 20 14 12892 34 = true := by decide +kernel
theorem sieve29_50_2 : svRange 400 280 33554432 20 14 12926 1 = true := by decide +kernel
theorem sieve29_50_3 : svRange 400 280 33554432 20 14 12927 1 = true := by decide +kernel
theorem sieve29_50_4 : svRange 400 280 33554432 20 14 12928 27 = true := by decide +kernel
theorem sieve29_50_5 : svRange 400 280 33554432 20 14 12955 1 = true := by decide +kernel
theorem sieve29_50_6 : svRange 400 280 33554432 20 14 12956 3 = true := by decide +kernel
theorem sieve29_50_7 : svRange 400 280 33554432 20 14 12959 1 = true := by decide +kernel
theorem sieve29_50_8 : svRange 400 280 33554432 20 14 12960 31 = true := by decide +kernel
theorem sieve29_50_9 : svRange 400 280 33554432 20 14 12991 1 = true := by decide +kernel
theorem sieve29_50_10 : svRange 400 280 33554432 20 14 12992 33 = true := by decide +kernel
theorem sieve29_50_11 : svRange 400 280 33554432 20 14 13025 1 = true := by decide +kernel
theorem sieve29_50_12 : svRange 400 280 33554432 20 14 13026 7 = true := by decide +kernel
theorem sieve29_50_13 : svRange 400 280 33554432 20 14 13033 1 = true := by decide +kernel
theorem sieve29_50_14 : svRange 400 280 33554432 20 14 13034 5 = true := by decide +kernel
theorem sieve29_50_15 : svRange 400 280 33554432 20 14 13039 1 = true := by decide +kernel

theorem sieve29_part50 : RootsOK 400 280 33554432 20 14 12891 13040 :=
  rootsOK_cons sieve29_50_0 <|
  rootsOK_cons sieve29_50_1 <|
  rootsOK_cons sieve29_50_2 <|
  rootsOK_cons sieve29_50_3 <|
  rootsOK_cons sieve29_50_4 <|
  rootsOK_cons sieve29_50_5 <|
  rootsOK_cons sieve29_50_6 <|
  rootsOK_cons sieve29_50_7 <|
  rootsOK_cons sieve29_50_8 <|
  rootsOK_cons sieve29_50_9 <|
  rootsOK_cons sieve29_50_10 <|
  rootsOK_cons sieve29_50_11 <|
  rootsOK_cons sieve29_50_12 <|
  rootsOK_cons sieve29_50_13 <|
  rootsOK_cons sieve29_50_14 <|
  rootsOK_cons sieve29_50_15 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_50_0
#print axioms Collatz.sieve29_part50
