import Sieve

/-! Kernel certificate part 54 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [13823, 14090), 13 blocks, estimated cost 2205530 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_54_0 : svRange 400 280 33554432 20 14 13823 32 = true := by decide +kernel
theorem sieve29_54_1 : svRange 400 280 33554432 20 14 13855 10 = true := by decide +kernel
theorem sieve29_54_2 : svRange 400 280 33554432 20 14 13865 1 = true := by decide +kernel
theorem sieve29_54_3 : svRange 400 280 33554432 20 14 13866 85 = true := by decide +kernel
theorem sieve29_54_4 : svRange 400 280 33554432 20 14 13951 32 = true := by decide +kernel
theorem sieve29_54_5 : svRange 400 280 33554432 20 14 13983 1 = true := by decide +kernel
theorem sieve29_54_6 : svRange 400 280 33554432 20 14 13984 31 = true := by decide +kernel
theorem sieve29_54_7 : svRange 400 280 33554432 20 14 14015 40 = true := by decide +kernel
theorem sieve29_54_8 : svRange 400 280 33554432 20 14 14055 1 = true := by decide +kernel
theorem sieve29_54_9 : svRange 400 280 33554432 20 14 14056 23 = true := by decide +kernel
theorem sieve29_54_10 : svRange 400 280 33554432 20 14 14079 1 = true := by decide +kernel
theorem sieve29_54_11 : svRange 400 280 33554432 20 14 14080 9 = true := by decide +kernel
theorem sieve29_54_12 : svRange 400 280 33554432 20 14 14089 1 = true := by decide +kernel

theorem sieve29_part54 : RootsOK 400 280 33554432 20 14 13823 14090 :=
  rootsOK_cons sieve29_54_0 <|
  rootsOK_cons sieve29_54_1 <|
  rootsOK_cons sieve29_54_2 <|
  rootsOK_cons sieve29_54_3 <|
  rootsOK_cons sieve29_54_4 <|
  rootsOK_cons sieve29_54_5 <|
  rootsOK_cons sieve29_54_6 <|
  rootsOK_cons sieve29_54_7 <|
  rootsOK_cons sieve29_54_8 <|
  rootsOK_cons sieve29_54_9 <|
  rootsOK_cons sieve29_54_10 <|
  rootsOK_cons sieve29_54_11 <|
  rootsOK_cons sieve29_54_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_54_0
#print axioms Collatz.sieve29_part54
