import Sieve

/-! Kernel certificate part 60 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [15423, 15663), 15 blocks, estimated cost 2273397 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_60_0 : svRange 400 280 33554432 20 14 15423 40 = true := by decide +kernel
theorem sieve29_60_1 : svRange 400 280 33554432 20 14 15463 1 = true := by decide +kernel
theorem sieve29_60_2 : svRange 400 280 33554432 20 14 15464 7 = true := by decide +kernel
theorem sieve29_60_3 : svRange 400 280 33554432 20 14 15471 1 = true := by decide +kernel
theorem sieve29_60_4 : svRange 400 280 33554432 20 14 15472 25 = true := by decide +kernel
theorem sieve29_60_5 : svRange 400 280 33554432 20 14 15497 1 = true := by decide +kernel
theorem sieve29_60_6 : svRange 400 280 33554432 20 14 15498 21 = true := by decide +kernel
theorem sieve29_60_7 : svRange 400 280 33554432 20 14 15519 1 = true := by decide +kernel
theorem sieve29_60_8 : svRange 400 280 33554432 20 14 15520 31 = true := by decide +kernel
theorem sieve29_60_9 : svRange 400 280 33554432 20 14 15551 1 = true := by decide +kernel
theorem sieve29_60_10 : svRange 400 280 33554432 20 14 15552 59 = true := by decide +kernel
theorem sieve29_60_11 : svRange 400 280 33554432 20 14 15611 3 = true := by decide +kernel
theorem sieve29_60_12 : svRange 400 280 33554432 20 14 15614 1 = true := by decide +kernel
theorem sieve29_60_13 : svRange 400 280 33554432 20 14 15615 1 = true := by decide +kernel
theorem sieve29_60_14 : svRange 400 280 33554432 20 14 15616 47 = true := by decide +kernel

theorem sieve29_part60 : RootsOK 400 280 33554432 20 14 15423 15663 :=
  rootsOK_cons sieve29_60_0 <|
  rootsOK_cons sieve29_60_1 <|
  rootsOK_cons sieve29_60_2 <|
  rootsOK_cons sieve29_60_3 <|
  rootsOK_cons sieve29_60_4 <|
  rootsOK_cons sieve29_60_5 <|
  rootsOK_cons sieve29_60_6 <|
  rootsOK_cons sieve29_60_7 <|
  rootsOK_cons sieve29_60_8 <|
  rootsOK_cons sieve29_60_9 <|
  rootsOK_cons sieve29_60_10 <|
  rootsOK_cons sieve29_60_11 <|
  rootsOK_cons sieve29_60_12 <|
  rootsOK_cons sieve29_60_13 <|
  rootsOK_cons sieve29_60_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_60_0
#print axioms Collatz.sieve29_part60
