import Sieve

/-! Kernel certificate part 59 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [15166, 15423), 13 blocks, estimated cost 2220053 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_59_0 : svRange 400 280 33554432 20 14 15166 1 = true := by decide +kernel
theorem sieve29_59_1 : svRange 400 280 33554432 20 14 15167 40 = true := by decide +kernel
theorem sieve29_59_2 : svRange 400 280 33554432 20 14 15207 23 = true := by decide +kernel
theorem sieve29_59_3 : svRange 400 280 33554432 20 14 15230 1 = true := by decide +kernel
theorem sieve29_59_4 : svRange 400 280 33554432 20 14 15231 1 = true := by decide +kernel
theorem sieve29_59_5 : svRange 400 280 33554432 20 14 15232 41 = true := by decide +kernel
theorem sieve29_59_6 : svRange 400 280 33554432 20 14 15273 64 = true := by decide +kernel
theorem sieve29_59_7 : svRange 400 280 33554432 20 14 15337 1 = true := by decide +kernel
theorem sieve29_59_8 : svRange 400 280 33554432 20 14 15338 20 = true := by decide +kernel
theorem sieve29_59_9 : svRange 400 280 33554432 20 14 15358 1 = true := by decide +kernel
theorem sieve29_59_10 : svRange 400 280 33554432 20 14 15359 1 = true := by decide +kernel
theorem sieve29_59_11 : svRange 400 280 33554432 20 14 15360 62 = true := by decide +kernel
theorem sieve29_59_12 : svRange 400 280 33554432 20 14 15422 1 = true := by decide +kernel

theorem sieve29_part59 : RootsOK 400 280 33554432 20 14 15166 15423 :=
  rootsOK_cons sieve29_59_0 <|
  rootsOK_cons sieve29_59_1 <|
  rootsOK_cons sieve29_59_2 <|
  rootsOK_cons sieve29_59_3 <|
  rootsOK_cons sieve29_59_4 <|
  rootsOK_cons sieve29_59_5 <|
  rootsOK_cons sieve29_59_6 <|
  rootsOK_cons sieve29_59_7 <|
  rootsOK_cons sieve29_59_8 <|
  rootsOK_cons sieve29_59_9 <|
  rootsOK_cons sieve29_59_10 <|
  rootsOK_cons sieve29_59_11 <|
  rootsOK_cons sieve29_59_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_59_0
#print axioms Collatz.sieve29_part59
