import Sieve

/-! Kernel certificate part 28 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [7336, 7647), 13 blocks, estimated cost 2379209 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_28_0 : svRange 400 280 33554432 20 14 7336 23 = true := by decide +kernel
theorem sieve29_28_1 : svRange 400 280 33554432 20 14 7359 48 = true := by decide +kernel
theorem sieve29_28_2 : svRange 400 280 33554432 20 14 7407 1 = true := by decide +kernel
theorem sieve29_28_3 : svRange 400 280 33554432 20 14 7408 14 = true := by decide +kernel
theorem sieve29_28_4 : svRange 400 280 33554432 20 14 7422 1 = true := by decide +kernel
theorem sieve29_28_5 : svRange 400 280 33554432 20 14 7423 1 = true := by decide +kernel
theorem sieve29_28_6 : svRange 400 280 33554432 20 14 7424 47 = true := by decide +kernel
theorem sieve29_28_7 : svRange 400 280 33554432 20 14 7471 56 = true := by decide +kernel
theorem sieve29_28_8 : svRange 400 280 33554432 20 14 7527 1 = true := by decide +kernel
theorem sieve29_28_9 : svRange 400 280 33554432 20 14 7528 55 = true := by decide +kernel
theorem sieve29_28_10 : svRange 400 280 33554432 20 14 7583 32 = true := by decide +kernel
theorem sieve29_28_11 : svRange 400 280 33554432 20 14 7615 1 = true := by decide +kernel
theorem sieve29_28_12 : svRange 400 280 33554432 20 14 7616 31 = true := by decide +kernel

theorem sieve29_part28 : RootsOK 400 280 33554432 20 14 7336 7647 :=
  rootsOK_cons sieve29_28_0 <|
  rootsOK_cons sieve29_28_1 <|
  rootsOK_cons sieve29_28_2 <|
  rootsOK_cons sieve29_28_3 <|
  rootsOK_cons sieve29_28_4 <|
  rootsOK_cons sieve29_28_5 <|
  rootsOK_cons sieve29_28_6 <|
  rootsOK_cons sieve29_28_7 <|
  rootsOK_cons sieve29_28_8 <|
  rootsOK_cons sieve29_28_9 <|
  rootsOK_cons sieve29_28_10 <|
  rootsOK_cons sieve29_28_11 <|
  rootsOK_cons sieve29_28_12 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_28_0
#print axioms Collatz.sieve29_part28
