import Sieve

/-! Kernel certificate part 6 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [1519, 1792), 17 blocks, estimated cost 2213435 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_6_0 : svRange 400 280 33554432 20 14 1519 15 = true := by decide +kernel
theorem sieve29_6_1 : svRange 400 280 33554432 20 14 1534 1 = true := by decide +kernel
theorem sieve29_6_2 : svRange 400 280 33554432 20 14 1535 42 = true := by decide +kernel
theorem sieve29_6_3 : svRange 400 280 33554432 20 14 1577 6 = true := by decide +kernel
theorem sieve29_6_4 : svRange 400 280 33554432 20 14 1583 1 = true := by decide +kernel
theorem sieve29_6_5 : svRange 400 280 33554432 20 14 1584 55 = true := by decide +kernel
theorem sieve29_6_6 : svRange 400 280 33554432 20 14 1639 1 = true := by decide +kernel
theorem sieve29_6_7 : svRange 400 280 33554432 20 14 1640 23 = true := by decide +kernel
theorem sieve29_6_8 : svRange 400 280 33554432 20 14 1663 1 = true := by decide +kernel
theorem sieve29_6_9 : svRange 400 280 33554432 20 14 1664 27 = true := by decide +kernel
theorem sieve29_6_10 : svRange 400 280 33554432 20 14 1691 4 = true := by decide +kernel
theorem sieve29_6_11 : svRange 400 280 33554432 20 14 1695 10 = true := by decide +kernel
theorem sieve29_6_12 : svRange 400 280 33554432 20 14 1705 38 = true := by decide +kernel
theorem sieve29_6_13 : svRange 400 280 33554432 20 14 1743 1 = true := by decide +kernel
theorem sieve29_6_14 : svRange 400 280 33554432 20 14 1744 46 = true := by decide +kernel
theorem sieve29_6_15 : svRange 400 280 33554432 20 14 1790 1 = true := by decide +kernel
theorem sieve29_6_16 : svRange 400 280 33554432 20 14 1791 1 = true := by decide +kernel

theorem sieve29_part6 : RootsOK 400 280 33554432 20 14 1519 1792 :=
  rootsOK_cons sieve29_6_0 <|
  rootsOK_cons sieve29_6_1 <|
  rootsOK_cons sieve29_6_2 <|
  rootsOK_cons sieve29_6_3 <|
  rootsOK_cons sieve29_6_4 <|
  rootsOK_cons sieve29_6_5 <|
  rootsOK_cons sieve29_6_6 <|
  rootsOK_cons sieve29_6_7 <|
  rootsOK_cons sieve29_6_8 <|
  rootsOK_cons sieve29_6_9 <|
  rootsOK_cons sieve29_6_10 <|
  rootsOK_cons sieve29_6_11 <|
  rootsOK_cons sieve29_6_12 <|
  rootsOK_cons sieve29_6_13 <|
  rootsOK_cons sieve29_6_14 <|
  rootsOK_cons sieve29_6_15 <|
  rootsOK_cons sieve29_6_16 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_6_0
#print axioms Collatz.sieve29_part6
