import Sieve

/-! Kernel certificate part 26 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [6826, 7145), 17 blocks, estimated cost 2173450 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_26_0 : svRange 400 280 33554432 20 14 6826 37 = true := by decide +kernel
theorem sieve29_26_1 : svRange 400 280 33554432 20 14 6863 1 = true := by decide +kernel
theorem sieve29_26_2 : svRange 400 280 33554432 20 14 6864 23 = true := by decide +kernel
theorem sieve29_26_3 : svRange 400 280 33554432 20 14 6887 1 = true := by decide +kernel
theorem sieve29_26_4 : svRange 400 280 33554432 20 14 6888 7 = true := by decide +kernel
theorem sieve29_26_5 : svRange 400 280 33554432 20 14 6895 1 = true := by decide +kernel
theorem sieve29_26_6 : svRange 400 280 33554432 20 14 6896 15 = true := by decide +kernel
theorem sieve29_26_7 : svRange 400 280 33554432 20 14 6911 1 = true := by decide +kernel
theorem sieve29_26_8 : svRange 400 280 33554432 20 14 6912 27 = true := by decide +kernel
theorem sieve29_26_9 : svRange 400 280 33554432 20 14 6939 1 = true := by decide +kernel
theorem sieve29_26_10 : svRange 400 280 33554432 20 14 6940 3 = true := by decide +kernel
theorem sieve29_26_11 : svRange 400 280 33554432 20 14 6943 1 = true := by decide +kernel
theorem sieve29_26_12 : svRange 400 280 33554432 20 14 6944 95 = true := by decide +kernel
theorem sieve29_26_13 : svRange 400 280 33554432 20 14 7039 64 = true := by decide +kernel
theorem sieve29_26_14 : svRange 400 280 33554432 20 14 7103 31 = true := by decide +kernel
theorem sieve29_26_15 : svRange 400 280 33554432 20 14 7134 1 = true := by decide +kernel
theorem sieve29_26_16 : svRange 400 280 33554432 20 14 7135 10 = true := by decide +kernel

theorem sieve29_part26 : RootsOK 400 280 33554432 20 14 6826 7145 :=
  rootsOK_cons sieve29_26_0 <|
  rootsOK_cons sieve29_26_1 <|
  rootsOK_cons sieve29_26_2 <|
  rootsOK_cons sieve29_26_3 <|
  rootsOK_cons sieve29_26_4 <|
  rootsOK_cons sieve29_26_5 <|
  rootsOK_cons sieve29_26_6 <|
  rootsOK_cons sieve29_26_7 <|
  rootsOK_cons sieve29_26_8 <|
  rootsOK_cons sieve29_26_9 <|
  rootsOK_cons sieve29_26_10 <|
  rootsOK_cons sieve29_26_11 <|
  rootsOK_cons sieve29_26_12 <|
  rootsOK_cons sieve29_26_13 <|
  rootsOK_cons sieve29_26_14 <|
  rootsOK_cons sieve29_26_15 <|
  rootsOK_cons sieve29_26_16 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_26_0
#print axioms Collatz.sieve29_part26
