import Sieve

/-! Kernel certificate part 41 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [10652, 10919), 11 blocks, estimated cost 2209061 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_41_0 : svRange 400 280 33554432 20 14 10652 35 = true := by decide +kernel
theorem sieve29_41_1 : svRange 400 280 33554432 20 14 10687 1 = true := by decide +kernel
theorem sieve29_41_2 : svRange 400 280 33554432 20 14 10688 30 = true := by decide +kernel
theorem sieve29_41_3 : svRange 400 280 33554432 20 14 10718 1 = true := by decide +kernel
theorem sieve29_41_4 : svRange 400 280 33554432 20 14 10719 1 = true := by decide +kernel
theorem sieve29_41_5 : svRange 400 280 33554432 20 14 10720 31 = true := by decide +kernel
theorem sieve29_41_6 : svRange 400 280 33554432 20 14 10751 1 = true := by decide +kernel
theorem sieve29_41_7 : svRange 400 280 33554432 20 14 10752 91 = true := by decide +kernel
theorem sieve29_41_8 : svRange 400 280 33554432 20 14 10843 36 = true := by decide +kernel
theorem sieve29_41_9 : svRange 400 280 33554432 20 14 10879 1 = true := by decide +kernel
theorem sieve29_41_10 : svRange 400 280 33554432 20 14 10880 39 = true := by decide +kernel

theorem sieve29_part41 : RootsOK 400 280 33554432 20 14 10652 10919 :=
  rootsOK_cons sieve29_41_0 <|
  rootsOK_cons sieve29_41_1 <|
  rootsOK_cons sieve29_41_2 <|
  rootsOK_cons sieve29_41_3 <|
  rootsOK_cons sieve29_41_4 <|
  rootsOK_cons sieve29_41_5 <|
  rootsOK_cons sieve29_41_6 <|
  rootsOK_cons sieve29_41_7 <|
  rootsOK_cons sieve29_41_8 <|
  rootsOK_cons sieve29_41_9 <|
  rootsOK_cons sieve29_41_10 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_41_0
#print axioms Collatz.sieve29_part41
