import Sieve

/-! Kernel certificate part 63 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [16156, 16384), 10 blocks, estimated cost 2189645 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_63_0 : svRange 400 280 33554432 20 14 16156 75 = true := by decide +kernel
theorem sieve29_63_1 : svRange 400 280 33554432 20 14 16231 1 = true := by decide +kernel
theorem sieve29_63_2 : svRange 400 280 33554432 20 14 16232 23 = true := by decide +kernel
theorem sieve29_63_3 : svRange 400 280 33554432 20 14 16255 42 = true := by decide +kernel
theorem sieve29_63_4 : svRange 400 280 33554432 20 14 16297 22 = true := by decide +kernel
theorem sieve29_63_5 : svRange 400 280 33554432 20 14 16319 48 = true := by decide +kernel
theorem sieve29_63_6 : svRange 400 280 33554432 20 14 16367 12 = true := by decide +kernel
theorem sieve29_63_7 : svRange 400 280 33554432 20 14 16379 3 = true := by decide +kernel
theorem sieve29_63_8 : svRange 400 280 33554432 20 14 16382 1 = true := by decide +kernel
theorem sieve29_63_9 : svRange 400 280 33554432 20 14 16383 1 = true := by decide +kernel

theorem sieve29_part63 : RootsOK 400 280 33554432 20 14 16156 16384 :=
  rootsOK_cons sieve29_63_0 <|
  rootsOK_cons sieve29_63_1 <|
  rootsOK_cons sieve29_63_2 <|
  rootsOK_cons sieve29_63_3 <|
  rootsOK_cons sieve29_63_4 <|
  rootsOK_cons sieve29_63_5 <|
  rootsOK_cons sieve29_63_6 <|
  rootsOK_cons sieve29_63_7 <|
  rootsOK_cons sieve29_63_8 <|
  rootsOK_cons sieve29_63_9 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_63_0
#print axioms Collatz.sieve29_part63
