import Sieve

/-! Kernel certificate part 3 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [6313, 8359), 38 blocks, estimated cost 1269708 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace Collatz

theorem sieve25_3_0 : svRange 400 32 16777216 20 14 6313 56 = true := by decide +kernel
theorem sieve25_3_1 : svRange 400 32 16777216 20 14 6369 29 = true := by decide +kernel
theorem sieve25_3_2 : svRange 400 32 16777216 20 14 6398 64 = true := by decide +kernel
theorem sieve25_3_3 : svRange 400 32 16777216 20 14 6462 9 = true := by decide +kernel
theorem sieve25_3_4 : svRange 400 32 16777216 20 14 6471 120 = true := by decide +kernel
theorem sieve25_3_5 : svRange 400 32 16777216 20 14 6591 32 = true := by decide +kernel
theorem sieve25_3_6 : svRange 400 32 16777216 20 14 6623 32 = true := by decide +kernel
theorem sieve25_3_7 : svRange 400 32 16777216 20 14 6655 128 = true := by decide +kernel
theorem sieve25_3_8 : svRange 400 32 16777216 20 14 6783 42 = true := by decide +kernel
theorem sieve25_3_9 : svRange 400 32 16777216 20 14 6825 62 = true := by decide +kernel
theorem sieve25_3_10 : svRange 400 32 16777216 20 14 6887 24 = true := by decide +kernel
theorem sieve25_3_11 : svRange 400 32 16777216 20 14 6911 32 = true := by decide +kernel
theorem sieve25_3_12 : svRange 400 32 16777216 20 14 6943 138 = true := by decide +kernel
theorem sieve25_3_13 : svRange 400 32 16777216 20 14 7081 64 = true := by decide +kernel
theorem sieve25_3_14 : svRange 400 32 16777216 20 14 7145 22 = true := by decide +kernel
theorem sieve25_3_15 : svRange 400 32 16777216 20 14 7167 63 = true := by decide +kernel
theorem sieve25_3_16 : svRange 400 32 16777216 20 14 7230 75 = true := by decide +kernel
theorem sieve25_3_17 : svRange 400 32 16777216 20 14 7305 32 = true := by decide +kernel
theorem sieve25_3_18 : svRange 400 32 16777216 20 14 7337 85 = true := by decide +kernel
theorem sieve25_3_19 : svRange 400 32 16777216 20 14 7422 1 = true := by decide +kernel
theorem sieve25_3_20 : svRange 400 32 16777216 20 14 7423 48 = true := by decide +kernel
theorem sieve25_3_21 : svRange 400 32 16777216 20 14 7471 112 = true := by decide +kernel
theorem sieve25_3_22 : svRange 400 32 16777216 20 14 7583 64 = true := by decide +kernel
theorem sieve25_3_23 : svRange 400 32 16777216 20 14 7647 32 = true := by decide +kernel
theorem sieve25_3_24 : svRange 400 32 16777216 20 14 7679 42 = true := by decide +kernel
theorem sieve25_3_25 : svRange 400 32 16777216 20 14 7721 86 = true := by decide +kernel
theorem sieve25_3_26 : svRange 400 32 16777216 20 14 7807 32 = true := by decide +kernel
theorem sieve25_3_27 : svRange 400 32 16777216 20 14 7839 48 = true := by decide +kernel
theorem sieve25_3_28 : svRange 400 32 16777216 20 14 7887 48 = true := by decide +kernel
theorem sieve25_3_29 : svRange 400 32 16777216 20 14 7935 28 = true := by decide +kernel
theorem sieve25_3_30 : svRange 400 32 16777216 20 14 7963 76 = true := by decide +kernel
theorem sieve25_3_31 : svRange 400 32 16777216 20 14 8039 88 = true := by decide +kernel
theorem sieve25_3_32 : svRange 400 32 16777216 20 14 8127 63 = true := by decide +kernel
theorem sieve25_3_33 : svRange 400 32 16777216 20 14 8190 1 = true := by decide +kernel
theorem sieve25_3_34 : svRange 400 32 16777216 20 14 8191 28 = true := by decide +kernel
theorem sieve25_3_35 : svRange 400 32 16777216 20 14 8219 35 = true := by decide +kernel
theorem sieve25_3_36 : svRange 400 32 16777216 20 14 8254 65 = true := by decide +kernel
theorem sieve25_3_37 : svRange 400 32 16777216 20 14 8319 40 = true := by decide +kernel

theorem sieve25_part3 : RootsOK 400 32 16777216 20 14 6313 8359 :=
  rootsOK_cons sieve25_3_0 <|
  rootsOK_cons sieve25_3_1 <|
  rootsOK_cons sieve25_3_2 <|
  rootsOK_cons sieve25_3_3 <|
  rootsOK_cons sieve25_3_4 <|
  rootsOK_cons sieve25_3_5 <|
  rootsOK_cons sieve25_3_6 <|
  rootsOK_cons sieve25_3_7 <|
  rootsOK_cons sieve25_3_8 <|
  rootsOK_cons sieve25_3_9 <|
  rootsOK_cons sieve25_3_10 <|
  rootsOK_cons sieve25_3_11 <|
  rootsOK_cons sieve25_3_12 <|
  rootsOK_cons sieve25_3_13 <|
  rootsOK_cons sieve25_3_14 <|
  rootsOK_cons sieve25_3_15 <|
  rootsOK_cons sieve25_3_16 <|
  rootsOK_cons sieve25_3_17 <|
  rootsOK_cons sieve25_3_18 <|
  rootsOK_cons sieve25_3_19 <|
  rootsOK_cons sieve25_3_20 <|
  rootsOK_cons sieve25_3_21 <|
  rootsOK_cons sieve25_3_22 <|
  rootsOK_cons sieve25_3_23 <|
  rootsOK_cons sieve25_3_24 <|
  rootsOK_cons sieve25_3_25 <|
  rootsOK_cons sieve25_3_26 <|
  rootsOK_cons sieve25_3_27 <|
  rootsOK_cons sieve25_3_28 <|
  rootsOK_cons sieve25_3_29 <|
  rootsOK_cons sieve25_3_30 <|
  rootsOK_cons sieve25_3_31 <|
  rootsOK_cons sieve25_3_32 <|
  rootsOK_cons sieve25_3_33 <|
  rootsOK_cons sieve25_3_34 <|
  rootsOK_cons sieve25_3_35 <|
  rootsOK_cons sieve25_3_36 <|
  rootsOK_cons sieve25_3_37 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve25_3_0
#print axioms Collatz.sieve25_part3
