import Sieve

/-! Kernel certificate part 5 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [1279, 1519), 15 blocks, estimated cost 2239753 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_5_0 : svRange 400 280 33554432 20 14 1279 1 = true := by decide +kernel
theorem sieve29_5_1 : svRange 400 280 33554432 20 14 1280 27 = true := by decide +kernel
theorem sieve29_5_2 : svRange 400 280 33554432 20 14 1307 1 = true := by decide +kernel
theorem sieve29_5_3 : svRange 400 280 33554432 20 14 1308 75 = true := by decide +kernel
theorem sieve29_5_4 : svRange 400 280 33554432 20 14 1383 23 = true := by decide +kernel
theorem sieve29_5_5 : svRange 400 280 33554432 20 14 1406 1 = true := by decide +kernel
theorem sieve29_5_6 : svRange 400 280 33554432 20 14 1407 1 = true := by decide +kernel
theorem sieve29_5_7 : svRange 400 280 33554432 20 14 1408 31 = true := by decide +kernel
theorem sieve29_5_8 : svRange 400 280 33554432 20 14 1439 1 = true := by decide +kernel
theorem sieve29_5_9 : svRange 400 280 33554432 20 14 1440 31 = true := by decide +kernel
theorem sieve29_5_10 : svRange 400 280 33554432 20 14 1471 1 = true := by decide +kernel
theorem sieve29_5_11 : svRange 400 280 33554432 20 14 1472 30 = true := by decide +kernel
theorem sieve29_5_12 : svRange 400 280 33554432 20 14 1502 1 = true := by decide +kernel
theorem sieve29_5_13 : svRange 400 280 33554432 20 14 1503 8 = true := by decide +kernel
theorem sieve29_5_14 : svRange 400 280 33554432 20 14 1511 8 = true := by decide +kernel

theorem sieve29_part5 : RootsOK 400 280 33554432 20 14 1279 1519 :=
  rootsOK_cons sieve29_5_0 <|
  rootsOK_cons sieve29_5_1 <|
  rootsOK_cons sieve29_5_2 <|
  rootsOK_cons sieve29_5_3 <|
  rootsOK_cons sieve29_5_4 <|
  rootsOK_cons sieve29_5_5 <|
  rootsOK_cons sieve29_5_6 <|
  rootsOK_cons sieve29_5_7 <|
  rootsOK_cons sieve29_5_8 <|
  rootsOK_cons sieve29_5_9 <|
  rootsOK_cons sieve29_5_10 <|
  rootsOK_cons sieve29_5_11 <|
  rootsOK_cons sieve29_5_12 <|
  rootsOK_cons sieve29_5_13 <|
  rootsOK_cons sieve29_5_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_5_0
#print axioms Collatz.sieve29_part5
