import Sieve

/-! Kernel certificate part 7 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [14495, 16384), 36 blocks,
  estimated cost 1169706 units. Generated by a script; `decide +kernel` only. -/

namespace Collatz

theorem sieve24_7_0 : svRange 400 16 2 20 14 14495 48 = true := by decide +kernel
theorem sieve24_7_1 : svRange 400 16 2 20 14 14543 18 = true := by decide +kernel
theorem sieve24_7_2 : svRange 400 16 2 20 14 14561 26 = true := by decide +kernel
theorem sieve24_7_3 : svRange 400 16 2 20 14 14587 68 = true := by decide +kernel
theorem sieve24_7_4 : svRange 400 16 2 20 14 14655 64 = true := by decide +kernel
theorem sieve24_7_5 : svRange 400 16 2 20 14 14719 64 = true := by decide +kernel
theorem sieve24_7_6 : svRange 400 16 2 20 14 14783 48 = true := by decide +kernel
theorem sieve24_7_7 : svRange 400 16 2 20 14 14831 16 = true := by decide +kernel
theorem sieve24_7_8 : svRange 400 16 2 20 14 14847 112 = true := by decide +kernel
theorem sieve24_7_9 : svRange 400 16 2 20 14 14959 56 = true := by decide +kernel
theorem sieve24_7_10 : svRange 400 16 2 20 14 15015 40 = true := by decide +kernel
theorem sieve24_7_11 : svRange 400 16 2 20 14 15055 44 = true := by decide +kernel
theorem sieve24_7_12 : svRange 400 16 2 20 14 15099 67 = true := by decide +kernel
theorem sieve24_7_13 : svRange 400 16 2 20 14 15166 65 = true := by decide +kernel
theorem sieve24_7_14 : svRange 400 16 2 20 14 15231 106 = true := by decide +kernel
theorem sieve24_7_15 : svRange 400 16 2 20 14 15337 22 = true := by decide +kernel
theorem sieve24_7_16 : svRange 400 16 2 20 14 15359 64 = true := by decide +kernel
theorem sieve24_7_17 : svRange 400 16 2 20 14 15423 64 = true := by decide +kernel
theorem sieve24_7_18 : svRange 400 16 2 20 14 15487 40 = true := by decide +kernel
theorem sieve24_7_19 : svRange 400 16 2 20 14 15527 87 = true := by decide +kernel
theorem sieve24_7_20 : svRange 400 16 2 20 14 15614 49 = true := by decide +kernel
theorem sieve24_7_21 : svRange 400 16 2 20 14 15663 79 = true := by decide +kernel
theorem sieve24_7_22 : svRange 400 16 2 20 14 15742 65 = true := by decide +kernel
theorem sieve24_7_23 : svRange 400 16 2 20 14 15807 63 = true := by decide +kernel
theorem sieve24_7_24 : svRange 400 16 2 20 14 15870 1 = true := by decide +kernel
theorem sieve24_7_25 : svRange 400 16 2 20 14 15871 32 = true := by decide +kernel
theorem sieve24_7_26 : svRange 400 16 2 20 14 15903 96 = true := by decide +kernel
theorem sieve24_7_27 : svRange 400 16 2 20 14 15999 42 = true := by decide +kernel
theorem sieve24_7_28 : svRange 400 16 2 20 14 16041 38 = true := by decide +kernel
theorem sieve24_7_29 : svRange 400 16 2 20 14 16079 48 = true := by decide +kernel
theorem sieve24_7_30 : svRange 400 16 2 20 14 16127 28 = true := by decide +kernel
theorem sieve24_7_31 : svRange 400 16 2 20 14 16155 76 = true := by decide +kernel
theorem sieve24_7_32 : svRange 400 16 2 20 14 16231 56 = true := by decide +kernel
theorem sieve24_7_33 : svRange 400 16 2 20 14 16287 95 = true := by decide +kernel
theorem sieve24_7_34 : svRange 400 16 2 20 14 16382 1 = true := by decide +kernel
theorem sieve24_7_35 : svRange 400 16 2 20 14 16383 1 = true := by decide +kernel

theorem sieve24_part7 : RootsOK 400 16 2 20 14 14495 16384 :=
  rootsOK_cons sieve24_7_0 <|
  rootsOK_cons sieve24_7_1 <|
  rootsOK_cons sieve24_7_2 <|
  rootsOK_cons sieve24_7_3 <|
  rootsOK_cons sieve24_7_4 <|
  rootsOK_cons sieve24_7_5 <|
  rootsOK_cons sieve24_7_6 <|
  rootsOK_cons sieve24_7_7 <|
  rootsOK_cons sieve24_7_8 <|
  rootsOK_cons sieve24_7_9 <|
  rootsOK_cons sieve24_7_10 <|
  rootsOK_cons sieve24_7_11 <|
  rootsOK_cons sieve24_7_12 <|
  rootsOK_cons sieve24_7_13 <|
  rootsOK_cons sieve24_7_14 <|
  rootsOK_cons sieve24_7_15 <|
  rootsOK_cons sieve24_7_16 <|
  rootsOK_cons sieve24_7_17 <|
  rootsOK_cons sieve24_7_18 <|
  rootsOK_cons sieve24_7_19 <|
  rootsOK_cons sieve24_7_20 <|
  rootsOK_cons sieve24_7_21 <|
  rootsOK_cons sieve24_7_22 <|
  rootsOK_cons sieve24_7_23 <|
  rootsOK_cons sieve24_7_24 <|
  rootsOK_cons sieve24_7_25 <|
  rootsOK_cons sieve24_7_26 <|
  rootsOK_cons sieve24_7_27 <|
  rootsOK_cons sieve24_7_28 <|
  rootsOK_cons sieve24_7_29 <|
  rootsOK_cons sieve24_7_30 <|
  rootsOK_cons sieve24_7_31 <|
  rootsOK_cons sieve24_7_32 <|
  rootsOK_cons sieve24_7_33 <|
  rootsOK_cons sieve24_7_34 <|
  rootsOK_cons sieve24_7_35 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve24_7_0
#print axioms Collatz.sieve24_part7
