import Sieve

/-! Kernel certificate part 5 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [10409, 12359), 37 blocks, estimated cost 1260143 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace Collatz

theorem sieve25_5_0 : svRange 400 32 16777216 20 14 10409 56 = true := by decide +kernel
theorem sieve25_5_1 : svRange 400 32 16777216 20 14 10465 26 = true := by decide +kernel
theorem sieve25_5_2 : svRange 400 32 16777216 20 14 10491 76 = true := by decide +kernel
theorem sieve25_5_3 : svRange 400 32 16777216 20 14 10567 88 = true := by decide +kernel
theorem sieve25_5_4 : svRange 400 32 16777216 20 14 10655 63 = true := by decide +kernel
theorem sieve25_5_5 : svRange 400 32 16777216 20 14 10718 1 = true := by decide +kernel
theorem sieve25_5_6 : svRange 400 32 16777216 20 14 10719 32 = true := by decide +kernel
theorem sieve25_5_7 : svRange 400 32 16777216 20 14 10751 92 = true := by decide +kernel
theorem sieve25_5_8 : svRange 400 32 16777216 20 14 10843 76 = true := by decide +kernel
theorem sieve25_5_9 : svRange 400 32 16777216 20 14 10919 24 = true := by decide +kernel
theorem sieve25_5_10 : svRange 400 32 16777216 20 14 10943 40 = true := by decide +kernel
theorem sieve25_5_11 : svRange 400 32 16777216 20 14 10983 20 = true := by decide +kernel
theorem sieve25_5_12 : svRange 400 32 16777216 20 14 11003 36 = true := by decide +kernel
theorem sieve25_5_13 : svRange 400 32 16777216 20 14 11039 72 = true := by decide +kernel
theorem sieve25_5_14 : svRange 400 32 16777216 20 14 11111 24 = true := by decide +kernel
theorem sieve25_5_15 : svRange 400 32 16777216 20 14 11135 64 = true := by decide +kernel
theorem sieve25_5_16 : svRange 400 32 16777216 20 14 11199 64 = true := by decide +kernel
theorem sieve25_5_17 : svRange 400 32 16777216 20 14 11263 32 = true := by decide +kernel
theorem sieve25_5_18 : svRange 400 32 16777216 20 14 11295 80 = true := by decide +kernel
theorem sieve25_5_19 : svRange 400 32 16777216 20 14 11375 48 = true := by decide +kernel
theorem sieve25_5_20 : svRange 400 32 16777216 20 14 11423 80 = true := by decide +kernel
theorem sieve25_5_21 : svRange 400 32 16777216 20 14 11503 15 = true := by decide +kernel
theorem sieve25_5_22 : svRange 400 32 16777216 20 14 11518 64 = true := by decide +kernel
theorem sieve25_5_23 : svRange 400 32 16777216 20 14 11582 41 = true := by decide +kernel
theorem sieve25_5_24 : svRange 400 32 16777216 20 14 11623 104 = true := by decide +kernel
theorem sieve25_5_25 : svRange 400 32 16777216 20 14 11727 48 = true := by decide +kernel
theorem sieve25_5_26 : svRange 400 32 16777216 20 14 11775 112 = true := by decide +kernel
theorem sieve25_5_27 : svRange 400 32 16777216 20 14 11887 26 = true := by decide +kernel
theorem sieve25_5_28 : svRange 400 32 16777216 20 14 11913 54 = true := by decide +kernel
theorem sieve25_5_29 : svRange 400 32 16777216 20 14 11967 64 = true := by decide +kernel
theorem sieve25_5_30 : svRange 400 32 16777216 20 14 12031 28 = true := by decide +kernel
theorem sieve25_5_31 : svRange 400 32 16777216 20 14 12059 76 = true := by decide +kernel
theorem sieve25_5_32 : svRange 400 32 16777216 20 14 12135 56 = true := by decide +kernel
theorem sieve25_5_33 : svRange 400 32 16777216 20 14 12191 66 = true := by decide +kernel
theorem sieve25_5_34 : svRange 400 32 16777216 20 14 12257 30 = true := by decide +kernel
theorem sieve25_5_35 : svRange 400 32 16777216 20 14 12287 32 = true := by decide +kernel
theorem sieve25_5_36 : svRange 400 32 16777216 20 14 12319 40 = true := by decide +kernel

theorem sieve25_part5 : RootsOK 400 32 16777216 20 14 10409 12359 :=
  rootsOK_cons sieve25_5_0 <|
  rootsOK_cons sieve25_5_1 <|
  rootsOK_cons sieve25_5_2 <|
  rootsOK_cons sieve25_5_3 <|
  rootsOK_cons sieve25_5_4 <|
  rootsOK_cons sieve25_5_5 <|
  rootsOK_cons sieve25_5_6 <|
  rootsOK_cons sieve25_5_7 <|
  rootsOK_cons sieve25_5_8 <|
  rootsOK_cons sieve25_5_9 <|
  rootsOK_cons sieve25_5_10 <|
  rootsOK_cons sieve25_5_11 <|
  rootsOK_cons sieve25_5_12 <|
  rootsOK_cons sieve25_5_13 <|
  rootsOK_cons sieve25_5_14 <|
  rootsOK_cons sieve25_5_15 <|
  rootsOK_cons sieve25_5_16 <|
  rootsOK_cons sieve25_5_17 <|
  rootsOK_cons sieve25_5_18 <|
  rootsOK_cons sieve25_5_19 <|
  rootsOK_cons sieve25_5_20 <|
  rootsOK_cons sieve25_5_21 <|
  rootsOK_cons sieve25_5_22 <|
  rootsOK_cons sieve25_5_23 <|
  rootsOK_cons sieve25_5_24 <|
  rootsOK_cons sieve25_5_25 <|
  rootsOK_cons sieve25_5_26 <|
  rootsOK_cons sieve25_5_27 <|
  rootsOK_cons sieve25_5_28 <|
  rootsOK_cons sieve25_5_29 <|
  rootsOK_cons sieve25_5_30 <|
  rootsOK_cons sieve25_5_31 <|
  rootsOK_cons sieve25_5_32 <|
  rootsOK_cons sieve25_5_33 <|
  rootsOK_cons sieve25_5_34 <|
  rootsOK_cons sieve25_5_35 <|
  rootsOK_cons sieve25_5_36 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve25_5_0
#print axioms Collatz.sieve25_part5
