import Sieve

/-! Kernel certificate part 16 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [4137, 4414), 18 blocks, estimated cost 2315815 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_16_0 : svRange 400 280 33554432 20 14 4137 30 = true := by decide +kernel
theorem sieve29_16_1 : svRange 400 280 33554432 20 14 4167 40 = true := by decide +kernel
theorem sieve29_16_2 : svRange 400 280 33554432 20 14 4207 26 = true := by decide +kernel
theorem sieve29_16_3 : svRange 400 280 33554432 20 14 4233 1 = true := by decide +kernel
theorem sieve29_16_4 : svRange 400 280 33554432 20 14 4234 21 = true := by decide +kernel
theorem sieve29_16_5 : svRange 400 280 33554432 20 14 4255 1 = true := by decide +kernel
theorem sieve29_16_6 : svRange 400 280 33554432 20 14 4256 7 = true := by decide +kernel
theorem sieve29_16_7 : svRange 400 280 33554432 20 14 4263 1 = true := by decide +kernel
theorem sieve29_16_8 : svRange 400 280 33554432 20 14 4264 1 = true := by decide +kernel
theorem sieve29_16_9 : svRange 400 280 33554432 20 14 4265 1 = true := by decide +kernel
theorem sieve29_16_10 : svRange 400 280 33554432 20 14 4266 52 = true := by decide +kernel
theorem sieve29_16_11 : svRange 400 280 33554432 20 14 4318 1 = true := by decide +kernel
theorem sieve29_16_12 : svRange 400 280 33554432 20 14 4319 16 = true := by decide +kernel
theorem sieve29_16_13 : svRange 400 280 33554432 20 14 4335 12 = true := by decide +kernel
theorem sieve29_16_14 : svRange 400 280 33554432 20 14 4347 1 = true := by decide +kernel
theorem sieve29_16_15 : svRange 400 280 33554432 20 14 4348 3 = true := by decide +kernel
theorem sieve29_16_16 : svRange 400 280 33554432 20 14 4351 28 = true := by decide +kernel
theorem sieve29_16_17 : svRange 400 280 33554432 20 14 4379 35 = true := by decide +kernel

theorem sieve29_part16 : RootsOK 400 280 33554432 20 14 4137 4414 :=
  rootsOK_cons sieve29_16_0 <|
  rootsOK_cons sieve29_16_1 <|
  rootsOK_cons sieve29_16_2 <|
  rootsOK_cons sieve29_16_3 <|
  rootsOK_cons sieve29_16_4 <|
  rootsOK_cons sieve29_16_5 <|
  rootsOK_cons sieve29_16_6 <|
  rootsOK_cons sieve29_16_7 <|
  rootsOK_cons sieve29_16_8 <|
  rootsOK_cons sieve29_16_9 <|
  rootsOK_cons sieve29_16_10 <|
  rootsOK_cons sieve29_16_11 <|
  rootsOK_cons sieve29_16_12 <|
  rootsOK_cons sieve29_16_13 <|
  rootsOK_cons sieve29_16_14 <|
  rootsOK_cons sieve29_16_15 <|
  rootsOK_cons sieve29_16_16 <|
  rootsOK_cons sieve29_16_17 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_16_0
#print axioms Collatz.sieve29_part16
