import Sieve

/-! Kernel certificate part 33 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [8607, 8874), 15 blocks, estimated cost 2430339 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_33_0 : svRange 400 280 33554432 20 14 8607 10 = true := by decide +kernel
theorem sieve29_33_1 : svRange 400 280 33554432 20 14 8617 22 = true := by decide +kernel
theorem sieve29_33_2 : svRange 400 280 33554432 20 14 8639 1 = true := by decide +kernel
theorem sieve29_33_3 : svRange 400 280 33554432 20 14 8640 31 = true := by decide +kernel
theorem sieve29_33_4 : svRange 400 280 33554432 20 14 8671 8 = true := by decide +kernel
theorem sieve29_33_5 : svRange 400 280 33554432 20 14 8679 8 = true := by decide +kernel
theorem sieve29_33_6 : svRange 400 280 33554432 20 14 8687 16 = true := by decide +kernel
theorem sieve29_33_7 : svRange 400 280 33554432 20 14 8703 1 = true := by decide +kernel
theorem sieve29_33_8 : svRange 400 280 33554432 20 14 8704 47 = true := by decide +kernel
theorem sieve29_33_9 : svRange 400 280 33554432 20 14 8751 1 = true := by decide +kernel
theorem sieve29_33_10 : svRange 400 280 33554432 20 14 8752 78 = true := by decide +kernel
theorem sieve29_33_11 : svRange 400 280 33554432 20 14 8830 1 = true := by decide +kernel
theorem sieve29_33_12 : svRange 400 280 33554432 20 14 8831 1 = true := by decide +kernel
theorem sieve29_33_13 : svRange 400 280 33554432 20 14 8832 41 = true := by decide +kernel
theorem sieve29_33_14 : svRange 400 280 33554432 20 14 8873 1 = true := by decide +kernel

theorem sieve29_part33 : RootsOK 400 280 33554432 20 14 8607 8874 :=
  rootsOK_cons sieve29_33_0 <|
  rootsOK_cons sieve29_33_1 <|
  rootsOK_cons sieve29_33_2 <|
  rootsOK_cons sieve29_33_3 <|
  rootsOK_cons sieve29_33_4 <|
  rootsOK_cons sieve29_33_5 <|
  rootsOK_cons sieve29_33_6 <|
  rootsOK_cons sieve29_33_7 <|
  rootsOK_cons sieve29_33_8 <|
  rootsOK_cons sieve29_33_9 <|
  rootsOK_cons sieve29_33_10 <|
  rootsOK_cons sieve29_33_11 <|
  rootsOK_cons sieve29_33_12 <|
  rootsOK_cons sieve29_33_13 <|
  rootsOK_cons sieve29_33_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_33_0
#print axioms Collatz.sieve29_part33
