import Sieve

/-! Kernel certificate part 14 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [3631, 3871), 15 blocks, estimated cost 2201705 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_14_0 : svRange 400 280 33554432 20 14 3631 1 = true := by decide +kernel
theorem sieve29_14_1 : svRange 400 280 33554432 20 14 3632 79 = true := by decide +kernel
theorem sieve29_14_2 : svRange 400 280 33554432 20 14 3711 1 = true := by decide +kernel
theorem sieve29_14_3 : svRange 400 280 33554432 20 14 3712 9 = true := by decide +kernel
theorem sieve29_14_4 : svRange 400 280 33554432 20 14 3721 1 = true := by decide +kernel
theorem sieve29_14_5 : svRange 400 280 33554432 20 14 3722 17 = true := by decide +kernel
theorem sieve29_14_6 : svRange 400 280 33554432 20 14 3739 1 = true := by decide +kernel
theorem sieve29_14_7 : svRange 400 280 33554432 20 14 3740 13 = true := by decide +kernel
theorem sieve29_14_8 : svRange 400 280 33554432 20 14 3753 22 = true := by decide +kernel
theorem sieve29_14_9 : svRange 400 280 33554432 20 14 3775 16 = true := by decide +kernel
theorem sieve29_14_10 : svRange 400 280 33554432 20 14 3791 1 = true := by decide +kernel
theorem sieve29_14_11 : svRange 400 280 33554432 20 14 3792 46 = true := by decide +kernel
theorem sieve29_14_12 : svRange 400 280 33554432 20 14 3838 1 = true := by decide +kernel
theorem sieve29_14_13 : svRange 400 280 33554432 20 14 3839 1 = true := by decide +kernel
theorem sieve29_14_14 : svRange 400 280 33554432 20 14 3840 31 = true := by decide +kernel

theorem sieve29_part14 : RootsOK 400 280 33554432 20 14 3631 3871 :=
  rootsOK_cons sieve29_14_0 <|
  rootsOK_cons sieve29_14_1 <|
  rootsOK_cons sieve29_14_2 <|
  rootsOK_cons sieve29_14_3 <|
  rootsOK_cons sieve29_14_4 <|
  rootsOK_cons sieve29_14_5 <|
  rootsOK_cons sieve29_14_6 <|
  rootsOK_cons sieve29_14_7 <|
  rootsOK_cons sieve29_14_8 <|
  rootsOK_cons sieve29_14_9 <|
  rootsOK_cons sieve29_14_10 <|
  rootsOK_cons sieve29_14_11 <|
  rootsOK_cons sieve29_14_12 <|
  rootsOK_cons sieve29_14_13 <|
  rootsOK_cons sieve29_14_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_14_0
#print axioms Collatz.sieve29_part14
