import Sieve

/-! Kernel certificate part 3 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [796, 1023), 14 blocks, estimated cost 2196045 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_3_0 : svRange 400 280 33554432 20 14 796 75 = true := by decide +kernel
theorem sieve29_3_1 : svRange 400 280 33554432 20 14 871 1 = true := by decide +kernel
theorem sieve29_3_2 : svRange 400 280 33554432 20 14 872 23 = true := by decide +kernel
theorem sieve29_3_3 : svRange 400 280 33554432 20 14 895 32 = true := by decide +kernel
theorem sieve29_3_4 : svRange 400 280 33554432 20 14 927 10 = true := by decide +kernel
theorem sieve29_3_5 : svRange 400 280 33554432 20 14 937 1 = true := by decide +kernel
theorem sieve29_3_6 : svRange 400 280 33554432 20 14 938 21 = true := by decide +kernel
theorem sieve29_3_7 : svRange 400 280 33554432 20 14 959 1 = true := by decide +kernel
theorem sieve29_3_8 : svRange 400 280 33554432 20 14 960 31 = true := by decide +kernel
theorem sieve29_3_9 : svRange 400 280 33554432 20 14 991 2 = true := by decide +kernel
theorem sieve29_3_10 : svRange 400 280 33554432 20 14 993 8 = true := by decide +kernel
theorem sieve29_3_11 : svRange 400 280 33554432 20 14 1001 1 = true := by decide +kernel
theorem sieve29_3_12 : svRange 400 280 33554432 20 14 1002 20 = true := by decide +kernel
theorem sieve29_3_13 : svRange 400 280 33554432 20 14 1022 1 = true := by decide +kernel

theorem sieve29_part3 : RootsOK 400 280 33554432 20 14 796 1023 :=
  rootsOK_cons sieve29_3_0 <|
  rootsOK_cons sieve29_3_1 <|
  rootsOK_cons sieve29_3_2 <|
  rootsOK_cons sieve29_3_3 <|
  rootsOK_cons sieve29_3_4 <|
  rootsOK_cons sieve29_3_5 <|
  rootsOK_cons sieve29_3_6 <|
  rootsOK_cons sieve29_3_7 <|
  rootsOK_cons sieve29_3_8 <|
  rootsOK_cons sieve29_3_9 <|
  rootsOK_cons sieve29_3_10 <|
  rootsOK_cons sieve29_3_11 <|
  rootsOK_cons sieve29_3_12 <|
  rootsOK_cons sieve29_3_13 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_3_0
#print axioms Collatz.sieve29_part3
