import Sieve

/-! Kernel certificate part 5 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [10409, 12379), 37 blocks,
  estimated cost 1196990 units. Generated by a script; `decide +kernel` only. -/

namespace Collatz

theorem sieve24_5_0 : svRange 400 16 2 20 14 10409 56 = true := by decide +kernel
theorem sieve24_5_1 : svRange 400 16 2 20 14 10465 26 = true := by decide +kernel
theorem sieve24_5_2 : svRange 400 16 2 20 14 10491 76 = true := by decide +kernel
theorem sieve24_5_3 : svRange 400 16 2 20 14 10567 120 = true := by decide +kernel
theorem sieve24_5_4 : svRange 400 16 2 20 14 10687 31 = true := by decide +kernel
theorem sieve24_5_5 : svRange 400 16 2 20 14 10718 1 = true := by decide +kernel
theorem sieve24_5_6 : svRange 400 16 2 20 14 10719 32 = true := by decide +kernel
theorem sieve24_5_7 : svRange 400 16 2 20 14 10751 92 = true := by decide +kernel
theorem sieve24_5_8 : svRange 400 16 2 20 14 10843 78 = true := by decide +kernel
theorem sieve24_5_9 : svRange 400 16 2 20 14 10921 22 = true := by decide +kernel
theorem sieve24_5_10 : svRange 400 16 2 20 14 10943 40 = true := by decide +kernel
theorem sieve24_5_11 : svRange 400 16 2 20 14 10983 20 = true := by decide +kernel
theorem sieve24_5_12 : svRange 400 16 2 20 14 11003 36 = true := by decide +kernel
theorem sieve24_5_13 : svRange 400 16 2 20 14 11039 72 = true := by decide +kernel
theorem sieve24_5_14 : svRange 400 16 2 20 14 11111 24 = true := by decide +kernel
theorem sieve24_5_15 : svRange 400 16 2 20 14 11135 64 = true := by decide +kernel
theorem sieve24_5_16 : svRange 400 16 2 20 14 11199 64 = true := by decide +kernel
theorem sieve24_5_17 : svRange 400 16 2 20 14 11263 32 = true := by decide +kernel
theorem sieve24_5_18 : svRange 400 16 2 20 14 11295 96 = true := by decide +kernel
theorem sieve24_5_19 : svRange 400 16 2 20 14 11391 32 = true := by decide +kernel
theorem sieve24_5_20 : svRange 400 16 2 20 14 11423 80 = true := by decide +kernel
theorem sieve24_5_21 : svRange 400 16 2 20 14 11503 15 = true := by decide +kernel
theorem sieve24_5_22 : svRange 400 16 2 20 14 11518 64 = true := by decide +kernel
theorem sieve24_5_23 : svRange 400 16 2 20 14 11582 41 = true := by decide +kernel
theorem sieve24_5_24 : svRange 400 16 2 20 14 11623 136 = true := by decide +kernel
theorem sieve24_5_25 : svRange 400 16 2 20 14 11759 44 = true := by decide +kernel
theorem sieve24_5_26 : svRange 400 16 2 20 14 11803 100 = true := by decide +kernel
theorem sieve24_5_27 : svRange 400 16 2 20 14 11903 28 = true := by decide +kernel
theorem sieve24_5_28 : svRange 400 16 2 20 14 11931 76 = true := by decide +kernel
theorem sieve24_5_29 : svRange 400 16 2 20 14 12007 24 = true := by decide +kernel
theorem sieve24_5_30 : svRange 400 16 2 20 14 12031 28 = true := by decide +kernel
theorem sieve24_5_31 : svRange 400 16 2 20 14 12059 76 = true := by decide +kernel
theorem sieve24_5_32 : svRange 400 16 2 20 14 12135 64 = true := by decide +kernel
theorem sieve24_5_33 : svRange 400 16 2 20 14 12199 87 = true := by decide +kernel
theorem sieve24_5_34 : svRange 400 16 2 20 14 12286 1 = true := by decide +kernel
theorem sieve24_5_35 : svRange 400 16 2 20 14 12287 42 = true := by decide +kernel
theorem sieve24_5_36 : svRange 400 16 2 20 14 12329 50 = true := by decide +kernel

theorem sieve24_part5 : RootsOK 400 16 2 20 14 10409 12379 :=
  rootsOK_cons sieve24_5_0 <|
  rootsOK_cons sieve24_5_1 <|
  rootsOK_cons sieve24_5_2 <|
  rootsOK_cons sieve24_5_3 <|
  rootsOK_cons sieve24_5_4 <|
  rootsOK_cons sieve24_5_5 <|
  rootsOK_cons sieve24_5_6 <|
  rootsOK_cons sieve24_5_7 <|
  rootsOK_cons sieve24_5_8 <|
  rootsOK_cons sieve24_5_9 <|
  rootsOK_cons sieve24_5_10 <|
  rootsOK_cons sieve24_5_11 <|
  rootsOK_cons sieve24_5_12 <|
  rootsOK_cons sieve24_5_13 <|
  rootsOK_cons sieve24_5_14 <|
  rootsOK_cons sieve24_5_15 <|
  rootsOK_cons sieve24_5_16 <|
  rootsOK_cons sieve24_5_17 <|
  rootsOK_cons sieve24_5_18 <|
  rootsOK_cons sieve24_5_19 <|
  rootsOK_cons sieve24_5_20 <|
  rootsOK_cons sieve24_5_21 <|
  rootsOK_cons sieve24_5_22 <|
  rootsOK_cons sieve24_5_23 <|
  rootsOK_cons sieve24_5_24 <|
  rootsOK_cons sieve24_5_25 <|
  rootsOK_cons sieve24_5_26 <|
  rootsOK_cons sieve24_5_27 <|
  rootsOK_cons sieve24_5_28 <|
  rootsOK_cons sieve24_5_29 <|
  rootsOK_cons sieve24_5_30 <|
  rootsOK_cons sieve24_5_31 <|
  rootsOK_cons sieve24_5_32 <|
  rootsOK_cons sieve24_5_33 <|
  rootsOK_cons sieve24_5_34 <|
  rootsOK_cons sieve24_5_35 <|
  rootsOK_cons sieve24_5_36 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve24_5_0
#print axioms Collatz.sieve24_part5
