import Sieve

/-! Kernel certificate part 4 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [1023, 1279), 16 blocks, estimated cost 2429179 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_4_0 : svRange 400 280 33554432 20 14 1023 1 = true := by decide +kernel
theorem sieve29_4_1 : svRange 400 280 33554432 20 14 1024 27 = true := by decide +kernel
theorem sieve29_4_2 : svRange 400 280 33554432 20 14 1051 1 = true := by decide +kernel
theorem sieve29_4_3 : svRange 400 280 33554432 20 14 1052 3 = true := by decide +kernel
theorem sieve29_4_4 : svRange 400 280 33554432 20 14 1055 1 = true := by decide +kernel
theorem sieve29_4_5 : svRange 400 280 33554432 20 14 1056 71 = true := by decide +kernel
theorem sieve29_4_6 : svRange 400 280 33554432 20 14 1127 34 = true := by decide +kernel
theorem sieve29_4_7 : svRange 400 280 33554432 20 14 1161 1 = true := by decide +kernel
theorem sieve29_4_8 : svRange 400 280 33554432 20 14 1162 21 = true := by decide +kernel
theorem sieve29_4_9 : svRange 400 280 33554432 20 14 1183 10 = true := by decide +kernel
theorem sieve29_4_10 : svRange 400 280 33554432 20 14 1193 56 = true := by decide +kernel
theorem sieve29_4_11 : svRange 400 280 33554432 20 14 1249 6 = true := by decide +kernel
theorem sieve29_4_12 : svRange 400 280 33554432 20 14 1255 8 = true := by decide +kernel
theorem sieve29_4_13 : svRange 400 280 33554432 20 14 1263 1 = true := by decide +kernel
theorem sieve29_4_14 : svRange 400 280 33554432 20 14 1264 14 = true := by decide +kernel
theorem sieve29_4_15 : svRange 400 280 33554432 20 14 1278 1 = true := by decide +kernel

theorem sieve29_part4 : RootsOK 400 280 33554432 20 14 1023 1279 :=
  rootsOK_cons sieve29_4_0 <|
  rootsOK_cons sieve29_4_1 <|
  rootsOK_cons sieve29_4_2 <|
  rootsOK_cons sieve29_4_3 <|
  rootsOK_cons sieve29_4_4 <|
  rootsOK_cons sieve29_4_5 <|
  rootsOK_cons sieve29_4_6 <|
  rootsOK_cons sieve29_4_7 <|
  rootsOK_cons sieve29_4_8 <|
  rootsOK_cons sieve29_4_9 <|
  rootsOK_cons sieve29_4_10 <|
  rootsOK_cons sieve29_4_11 <|
  rootsOK_cons sieve29_4_12 <|
  rootsOK_cons sieve29_4_13 <|
  rootsOK_cons sieve29_4_14 <|
  rootsOK_cons sieve29_4_15 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_4_0
#print axioms Collatz.sieve29_part4
