import Sieve

/-! Kernel certificate part 6 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [12379, 14495), 36 blocks,
  estimated cost 1179439 units. Generated by a script; `decide +kernel` only. -/

namespace Collatz

theorem sieve24_6_0 : svRange 400 16 2 20 14 12379 68 = true := by decide +kernel
theorem sieve24_6_1 : svRange 400 16 2 20 14 12447 32 = true := by decide +kernel
theorem sieve24_6_2 : svRange 400 16 2 20 14 12479 60 = true := by decide +kernel
theorem sieve24_6_3 : svRange 400 16 2 20 14 12539 67 = true := by decide +kernel
theorem sieve24_6_4 : svRange 400 16 2 20 14 12606 1 = true := by decide +kernel
theorem sieve24_6_5 : svRange 400 16 2 20 14 12607 159 = true := by decide +kernel
theorem sieve24_6_6 : svRange 400 16 2 20 14 12766 32 = true := by decide +kernel
theorem sieve24_6_7 : svRange 400 16 2 20 14 12798 49 = true := by decide +kernel
theorem sieve24_6_8 : svRange 400 16 2 20 14 12847 80 = true := by decide +kernel
theorem sieve24_6_9 : svRange 400 16 2 20 14 12927 32 = true := by decide +kernel
theorem sieve24_6_10 : svRange 400 16 2 20 14 12959 66 = true := by decide +kernel
theorem sieve24_6_11 : svRange 400 16 2 20 14 13025 14 = true := by decide +kernel
theorem sieve24_6_12 : svRange 400 16 2 20 14 13039 16 = true := by decide +kernel
theorem sieve24_6_13 : svRange 400 16 2 20 14 13055 104 = true := by decide +kernel
theorem sieve24_6_14 : svRange 400 16 2 20 14 13159 24 = true := by decide +kernel
theorem sieve24_6_15 : svRange 400 16 2 20 14 13183 127 = true := by decide +kernel
theorem sieve24_6_16 : svRange 400 16 2 20 14 13310 33 = true := by decide +kernel
theorem sieve24_6_17 : svRange 400 16 2 20 14 13343 72 = true := by decide +kernel
theorem sieve24_6_18 : svRange 400 16 2 20 14 13415 34 = true := by decide +kernel
theorem sieve24_6_19 : svRange 400 16 2 20 14 13449 54 = true := by decide +kernel
theorem sieve24_6_20 : svRange 400 16 2 20 14 13503 40 = true := by decide +kernel
theorem sieve24_6_21 : svRange 400 16 2 20 14 13543 8 = true := by decide +kernel
theorem sieve24_6_22 : svRange 400 16 2 20 14 13551 44 = true := by decide +kernel
theorem sieve24_6_23 : svRange 400 16 2 20 14 13595 132 = true := by decide +kernel
theorem sieve24_6_24 : svRange 400 16 2 20 14 13727 32 = true := by decide +kernel
theorem sieve24_6_25 : svRange 400 16 2 20 14 13759 31 = true := by decide +kernel
theorem sieve24_6_26 : svRange 400 16 2 20 14 13790 65 = true := by decide +kernel
theorem sieve24_6_27 : svRange 400 16 2 20 14 13855 96 = true := by decide +kernel
theorem sieve24_6_28 : svRange 400 16 2 20 14 13951 64 = true := by decide +kernel
theorem sieve24_6_29 : svRange 400 16 2 20 14 14015 64 = true := by decide +kernel
theorem sieve24_6_30 : svRange 400 16 2 20 14 14079 28 = true := by decide +kernel
theorem sieve24_6_31 : svRange 400 16 2 20 14 14107 140 = true := by decide +kernel
theorem sieve24_6_32 : svRange 400 16 2 20 14 14247 66 = true := by decide +kernel
theorem sieve24_6_33 : svRange 400 16 2 20 14 14313 22 = true := by decide +kernel
theorem sieve24_6_34 : svRange 400 16 2 20 14 14335 92 = true := by decide +kernel
theorem sieve24_6_35 : svRange 400 16 2 20 14 14427 68 = true := by decide +kernel

theorem sieve24_part6 : RootsOK 400 16 2 20 14 12379 14495 :=
  rootsOK_cons sieve24_6_0 <|
  rootsOK_cons sieve24_6_1 <|
  rootsOK_cons sieve24_6_2 <|
  rootsOK_cons sieve24_6_3 <|
  rootsOK_cons sieve24_6_4 <|
  rootsOK_cons sieve24_6_5 <|
  rootsOK_cons sieve24_6_6 <|
  rootsOK_cons sieve24_6_7 <|
  rootsOK_cons sieve24_6_8 <|
  rootsOK_cons sieve24_6_9 <|
  rootsOK_cons sieve24_6_10 <|
  rootsOK_cons sieve24_6_11 <|
  rootsOK_cons sieve24_6_12 <|
  rootsOK_cons sieve24_6_13 <|
  rootsOK_cons sieve24_6_14 <|
  rootsOK_cons sieve24_6_15 <|
  rootsOK_cons sieve24_6_16 <|
  rootsOK_cons sieve24_6_17 <|
  rootsOK_cons sieve24_6_18 <|
  rootsOK_cons sieve24_6_19 <|
  rootsOK_cons sieve24_6_20 <|
  rootsOK_cons sieve24_6_21 <|
  rootsOK_cons sieve24_6_22 <|
  rootsOK_cons sieve24_6_23 <|
  rootsOK_cons sieve24_6_24 <|
  rootsOK_cons sieve24_6_25 <|
  rootsOK_cons sieve24_6_26 <|
  rootsOK_cons sieve24_6_27 <|
  rootsOK_cons sieve24_6_28 <|
  rootsOK_cons sieve24_6_29 <|
  rootsOK_cons sieve24_6_30 <|
  rootsOK_cons sieve24_6_31 <|
  rootsOK_cons sieve24_6_32 <|
  rootsOK_cons sieve24_6_33 <|
  rootsOK_cons sieve24_6_34 <|
  rootsOK_cons sieve24_6_35 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve24_6_0
#print axioms Collatz.sieve24_part6
