import Sieve

/-! Kernel certificate part 40 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [10400, 10652), 15 blocks, estimated cost 2199182 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace Collatz

theorem sieve29_40_0 : svRange 400 280 33554432 20 14 10400 9 = true := by decide +kernel
theorem sieve29_40_1 : svRange 400 280 33554432 20 14 10409 1 = true := by decide +kernel
theorem sieve29_40_2 : svRange 400 280 33554432 20 14 10410 55 = true := by decide +kernel
theorem sieve29_40_3 : svRange 400 280 33554432 20 14 10465 1 = true := by decide +kernel
theorem sieve29_40_4 : svRange 400 280 33554432 20 14 10466 13 = true := by decide +kernel
theorem sieve29_40_5 : svRange 400 280 33554432 20 14 10479 1 = true := by decide +kernel
theorem sieve29_40_6 : svRange 400 280 33554432 20 14 10480 14 = true := by decide +kernel
theorem sieve29_40_7 : svRange 400 280 33554432 20 14 10494 1 = true := by decide +kernel
theorem sieve29_40_8 : svRange 400 280 33554432 20 14 10495 63 = true := by decide +kernel
theorem sieve29_40_9 : svRange 400 280 33554432 20 14 10558 1 = true := by decide +kernel
theorem sieve29_40_10 : svRange 400 280 33554432 20 14 10559 8 = true := by decide +kernel
theorem sieve29_40_11 : svRange 400 280 33554432 20 14 10567 32 = true := by decide +kernel
theorem sieve29_40_12 : svRange 400 280 33554432 20 14 10599 1 = true := by decide +kernel
theorem sieve29_40_13 : svRange 400 280 33554432 20 14 10600 51 = true := by decide +kernel
theorem sieve29_40_14 : svRange 400 280 33554432 20 14 10651 1 = true := by decide +kernel

theorem sieve29_part40 : RootsOK 400 280 33554432 20 14 10400 10652 :=
  rootsOK_cons sieve29_40_0 <|
  rootsOK_cons sieve29_40_1 <|
  rootsOK_cons sieve29_40_2 <|
  rootsOK_cons sieve29_40_3 <|
  rootsOK_cons sieve29_40_4 <|
  rootsOK_cons sieve29_40_5 <|
  rootsOK_cons sieve29_40_6 <|
  rootsOK_cons sieve29_40_7 <|
  rootsOK_cons sieve29_40_8 <|
  rootsOK_cons sieve29_40_9 <|
  rootsOK_cons sieve29_40_10 <|
  rootsOK_cons sieve29_40_11 <|
  rootsOK_cons sieve29_40_12 <|
  rootsOK_cons sieve29_40_13 <|
  rootsOK_cons sieve29_40_14 <|
  rootsOK_nil _ _ _ _ _ _

end Collatz

#print axioms Collatz.sieve29_40_0
#print axioms Collatz.sieve29_part40
