import CollatzSearch.Sieve

/-! Kernel certificate part 47 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [12060, 12330), 11 blocks, estimated cost 2337395 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_47_0 : svRange 400 280 33554432 20 14 12060 75 = true := by decide +kernel
theorem sieve29_47_1 : svRange 400 280 33554432 20 14 12135 1 = true := by decide +kernel
theorem sieve29_47_2 : svRange 400 280 33554432 20 14 12136 63 = true := by decide +kernel
theorem sieve29_47_3 : svRange 400 280 33554432 20 14 12199 2 = true := by decide +kernel
theorem sieve29_47_4 : svRange 400 280 33554432 20 14 12201 1 = true := by decide +kernel
theorem sieve29_47_5 : svRange 400 280 33554432 20 14 12202 55 = true := by decide +kernel
theorem sieve29_47_6 : svRange 400 280 33554432 20 14 12257 29 = true := by decide +kernel
theorem sieve29_47_7 : svRange 400 280 33554432 20 14 12286 1 = true := by decide +kernel
theorem sieve29_47_8 : svRange 400 280 33554432 20 14 12287 1 = true := by decide +kernel
theorem sieve29_47_9 : svRange 400 280 33554432 20 14 12288 41 = true := by decide +kernel
theorem sieve29_47_10 : svRange 400 280 33554432 20 14 12329 1 = true := by decide +kernel

theorem sieve29_part47 : RootsOK 400 280 33554432 20 14 12060 12330 :=
  rootsOK_cons sieve29_47_0 <|
  rootsOK_cons sieve29_47_1 <|
  rootsOK_cons sieve29_47_2 <|
  rootsOK_cons sieve29_47_3 <|
  rootsOK_cons sieve29_47_4 <|
  rootsOK_cons sieve29_47_5 <|
  rootsOK_cons sieve29_47_6 <|
  rootsOK_cons sieve29_47_7 <|
  rootsOK_cons sieve29_47_8 <|
  rootsOK_cons sieve29_47_9 <|
  rootsOK_cons sieve29_47_10 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_47_0
#print axioms CollatzSearch.sieve29_part47
