import CollatzSearch.Sieve

/-! Kernel certificate part 57 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [14655, 14848), 14 blocks, estimated cost 2212250 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_57_0 : svRange 400 280 33554432 20 14 14655 8 = true := by decide +kernel
theorem sieve29_57_1 : svRange 400 280 33554432 20 14 14663 1 = true := by decide +kernel
theorem sieve29_57_2 : svRange 400 280 33554432 20 14 14664 54 = true := by decide +kernel
theorem sieve29_57_3 : svRange 400 280 33554432 20 14 14718 1 = true := by decide +kernel
theorem sieve29_57_4 : svRange 400 280 33554432 20 14 14719 28 = true := by decide +kernel
theorem sieve29_57_5 : svRange 400 280 33554432 20 14 14747 14 = true := by decide +kernel
theorem sieve29_57_6 : svRange 400 280 33554432 20 14 14761 22 = true := by decide +kernel
theorem sieve29_57_7 : svRange 400 280 33554432 20 14 14783 1 = true := by decide +kernel
theorem sieve29_57_8 : svRange 400 280 33554432 20 14 14784 31 = true := by decide +kernel
theorem sieve29_57_9 : svRange 400 280 33554432 20 14 14815 16 = true := by decide +kernel
theorem sieve29_57_10 : svRange 400 280 33554432 20 14 14831 1 = true := by decide +kernel
theorem sieve29_57_11 : svRange 400 280 33554432 20 14 14832 14 = true := by decide +kernel
theorem sieve29_57_12 : svRange 400 280 33554432 20 14 14846 1 = true := by decide +kernel
theorem sieve29_57_13 : svRange 400 280 33554432 20 14 14847 1 = true := by decide +kernel

theorem sieve29_part57 : RootsOK 400 280 33554432 20 14 14655 14848 :=
  rootsOK_cons sieve29_57_0 <|
  rootsOK_cons sieve29_57_1 <|
  rootsOK_cons sieve29_57_2 <|
  rootsOK_cons sieve29_57_3 <|
  rootsOK_cons sieve29_57_4 <|
  rootsOK_cons sieve29_57_5 <|
  rootsOK_cons sieve29_57_6 <|
  rootsOK_cons sieve29_57_7 <|
  rootsOK_cons sieve29_57_8 <|
  rootsOK_cons sieve29_57_9 <|
  rootsOK_cons sieve29_57_10 <|
  rootsOK_cons sieve29_57_11 <|
  rootsOK_cons sieve29_57_12 <|
  rootsOK_cons sieve29_57_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_57_0
#print axioms CollatzSearch.sieve29_part57
