import CollatzSearch.Sieve

/-! Kernel certificate part 2 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [4137, 6313), 37 blocks, estimated cost 1289478 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace CollatzSearch

theorem sieve25_2_0 : svRange 400 32 16777216 20 14 4137 96 = true := by decide +kernel
theorem sieve25_2_1 : svRange 400 32 16777216 20 14 4233 30 = true := by decide +kernel
theorem sieve25_2_2 : svRange 400 32 16777216 20 14 4263 55 = true := by decide +kernel
theorem sieve25_2_3 : svRange 400 32 16777216 20 14 4318 32 = true := by decide +kernel
theorem sieve25_2_4 : svRange 400 32 16777216 20 14 4350 64 = true := by decide +kernel
theorem sieve25_2_5 : svRange 400 32 16777216 20 14 4414 97 = true := by decide +kernel
theorem sieve25_2_6 : svRange 400 32 16777216 20 14 4511 64 = true := by decide +kernel
theorem sieve25_2_7 : svRange 400 32 16777216 20 14 4575 16 = true := by decide +kernel
theorem sieve25_2_8 : svRange 400 32 16777216 20 14 4591 16 = true := by decide +kernel
theorem sieve25_2_9 : svRange 400 32 16777216 20 14 4607 92 = true := by decide +kernel
theorem sieve25_2_10 : svRange 400 32 16777216 20 14 4699 64 = true := by decide +kernel
theorem sieve25_2_11 : svRange 400 32 16777216 20 14 4763 14 = true := by decide +kernel
theorem sieve25_2_12 : svRange 400 32 16777216 20 14 4777 64 = true := by decide +kernel
theorem sieve25_2_13 : svRange 400 32 16777216 20 14 4841 50 = true := by decide +kernel
theorem sieve25_2_14 : svRange 400 32 16777216 20 14 4891 99 = true := by decide +kernel
theorem sieve25_2_15 : svRange 400 32 16777216 20 14 4990 97 = true := by decide +kernel
theorem sieve25_2_16 : svRange 400 32 16777216 20 14 5087 32 = true := by decide +kernel
theorem sieve25_2_17 : svRange 400 32 16777216 20 14 5119 32 = true := by decide +kernel
theorem sieve25_2_18 : svRange 400 32 16777216 20 14 5151 96 = true := by decide +kernel
theorem sieve25_2_19 : svRange 400 32 16777216 20 14 5247 32 = true := by decide +kernel
theorem sieve25_2_20 : svRange 400 32 16777216 20 14 5279 80 = true := by decide +kernel
theorem sieve25_2_21 : svRange 400 32 16777216 20 14 5359 44 = true := by decide +kernel
theorem sieve25_2_22 : svRange 400 32 16777216 20 14 5403 99 = true := by decide +kernel
theorem sieve25_2_23 : svRange 400 32 16777216 20 14 5502 43 = true := by decide +kernel
theorem sieve25_2_24 : svRange 400 32 16777216 20 14 5545 64 = true := by decide +kernel
theorem sieve25_2_25 : svRange 400 32 16777216 20 14 5609 64 = true := by decide +kernel
theorem sieve25_2_26 : svRange 400 32 16777216 20 14 5673 85 = true := by decide +kernel
theorem sieve25_2_27 : svRange 400 32 16777216 20 14 5758 43 = true := by decide +kernel
theorem sieve25_2_28 : svRange 400 32 16777216 20 14 5801 86 = true := by decide +kernel
theorem sieve25_2_29 : svRange 400 32 16777216 20 14 5887 28 = true := by decide +kernel
theorem sieve25_2_30 : svRange 400 32 16777216 20 14 5915 84 = true := by decide +kernel
theorem sieve25_2_31 : svRange 400 32 16777216 20 14 5999 58 = true := by decide +kernel
theorem sieve25_2_32 : svRange 400 32 16777216 20 14 6057 64 = true := by decide +kernel
theorem sieve25_2_33 : svRange 400 32 16777216 20 14 6121 22 = true := by decide +kernel
theorem sieve25_2_34 : svRange 400 32 16777216 20 14 6143 63 = true := by decide +kernel
theorem sieve25_2_35 : svRange 400 32 16777216 20 14 6206 65 = true := by decide +kernel
theorem sieve25_2_36 : svRange 400 32 16777216 20 14 6271 42 = true := by decide +kernel

theorem sieve25_part2 : RootsOK 400 32 16777216 20 14 4137 6313 :=
  rootsOK_cons sieve25_2_0 <|
  rootsOK_cons sieve25_2_1 <|
  rootsOK_cons sieve25_2_2 <|
  rootsOK_cons sieve25_2_3 <|
  rootsOK_cons sieve25_2_4 <|
  rootsOK_cons sieve25_2_5 <|
  rootsOK_cons sieve25_2_6 <|
  rootsOK_cons sieve25_2_7 <|
  rootsOK_cons sieve25_2_8 <|
  rootsOK_cons sieve25_2_9 <|
  rootsOK_cons sieve25_2_10 <|
  rootsOK_cons sieve25_2_11 <|
  rootsOK_cons sieve25_2_12 <|
  rootsOK_cons sieve25_2_13 <|
  rootsOK_cons sieve25_2_14 <|
  rootsOK_cons sieve25_2_15 <|
  rootsOK_cons sieve25_2_16 <|
  rootsOK_cons sieve25_2_17 <|
  rootsOK_cons sieve25_2_18 <|
  rootsOK_cons sieve25_2_19 <|
  rootsOK_cons sieve25_2_20 <|
  rootsOK_cons sieve25_2_21 <|
  rootsOK_cons sieve25_2_22 <|
  rootsOK_cons sieve25_2_23 <|
  rootsOK_cons sieve25_2_24 <|
  rootsOK_cons sieve25_2_25 <|
  rootsOK_cons sieve25_2_26 <|
  rootsOK_cons sieve25_2_27 <|
  rootsOK_cons sieve25_2_28 <|
  rootsOK_cons sieve25_2_29 <|
  rootsOK_cons sieve25_2_30 <|
  rootsOK_cons sieve25_2_31 <|
  rootsOK_cons sieve25_2_32 <|
  rootsOK_cons sieve25_2_33 <|
  rootsOK_cons sieve25_2_34 <|
  rootsOK_cons sieve25_2_35 <|
  rootsOK_cons sieve25_2_36 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve25_2_0
#print axioms CollatzSearch.sieve25_part2
