import CollatzSearch.Sieve

/-! Kernel certificate part 42 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [10919, 11071), 15 blocks, estimated cost 2339327 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_42_0 : svRange 400 280 33554432 20 14 10919 2 = true := by decide +kernel
theorem sieve29_42_1 : svRange 400 280 33554432 20 14 10921 1 = true := by decide +kernel
theorem sieve29_42_2 : svRange 400 280 33554432 20 14 10922 21 = true := by decide +kernel
theorem sieve29_42_3 : svRange 400 280 33554432 20 14 10943 1 = true := by decide +kernel
theorem sieve29_42_4 : svRange 400 280 33554432 20 14 10944 33 = true := by decide +kernel
theorem sieve29_42_5 : svRange 400 280 33554432 20 14 10977 6 = true := by decide +kernel
theorem sieve29_42_6 : svRange 400 280 33554432 20 14 10983 1 = true := by decide +kernel
theorem sieve29_42_7 : svRange 400 280 33554432 20 14 10984 7 = true := by decide +kernel
theorem sieve29_42_8 : svRange 400 280 33554432 20 14 10991 12 = true := by decide +kernel
theorem sieve29_42_9 : svRange 400 280 33554432 20 14 11003 1 = true := by decide +kernel
theorem sieve29_42_10 : svRange 400 280 33554432 20 14 11004 13 = true := by decide +kernel
theorem sieve29_42_11 : svRange 400 280 33554432 20 14 11017 18 = true := by decide +kernel
theorem sieve29_42_12 : svRange 400 280 33554432 20 14 11035 4 = true := by decide +kernel
theorem sieve29_42_13 : svRange 400 280 33554432 20 14 11039 31 = true := by decide +kernel
theorem sieve29_42_14 : svRange 400 280 33554432 20 14 11070 1 = true := by decide +kernel

theorem sieve29_part42 : RootsOK 400 280 33554432 20 14 10919 11071 :=
  rootsOK_cons sieve29_42_0 <|
  rootsOK_cons sieve29_42_1 <|
  rootsOK_cons sieve29_42_2 <|
  rootsOK_cons sieve29_42_3 <|
  rootsOK_cons sieve29_42_4 <|
  rootsOK_cons sieve29_42_5 <|
  rootsOK_cons sieve29_42_6 <|
  rootsOK_cons sieve29_42_7 <|
  rootsOK_cons sieve29_42_8 <|
  rootsOK_cons sieve29_42_9 <|
  rootsOK_cons sieve29_42_10 <|
  rootsOK_cons sieve29_42_11 <|
  rootsOK_cons sieve29_42_12 <|
  rootsOK_cons sieve29_42_13 <|
  rootsOK_cons sieve29_42_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_42_0
#print axioms CollatzSearch.sieve29_part42
