import CollatzSearch.Sieve

/-! Kernel certificate part 1 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [2047, 4137), 39 blocks, estimated cost 1252302 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace CollatzSearch

theorem sieve25_1_0 : svRange 400 32 16777216 20 14 2047 64 = true := by decide +kernel
theorem sieve25_1_1 : svRange 400 32 16777216 20 14 2111 48 = true := by decide +kernel
theorem sieve25_1_2 : svRange 400 32 16777216 20 14 2159 48 = true := by decide +kernel
theorem sieve25_1_3 : svRange 400 32 16777216 20 14 2207 10 = true := by decide +kernel
theorem sieve25_1_4 : svRange 400 32 16777216 20 14 2217 70 = true := by decide +kernel
theorem sieve25_1_5 : svRange 400 32 16777216 20 14 2287 88 = true := by decide +kernel
theorem sieve25_1_6 : svRange 400 32 16777216 20 14 2375 120 = true := by decide +kernel
theorem sieve25_1_7 : svRange 400 32 16777216 20 14 2495 32 = true := by decide +kernel
theorem sieve25_1_8 : svRange 400 32 16777216 20 14 2527 31 = true := by decide +kernel
theorem sieve25_1_9 : svRange 400 32 16777216 20 14 2558 113 = true := by decide +kernel
theorem sieve25_1_10 : svRange 400 32 16777216 20 14 2671 58 = true := by decide +kernel
theorem sieve25_1_11 : svRange 400 32 16777216 20 14 2729 62 = true := by decide +kernel
theorem sieve25_1_12 : svRange 400 32 16777216 20 14 2791 52 = true := by decide +kernel
theorem sieve25_1_13 : svRange 400 32 16777216 20 14 2843 44 = true := by decide +kernel
theorem sieve25_1_14 : svRange 400 32 16777216 20 14 2887 55 = true := by decide +kernel
theorem sieve25_1_15 : svRange 400 32 16777216 20 14 2942 1 = true := by decide +kernel
theorem sieve25_1_16 : svRange 400 32 16777216 20 14 2943 64 = true := by decide +kernel
theorem sieve25_1_17 : svRange 400 32 16777216 20 14 3007 48 = true := by decide +kernel
theorem sieve25_1_18 : svRange 400 32 16777216 20 14 3055 44 = true := by decide +kernel
theorem sieve25_1_19 : svRange 400 32 16777216 20 14 3099 76 = true := by decide +kernel
theorem sieve25_1_20 : svRange 400 32 16777216 20 14 3175 24 = true := by decide +kernel
theorem sieve25_1_21 : svRange 400 32 16777216 20 14 3199 32 = true := by decide +kernel
theorem sieve25_1_22 : svRange 400 32 16777216 20 14 3231 66 = true := by decide +kernel
theorem sieve25_1_23 : svRange 400 32 16777216 20 14 3297 29 = true := by decide +kernel
theorem sieve25_1_24 : svRange 400 32 16777216 20 14 3326 43 = true := by decide +kernel
theorem sieve25_1_25 : svRange 400 32 16777216 20 14 3369 30 = true := by decide +kernel
theorem sieve25_1_26 : svRange 400 32 16777216 20 14 3399 120 = true := by decide +kernel
theorem sieve25_1_27 : svRange 400 32 16777216 20 14 3519 48 = true := by decide +kernel
theorem sieve25_1_28 : svRange 400 32 16777216 20 14 3567 48 = true := by decide +kernel
theorem sieve25_1_29 : svRange 400 32 16777216 20 14 3615 96 = true := by decide +kernel
theorem sieve25_1_30 : svRange 400 32 16777216 20 14 3711 28 = true := by decide +kernel
theorem sieve25_1_31 : svRange 400 32 16777216 20 14 3739 52 = true := by decide +kernel
theorem sieve25_1_32 : svRange 400 32 16777216 20 14 3791 48 = true := by decide +kernel
theorem sieve25_1_33 : svRange 400 32 16777216 20 14 3839 92 = true := by decide +kernel
theorem sieve25_1_34 : svRange 400 32 16777216 20 14 3931 20 = true := by decide +kernel
theorem sieve25_1_35 : svRange 400 32 16777216 20 14 3951 114 = true := by decide +kernel
theorem sieve25_1_36 : svRange 400 32 16777216 20 14 4065 29 = true := by decide +kernel
theorem sieve25_1_37 : svRange 400 32 16777216 20 14 4094 1 = true := by decide +kernel
theorem sieve25_1_38 : svRange 400 32 16777216 20 14 4095 42 = true := by decide +kernel

theorem sieve25_part1 : RootsOK 400 32 16777216 20 14 2047 4137 :=
  rootsOK_cons sieve25_1_0 <|
  rootsOK_cons sieve25_1_1 <|
  rootsOK_cons sieve25_1_2 <|
  rootsOK_cons sieve25_1_3 <|
  rootsOK_cons sieve25_1_4 <|
  rootsOK_cons sieve25_1_5 <|
  rootsOK_cons sieve25_1_6 <|
  rootsOK_cons sieve25_1_7 <|
  rootsOK_cons sieve25_1_8 <|
  rootsOK_cons sieve25_1_9 <|
  rootsOK_cons sieve25_1_10 <|
  rootsOK_cons sieve25_1_11 <|
  rootsOK_cons sieve25_1_12 <|
  rootsOK_cons sieve25_1_13 <|
  rootsOK_cons sieve25_1_14 <|
  rootsOK_cons sieve25_1_15 <|
  rootsOK_cons sieve25_1_16 <|
  rootsOK_cons sieve25_1_17 <|
  rootsOK_cons sieve25_1_18 <|
  rootsOK_cons sieve25_1_19 <|
  rootsOK_cons sieve25_1_20 <|
  rootsOK_cons sieve25_1_21 <|
  rootsOK_cons sieve25_1_22 <|
  rootsOK_cons sieve25_1_23 <|
  rootsOK_cons sieve25_1_24 <|
  rootsOK_cons sieve25_1_25 <|
  rootsOK_cons sieve25_1_26 <|
  rootsOK_cons sieve25_1_27 <|
  rootsOK_cons sieve25_1_28 <|
  rootsOK_cons sieve25_1_29 <|
  rootsOK_cons sieve25_1_30 <|
  rootsOK_cons sieve25_1_31 <|
  rootsOK_cons sieve25_1_32 <|
  rootsOK_cons sieve25_1_33 <|
  rootsOK_cons sieve25_1_34 <|
  rootsOK_cons sieve25_1_35 <|
  rootsOK_cons sieve25_1_36 <|
  rootsOK_cons sieve25_1_37 <|
  rootsOK_cons sieve25_1_38 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve25_1_0
#print axioms CollatzSearch.sieve25_part1
