import CollatzSearch.Sieve

/-! Kernel certificate part 32 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [8351, 8607), 15 blocks, estimated cost 2254511 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_32_0 : svRange 400 280 33554432 20 14 8351 1 = true := by decide +kernel
theorem sieve29_32_1 : svRange 400 280 33554432 20 14 8352 7 = true := by decide +kernel
theorem sieve29_32_2 : svRange 400 280 33554432 20 14 8359 1 = true := by decide +kernel
theorem sieve29_32_3 : svRange 400 280 33554432 20 14 8360 54 = true := by decide +kernel
theorem sieve29_32_4 : svRange 400 280 33554432 20 14 8414 1 = true := by decide +kernel
theorem sieve29_32_5 : svRange 400 280 33554432 20 14 8415 2 = true := by decide +kernel
theorem sieve29_32_6 : svRange 400 280 33554432 20 14 8417 1 = true := by decide +kernel
theorem sieve29_32_7 : svRange 400 280 33554432 20 14 8418 25 = true := by decide +kernel
theorem sieve29_32_8 : svRange 400 280 33554432 20 14 8443 1 = true := by decide +kernel
theorem sieve29_32_9 : svRange 400 280 33554432 20 14 8444 66 = true := by decide +kernel
theorem sieve29_32_10 : svRange 400 280 33554432 20 14 8510 1 = true := by decide +kernel
theorem sieve29_32_11 : svRange 400 280 33554432 20 14 8511 1 = true := by decide +kernel
theorem sieve29_32_12 : svRange 400 280 33554432 20 14 8512 39 = true := by decide +kernel
theorem sieve29_32_13 : svRange 400 280 33554432 20 14 8551 52 = true := by decide +kernel
theorem sieve29_32_14 : svRange 400 280 33554432 20 14 8603 4 = true := by decide +kernel

theorem sieve29_part32 : RootsOK 400 280 33554432 20 14 8351 8607 :=
  rootsOK_cons sieve29_32_0 <|
  rootsOK_cons sieve29_32_1 <|
  rootsOK_cons sieve29_32_2 <|
  rootsOK_cons sieve29_32_3 <|
  rootsOK_cons sieve29_32_4 <|
  rootsOK_cons sieve29_32_5 <|
  rootsOK_cons sieve29_32_6 <|
  rootsOK_cons sieve29_32_7 <|
  rootsOK_cons sieve29_32_8 <|
  rootsOK_cons sieve29_32_9 <|
  rootsOK_cons sieve29_32_10 <|
  rootsOK_cons sieve29_32_11 <|
  rootsOK_cons sieve29_32_12 <|
  rootsOK_cons sieve29_32_13 <|
  rootsOK_cons sieve29_32_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_32_0
#print axioms CollatzSearch.sieve29_part32
