import CollatzSearch.Sieve

/-! Kernel certificate part 18 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [4649, 4935), 16 blocks, estimated cost 2297647 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_18_0 : svRange 400 280 33554432 20 14 4649 50 = true := by decide +kernel
theorem sieve29_18_1 : svRange 400 280 33554432 20 14 4699 36 = true := by decide +kernel
theorem sieve29_18_2 : svRange 400 280 33554432 20 14 4735 28 = true := by decide +kernel
theorem sieve29_18_3 : svRange 400 280 33554432 20 14 4763 1 = true := by decide +kernel
theorem sieve29_18_4 : svRange 400 280 33554432 20 14 4764 11 = true := by decide +kernel
theorem sieve29_18_5 : svRange 400 280 33554432 20 14 4775 2 = true := by decide +kernel
theorem sieve29_18_6 : svRange 400 280 33554432 20 14 4777 1 = true := by decide +kernel
theorem sieve29_18_7 : svRange 400 280 33554432 20 14 4778 37 = true := by decide +kernel
theorem sieve29_18_8 : svRange 400 280 33554432 20 14 4815 18 = true := by decide +kernel
theorem sieve29_18_9 : svRange 400 280 33554432 20 14 4833 8 = true := by decide +kernel
theorem sieve29_18_10 : svRange 400 280 33554432 20 14 4841 6 = true := by decide +kernel
theorem sieve29_18_11 : svRange 400 280 33554432 20 14 4847 1 = true := by decide +kernel
theorem sieve29_18_12 : svRange 400 280 33554432 20 14 4848 15 = true := by decide +kernel
theorem sieve29_18_13 : svRange 400 280 33554432 20 14 4863 1 = true := by decide +kernel
theorem sieve29_18_14 : svRange 400 280 33554432 20 14 4864 31 = true := by decide +kernel
theorem sieve29_18_15 : svRange 400 280 33554432 20 14 4895 40 = true := by decide +kernel

theorem sieve29_part18 : RootsOK 400 280 33554432 20 14 4649 4935 :=
  rootsOK_cons sieve29_18_0 <|
  rootsOK_cons sieve29_18_1 <|
  rootsOK_cons sieve29_18_2 <|
  rootsOK_cons sieve29_18_3 <|
  rootsOK_cons sieve29_18_4 <|
  rootsOK_cons sieve29_18_5 <|
  rootsOK_cons sieve29_18_6 <|
  rootsOK_cons sieve29_18_7 <|
  rootsOK_cons sieve29_18_8 <|
  rootsOK_cons sieve29_18_9 <|
  rootsOK_cons sieve29_18_10 <|
  rootsOK_cons sieve29_18_11 <|
  rootsOK_cons sieve29_18_12 <|
  rootsOK_cons sieve29_18_13 <|
  rootsOK_cons sieve29_18_14 <|
  rootsOK_cons sieve29_18_15 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_18_0
#print axioms CollatzSearch.sieve29_part18
