import CollatzSearch.Sieve

/-! Kernel certificate part 34 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [8874, 9152), 16 blocks, estimated cost 2357539 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_34_0 : svRange 400 280 33554432 20 14 8874 21 = true := by decide +kernel
theorem sieve29_34_1 : svRange 400 280 33554432 20 14 8895 1 = true := by decide +kernel
theorem sieve29_34_2 : svRange 400 280 33554432 20 14 8896 39 = true := by decide +kernel
theorem sieve29_34_3 : svRange 400 280 33554432 20 14 8935 1 = true := by decide +kernel
theorem sieve29_34_4 : svRange 400 280 33554432 20 14 8936 7 = true := by decide +kernel
theorem sieve29_34_5 : svRange 400 280 33554432 20 14 8943 1 = true := by decide +kernel
theorem sieve29_34_6 : svRange 400 280 33554432 20 14 8944 15 = true := by decide +kernel
theorem sieve29_34_7 : svRange 400 280 33554432 20 14 8959 1 = true := by decide +kernel
theorem sieve29_34_8 : svRange 400 280 33554432 20 14 8960 62 = true := by decide +kernel
theorem sieve29_34_9 : svRange 400 280 33554432 20 14 9022 1 = true := by decide +kernel
theorem sieve29_34_10 : svRange 400 280 33554432 20 14 9023 8 = true := by decide +kernel
theorem sieve29_34_11 : svRange 400 280 33554432 20 14 9031 32 = true := by decide +kernel
theorem sieve29_34_12 : svRange 400 280 33554432 20 14 9063 1 = true := by decide +kernel
theorem sieve29_34_13 : svRange 400 280 33554432 20 14 9064 65 = true := by decide +kernel
theorem sieve29_34_14 : svRange 400 280 33554432 20 14 9129 22 = true := by decide +kernel
theorem sieve29_34_15 : svRange 400 280 33554432 20 14 9151 1 = true := by decide +kernel

theorem sieve29_part34 : RootsOK 400 280 33554432 20 14 8874 9152 :=
  rootsOK_cons sieve29_34_0 <|
  rootsOK_cons sieve29_34_1 <|
  rootsOK_cons sieve29_34_2 <|
  rootsOK_cons sieve29_34_3 <|
  rootsOK_cons sieve29_34_4 <|
  rootsOK_cons sieve29_34_5 <|
  rootsOK_cons sieve29_34_6 <|
  rootsOK_cons sieve29_34_7 <|
  rootsOK_cons sieve29_34_8 <|
  rootsOK_cons sieve29_34_9 <|
  rootsOK_cons sieve29_34_10 <|
  rootsOK_cons sieve29_34_11 <|
  rootsOK_cons sieve29_34_12 <|
  rootsOK_cons sieve29_34_13 <|
  rootsOK_cons sieve29_34_14 <|
  rootsOK_cons sieve29_34_15 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_34_0
#print axioms CollatzSearch.sieve29_part34
