import CollatzSearch.Sieve

/-! Kernel certificate part 8 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [2044, 2216), 13 blocks, estimated cost 2160627 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_8_0 : svRange 400 280 33554432 20 14 2044 3 = true := by decide +kernel
theorem sieve29_8_1 : svRange 400 280 33554432 20 14 2047 1 = true := by decide +kernel
theorem sieve29_8_2 : svRange 400 280 33554432 20 14 2048 62 = true := by decide +kernel
theorem sieve29_8_3 : svRange 400 280 33554432 20 14 2110 1 = true := by decide +kernel
theorem sieve29_8_4 : svRange 400 280 33554432 20 14 2111 1 = true := by decide +kernel
theorem sieve29_8_5 : svRange 400 280 33554432 20 14 2112 39 = true := by decide +kernel
theorem sieve29_8_6 : svRange 400 280 33554432 20 14 2151 1 = true := by decide +kernel
theorem sieve29_8_7 : svRange 400 280 33554432 20 14 2152 23 = true := by decide +kernel
theorem sieve29_8_8 : svRange 400 280 33554432 20 14 2175 10 = true := by decide +kernel
theorem sieve29_8_9 : svRange 400 280 33554432 20 14 2185 22 = true := by decide +kernel
theorem sieve29_8_10 : svRange 400 280 33554432 20 14 2207 1 = true := by decide +kernel
theorem sieve29_8_11 : svRange 400 280 33554432 20 14 2208 7 = true := by decide +kernel
theorem sieve29_8_12 : svRange 400 280 33554432 20 14 2215 1 = true := by decide +kernel

theorem sieve29_part8 : RootsOK 400 280 33554432 20 14 2044 2216 :=
  rootsOK_cons sieve29_8_0 <|
  rootsOK_cons sieve29_8_1 <|
  rootsOK_cons sieve29_8_2 <|
  rootsOK_cons sieve29_8_3 <|
  rootsOK_cons sieve29_8_4 <|
  rootsOK_cons sieve29_8_5 <|
  rootsOK_cons sieve29_8_6 <|
  rootsOK_cons sieve29_8_7 <|
  rootsOK_cons sieve29_8_8 <|
  rootsOK_cons sieve29_8_9 <|
  rootsOK_cons sieve29_8_10 <|
  rootsOK_cons sieve29_8_11 <|
  rootsOK_cons sieve29_8_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_8_0
#print axioms CollatzSearch.sieve29_part8
