import CollatzSearch.Sieve

/-! Kernel certificate part 44 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [11296, 11548), 15 blocks, estimated cost 2426721 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_44_0 : svRange 400 280 33554432 20 14 11296 71 = true := by decide +kernel
theorem sieve29_44_1 : svRange 400 280 33554432 20 14 11367 1 = true := by decide +kernel
theorem sieve29_44_2 : svRange 400 280 33554432 20 14 11368 23 = true := by decide +kernel
theorem sieve29_44_3 : svRange 400 280 33554432 20 14 11391 1 = true := by decide +kernel
theorem sieve29_44_4 : svRange 400 280 33554432 20 14 11392 31 = true := by decide +kernel
theorem sieve29_44_5 : svRange 400 280 33554432 20 14 11423 1 = true := by decide +kernel
theorem sieve29_44_6 : svRange 400 280 33554432 20 14 11424 65 = true := by decide +kernel
theorem sieve29_44_7 : svRange 400 280 33554432 20 14 11489 6 = true := by decide +kernel
theorem sieve29_44_8 : svRange 400 280 33554432 20 14 11495 8 = true := by decide +kernel
theorem sieve29_44_9 : svRange 400 280 33554432 20 14 11503 1 = true := by decide +kernel
theorem sieve29_44_10 : svRange 400 280 33554432 20 14 11504 11 = true := by decide +kernel
theorem sieve29_44_11 : svRange 400 280 33554432 20 14 11515 1 = true := by decide +kernel
theorem sieve29_44_12 : svRange 400 280 33554432 20 14 11516 3 = true := by decide +kernel
theorem sieve29_44_13 : svRange 400 280 33554432 20 14 11519 28 = true := by decide +kernel
theorem sieve29_44_14 : svRange 400 280 33554432 20 14 11547 1 = true := by decide +kernel

theorem sieve29_part44 : RootsOK 400 280 33554432 20 14 11296 11548 :=
  rootsOK_cons sieve29_44_0 <|
  rootsOK_cons sieve29_44_1 <|
  rootsOK_cons sieve29_44_2 <|
  rootsOK_cons sieve29_44_3 <|
  rootsOK_cons sieve29_44_4 <|
  rootsOK_cons sieve29_44_5 <|
  rootsOK_cons sieve29_44_6 <|
  rootsOK_cons sieve29_44_7 <|
  rootsOK_cons sieve29_44_8 <|
  rootsOK_cons sieve29_44_9 <|
  rootsOK_cons sieve29_44_10 <|
  rootsOK_cons sieve29_44_11 <|
  rootsOK_cons sieve29_44_12 <|
  rootsOK_cons sieve29_44_13 <|
  rootsOK_cons sieve29_44_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_44_0
#print axioms CollatzSearch.sieve29_part44
