import CollatzSearch.Sieve

/-! Kernel certificate part 13 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [3327, 3631), 15 blocks, estimated cost 2266226 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_13_0 : svRange 400 280 33554432 20 14 3327 1 = true := by decide +kernel
theorem sieve29_13_1 : svRange 400 280 33554432 20 14 3328 41 = true := by decide +kernel
theorem sieve29_13_2 : svRange 400 280 33554432 20 14 3369 1 = true := by decide +kernel
theorem sieve29_13_3 : svRange 400 280 33554432 20 14 3370 20 = true := by decide +kernel
theorem sieve29_13_4 : svRange 400 280 33554432 20 14 3390 1 = true := by decide +kernel
theorem sieve29_13_5 : svRange 400 280 33554432 20 14 3391 8 = true := by decide +kernel
theorem sieve29_13_6 : svRange 400 280 33554432 20 14 3399 32 = true := by decide +kernel
theorem sieve29_13_7 : svRange 400 280 33554432 20 14 3431 1 = true := by decide +kernel
theorem sieve29_13_8 : svRange 400 280 33554432 20 14 3432 87 = true := by decide +kernel
theorem sieve29_13_9 : svRange 400 280 33554432 20 14 3519 1 = true := by decide +kernel
theorem sieve29_13_10 : svRange 400 280 33554432 20 14 3520 47 = true := by decide +kernel
theorem sieve29_13_11 : svRange 400 280 33554432 20 14 3567 1 = true := by decide +kernel
theorem sieve29_13_12 : svRange 400 280 33554432 20 14 3568 15 = true := by decide +kernel
theorem sieve29_13_13 : svRange 400 280 33554432 20 14 3583 32 = true := by decide +kernel
theorem sieve29_13_14 : svRange 400 280 33554432 20 14 3615 16 = true := by decide +kernel

theorem sieve29_part13 : RootsOK 400 280 33554432 20 14 3327 3631 :=
  rootsOK_cons sieve29_13_0 <|
  rootsOK_cons sieve29_13_1 <|
  rootsOK_cons sieve29_13_2 <|
  rootsOK_cons sieve29_13_3 <|
  rootsOK_cons sieve29_13_4 <|
  rootsOK_cons sieve29_13_5 <|
  rootsOK_cons sieve29_13_6 <|
  rootsOK_cons sieve29_13_7 <|
  rootsOK_cons sieve29_13_8 <|
  rootsOK_cons sieve29_13_9 <|
  rootsOK_cons sieve29_13_10 <|
  rootsOK_cons sieve29_13_11 <|
  rootsOK_cons sieve29_13_12 <|
  rootsOK_cons sieve29_13_13 <|
  rootsOK_cons sieve29_13_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_13_0
#print axioms CollatzSearch.sieve29_part13
