import CollatzSearch.Sieve

/-! Kernel certificate part 21 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [5480, 5760), 14 blocks, estimated cost 2256333 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_21_0 : svRange 400 280 33554432 20 14 5480 23 = true := by decide +kernel
theorem sieve29_21_1 : svRange 400 280 33554432 20 14 5503 32 = true := by decide +kernel
theorem sieve29_21_2 : svRange 400 280 33554432 20 14 5535 1 = true := by decide +kernel
theorem sieve29_21_3 : svRange 400 280 33554432 20 14 5536 31 = true := by decide +kernel
theorem sieve29_21_4 : svRange 400 280 33554432 20 14 5567 1 = true := by decide +kernel
theorem sieve29_21_5 : svRange 400 280 33554432 20 14 5568 41 = true := by decide +kernel
theorem sieve29_21_6 : svRange 400 280 33554432 20 14 5609 1 = true := by decide +kernel
theorem sieve29_21_7 : svRange 400 280 33554432 20 14 5610 63 = true := by decide +kernel
theorem sieve29_21_8 : svRange 400 280 33554432 20 14 5673 1 = true := by decide +kernel
theorem sieve29_21_9 : svRange 400 280 33554432 20 14 5674 5 = true := by decide +kernel
theorem sieve29_21_10 : svRange 400 280 33554432 20 14 5679 1 = true := by decide +kernel
theorem sieve29_21_11 : svRange 400 280 33554432 20 14 5680 78 = true := by decide +kernel
theorem sieve29_21_12 : svRange 400 280 33554432 20 14 5758 1 = true := by decide +kernel
theorem sieve29_21_13 : svRange 400 280 33554432 20 14 5759 1 = true := by decide +kernel

theorem sieve29_part21 : RootsOK 400 280 33554432 20 14 5480 5760 :=
  rootsOK_cons sieve29_21_0 <|
  rootsOK_cons sieve29_21_1 <|
  rootsOK_cons sieve29_21_2 <|
  rootsOK_cons sieve29_21_3 <|
  rootsOK_cons sieve29_21_4 <|
  rootsOK_cons sieve29_21_5 <|
  rootsOK_cons sieve29_21_6 <|
  rootsOK_cons sieve29_21_7 <|
  rootsOK_cons sieve29_21_8 <|
  rootsOK_cons sieve29_21_9 <|
  rootsOK_cons sieve29_21_10 <|
  rootsOK_cons sieve29_21_11 <|
  rootsOK_cons sieve29_21_12 <|
  rootsOK_cons sieve29_21_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_21_0
#print axioms CollatzSearch.sieve29_part21
