import CollatzSearch.Sieve

/-! Kernel certificate part 4 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [8359, 10409), 37 blocks, estimated cost 1265926 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace CollatzSearch

theorem sieve25_4_0 : svRange 400 32 16777216 20 14 8359 56 = true := by decide +kernel
theorem sieve25_4_1 : svRange 400 32 16777216 20 14 8415 60 = true := by decide +kernel
theorem sieve25_4_2 : svRange 400 32 16777216 20 14 8475 36 = true := by decide +kernel
theorem sieve25_4_3 : svRange 400 32 16777216 20 14 8511 96 = true := by decide +kernel
theorem sieve25_4_4 : svRange 400 32 16777216 20 14 8607 64 = true := by decide +kernel
theorem sieve25_4_5 : svRange 400 32 16777216 20 14 8671 32 = true := by decide +kernel
theorem sieve25_4_6 : svRange 400 32 16777216 20 14 8703 48 = true := by decide +kernel
theorem sieve25_4_7 : svRange 400 32 16777216 20 14 8751 80 = true := by decide +kernel
theorem sieve25_4_8 : svRange 400 32 16777216 20 14 8831 42 = true := by decide +kernel
theorem sieve25_4_9 : svRange 400 32 16777216 20 14 8873 56 = true := by decide +kernel
theorem sieve25_4_10 : svRange 400 32 16777216 20 14 8929 26 = true := by decide +kernel
theorem sieve25_4_11 : svRange 400 32 16777216 20 14 8955 68 = true := by decide +kernel
theorem sieve25_4_12 : svRange 400 32 16777216 20 14 9023 74 = true := by decide +kernel
theorem sieve25_4_13 : svRange 400 32 16777216 20 14 9097 85 = true := by decide +kernel
theorem sieve25_4_14 : svRange 400 32 16777216 20 14 9182 32 = true := by decide +kernel
theorem sieve25_4_15 : svRange 400 32 16777216 20 14 9214 33 = true := by decide +kernel
theorem sieve25_4_16 : svRange 400 32 16777216 20 14 9247 96 = true := by decide +kernel
theorem sieve25_4_17 : svRange 400 32 16777216 20 14 9343 112 = true := by decide +kernel
theorem sieve25_4_18 : svRange 400 32 16777216 20 14 9455 44 = true := by decide +kernel
theorem sieve25_4_19 : svRange 400 32 16777216 20 14 9499 62 = true := by decide +kernel
theorem sieve25_4_20 : svRange 400 32 16777216 20 14 9561 102 = true := by decide +kernel
theorem sieve25_4_21 : svRange 400 32 16777216 20 14 9663 31 = true := by decide +kernel
theorem sieve25_4_22 : svRange 400 32 16777216 20 14 9694 11 = true := by decide +kernel
theorem sieve25_4_23 : svRange 400 32 16777216 20 14 9705 22 = true := by decide +kernel
theorem sieve25_4_24 : svRange 400 32 16777216 20 14 9727 48 = true := by decide +kernel
theorem sieve25_4_25 : svRange 400 32 16777216 20 14 9775 80 = true := by decide +kernel
theorem sieve25_4_26 : svRange 400 32 16777216 20 14 9855 32 = true := by decide +kernel
theorem sieve25_4_27 : svRange 400 32 16777216 20 14 9887 66 = true := by decide +kernel
theorem sieve25_4_28 : svRange 400 32 16777216 20 14 9953 40 = true := by decide +kernel
theorem sieve25_4_29 : svRange 400 32 16777216 20 14 9993 94 = true := by decide +kernel
theorem sieve25_4_30 : svRange 400 32 16777216 20 14 10087 24 = true := by decide +kernel
theorem sieve25_4_31 : svRange 400 32 16777216 20 14 10111 124 = true := by decide +kernel
theorem sieve25_4_32 : svRange 400 32 16777216 20 14 10235 4 = true := by decide +kernel
theorem sieve25_4_33 : svRange 400 32 16777216 20 14 10239 63 = true := by decide +kernel
theorem sieve25_4_34 : svRange 400 32 16777216 20 14 10302 41 = true := by decide +kernel
theorem sieve25_4_35 : svRange 400 32 16777216 20 14 10343 34 = true := by decide +kernel
theorem sieve25_4_36 : svRange 400 32 16777216 20 14 10377 32 = true := by decide +kernel

theorem sieve25_part4 : RootsOK 400 32 16777216 20 14 8359 10409 :=
  rootsOK_cons sieve25_4_0 <|
  rootsOK_cons sieve25_4_1 <|
  rootsOK_cons sieve25_4_2 <|
  rootsOK_cons sieve25_4_3 <|
  rootsOK_cons sieve25_4_4 <|
  rootsOK_cons sieve25_4_5 <|
  rootsOK_cons sieve25_4_6 <|
  rootsOK_cons sieve25_4_7 <|
  rootsOK_cons sieve25_4_8 <|
  rootsOK_cons sieve25_4_9 <|
  rootsOK_cons sieve25_4_10 <|
  rootsOK_cons sieve25_4_11 <|
  rootsOK_cons sieve25_4_12 <|
  rootsOK_cons sieve25_4_13 <|
  rootsOK_cons sieve25_4_14 <|
  rootsOK_cons sieve25_4_15 <|
  rootsOK_cons sieve25_4_16 <|
  rootsOK_cons sieve25_4_17 <|
  rootsOK_cons sieve25_4_18 <|
  rootsOK_cons sieve25_4_19 <|
  rootsOK_cons sieve25_4_20 <|
  rootsOK_cons sieve25_4_21 <|
  rootsOK_cons sieve25_4_22 <|
  rootsOK_cons sieve25_4_23 <|
  rootsOK_cons sieve25_4_24 <|
  rootsOK_cons sieve25_4_25 <|
  rootsOK_cons sieve25_4_26 <|
  rootsOK_cons sieve25_4_27 <|
  rootsOK_cons sieve25_4_28 <|
  rootsOK_cons sieve25_4_29 <|
  rootsOK_cons sieve25_4_30 <|
  rootsOK_cons sieve25_4_31 <|
  rootsOK_cons sieve25_4_32 <|
  rootsOK_cons sieve25_4_33 <|
  rootsOK_cons sieve25_4_34 <|
  rootsOK_cons sieve25_4_35 <|
  rootsOK_cons sieve25_4_36 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve25_4_0
#print axioms CollatzSearch.sieve25_part4
