import CollatzSearch.Sieve

/-! Kernel certificate part 45 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [11548, 11887), 13 blocks, estimated cost 2124170 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_45_0 : svRange 400 280 33554432 20 14 11548 34 = true := by decide +kernel
theorem sieve29_45_1 : svRange 400 280 33554432 20 14 11582 1 = true := by decide +kernel
theorem sieve29_45_2 : svRange 400 280 33554432 20 14 11583 1 = true := by decide +kernel
theorem sieve29_45_3 : svRange 400 280 33554432 20 14 11584 39 = true := by decide +kernel
theorem sieve29_45_4 : svRange 400 280 33554432 20 14 11623 1 = true := by decide +kernel
theorem sieve29_45_5 : svRange 400 280 33554432 20 14 11624 103 = true := by decide +kernel
theorem sieve29_45_6 : svRange 400 280 33554432 20 14 11727 32 = true := by decide +kernel
theorem sieve29_45_7 : svRange 400 280 33554432 20 14 11759 15 = true := by decide +kernel
theorem sieve29_45_8 : svRange 400 280 33554432 20 14 11774 1 = true := by decide +kernel
theorem sieve29_45_9 : svRange 400 280 33554432 20 14 11775 1 = true := by decide +kernel
theorem sieve29_45_10 : svRange 400 280 33554432 20 14 11776 41 = true := by decide +kernel
theorem sieve29_45_11 : svRange 400 280 33554432 20 14 11817 6 = true := by decide +kernel
theorem sieve29_45_12 : svRange 400 280 33554432 20 14 11823 64 = true := by decide +kernel

theorem sieve29_part45 : RootsOK 400 280 33554432 20 14 11548 11887 :=
  rootsOK_cons sieve29_45_0 <|
  rootsOK_cons sieve29_45_1 <|
  rootsOK_cons sieve29_45_2 <|
  rootsOK_cons sieve29_45_3 <|
  rootsOK_cons sieve29_45_4 <|
  rootsOK_cons sieve29_45_5 <|
  rootsOK_cons sieve29_45_6 <|
  rootsOK_cons sieve29_45_7 <|
  rootsOK_cons sieve29_45_8 <|
  rootsOK_cons sieve29_45_9 <|
  rootsOK_cons sieve29_45_10 <|
  rootsOK_cons sieve29_45_11 <|
  rootsOK_cons sieve29_45_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_45_0
#print axioms CollatzSearch.sieve29_part45
