import CollatzSearch.Sieve

/-! Kernel certificate part 58 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [14848, 15166), 14 blocks, estimated cost 2363459 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_58_0 : svRange 400 280 33554432 20 14 14848 111 = true := by decide +kernel
theorem sieve29_58_1 : svRange 400 280 33554432 20 14 14959 1 = true := by decide +kernel
theorem sieve29_58_2 : svRange 400 280 33554432 20 14 14960 43 = true := by decide +kernel
theorem sieve29_58_3 : svRange 400 280 33554432 20 14 15003 1 = true := by decide +kernel
theorem sieve29_58_4 : svRange 400 280 33554432 20 14 15004 13 = true := by decide +kernel
theorem sieve29_58_5 : svRange 400 280 33554432 20 14 15017 1 = true := by decide +kernel
theorem sieve29_58_6 : svRange 400 280 33554432 20 14 15018 37 = true := by decide +kernel
theorem sieve29_58_7 : svRange 400 280 33554432 20 14 15055 24 = true := by decide +kernel
theorem sieve29_58_8 : svRange 400 280 33554432 20 14 15079 1 = true := by decide +kernel
theorem sieve29_58_9 : svRange 400 280 33554432 20 14 15080 19 = true := by decide +kernel
theorem sieve29_58_10 : svRange 400 280 33554432 20 14 15099 4 = true := by decide +kernel
theorem sieve29_58_11 : svRange 400 280 33554432 20 14 15103 28 = true := by decide +kernel
theorem sieve29_58_12 : svRange 400 280 33554432 20 14 15131 1 = true := by decide +kernel
theorem sieve29_58_13 : svRange 400 280 33554432 20 14 15132 34 = true := by decide +kernel

theorem sieve29_part58 : RootsOK 400 280 33554432 20 14 14848 15166 :=
  rootsOK_cons sieve29_58_0 <|
  rootsOK_cons sieve29_58_1 <|
  rootsOK_cons sieve29_58_2 <|
  rootsOK_cons sieve29_58_3 <|
  rootsOK_cons sieve29_58_4 <|
  rootsOK_cons sieve29_58_5 <|
  rootsOK_cons sieve29_58_6 <|
  rootsOK_cons sieve29_58_7 <|
  rootsOK_cons sieve29_58_8 <|
  rootsOK_cons sieve29_58_9 <|
  rootsOK_cons sieve29_58_10 <|
  rootsOK_cons sieve29_58_11 <|
  rootsOK_cons sieve29_58_12 <|
  rootsOK_cons sieve29_58_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_58_0
#print axioms CollatzSearch.sieve29_part58
