import CollatzSearch.Sieve

/-! Kernel certificate part 31 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [8128, 8351), 13 blocks, estimated cost 2334471 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_31_0 : svRange 400 280 33554432 20 14 8128 62 = true := by decide +kernel
theorem sieve29_31_1 : svRange 400 280 33554432 20 14 8190 1 = true := by decide +kernel
theorem sieve29_31_2 : svRange 400 280 33554432 20 14 8191 1 = true := by decide +kernel
theorem sieve29_31_3 : svRange 400 280 33554432 20 14 8192 27 = true := by decide +kernel
theorem sieve29_31_4 : svRange 400 280 33554432 20 14 8219 1 = true := by decide +kernel
theorem sieve29_31_5 : svRange 400 280 33554432 20 14 8220 19 = true := by decide +kernel
theorem sieve29_31_6 : svRange 400 280 33554432 20 14 8239 1 = true := by decide +kernel
theorem sieve29_31_7 : svRange 400 280 33554432 20 14 8240 43 = true := by decide +kernel
theorem sieve29_31_8 : svRange 400 280 33554432 20 14 8283 1 = true := by decide +kernel
theorem sieve29_31_9 : svRange 400 280 33554432 20 14 8284 19 = true := by decide +kernel
theorem sieve29_31_10 : svRange 400 280 33554432 20 14 8303 1 = true := by decide +kernel
theorem sieve29_31_11 : svRange 400 280 33554432 20 14 8304 25 = true := by decide +kernel
theorem sieve29_31_12 : svRange 400 280 33554432 20 14 8329 22 = true := by decide +kernel

theorem sieve29_part31 : RootsOK 400 280 33554432 20 14 8128 8351 :=
  rootsOK_cons sieve29_31_0 <|
  rootsOK_cons sieve29_31_1 <|
  rootsOK_cons sieve29_31_2 <|
  rootsOK_cons sieve29_31_3 <|
  rootsOK_cons sieve29_31_4 <|
  rootsOK_cons sieve29_31_5 <|
  rootsOK_cons sieve29_31_6 <|
  rootsOK_cons sieve29_31_7 <|
  rootsOK_cons sieve29_31_8 <|
  rootsOK_cons sieve29_31_9 <|
  rootsOK_cons sieve29_31_10 <|
  rootsOK_cons sieve29_31_11 <|
  rootsOK_cons sieve29_31_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_31_0
#print axioms CollatzSearch.sieve29_part31
