import CollatzSearch.Sieve

/-! Kernel certificate part 17 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [4414, 4649), 14 blocks, estimated cost 2294266 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_17_0 : svRange 400 280 33554432 20 14 4414 1 = true := by decide +kernel
theorem sieve29_17_1 : svRange 400 280 33554432 20 14 4415 1 = true := by decide +kernel
theorem sieve29_17_2 : svRange 400 280 33554432 20 14 4416 95 = true := by decide +kernel
theorem sieve29_17_3 : svRange 400 280 33554432 20 14 4511 1 = true := by decide +kernel
theorem sieve29_17_4 : svRange 400 280 33554432 20 14 4512 62 = true := by decide +kernel
theorem sieve29_17_5 : svRange 400 280 33554432 20 14 4574 1 = true := by decide +kernel
theorem sieve29_17_6 : svRange 400 280 33554432 20 14 4575 1 = true := by decide +kernel
theorem sieve29_17_7 : svRange 400 280 33554432 20 14 4576 7 = true := by decide +kernel
theorem sieve29_17_8 : svRange 400 280 33554432 20 14 4583 1 = true := by decide +kernel
theorem sieve29_17_9 : svRange 400 280 33554432 20 14 4584 7 = true := by decide +kernel
theorem sieve29_17_10 : svRange 400 280 33554432 20 14 4591 1 = true := by decide +kernel
theorem sieve29_17_11 : svRange 400 280 33554432 20 14 4592 15 = true := by decide +kernel
theorem sieve29_17_12 : svRange 400 280 33554432 20 14 4607 1 = true := by decide +kernel
theorem sieve29_17_13 : svRange 400 280 33554432 20 14 4608 41 = true := by decide +kernel

theorem sieve29_part17 : RootsOK 400 280 33554432 20 14 4414 4649 :=
  rootsOK_cons sieve29_17_0 <|
  rootsOK_cons sieve29_17_1 <|
  rootsOK_cons sieve29_17_2 <|
  rootsOK_cons sieve29_17_3 <|
  rootsOK_cons sieve29_17_4 <|
  rootsOK_cons sieve29_17_5 <|
  rootsOK_cons sieve29_17_6 <|
  rootsOK_cons sieve29_17_7 <|
  rootsOK_cons sieve29_17_8 <|
  rootsOK_cons sieve29_17_9 <|
  rootsOK_cons sieve29_17_10 <|
  rootsOK_cons sieve29_17_11 <|
  rootsOK_cons sieve29_17_12 <|
  rootsOK_cons sieve29_17_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_17_0
#print axioms CollatzSearch.sieve29_part17
