import CollatzSearch.Sieve

/-! Kernel certificate part 12 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [3100, 3327), 13 blocks, estimated cost 2317175 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_12_0 : svRange 400 280 33554432 20 14 3100 75 = true := by decide +kernel
theorem sieve29_12_1 : svRange 400 280 33554432 20 14 3175 1 = true := by decide +kernel
theorem sieve29_12_2 : svRange 400 280 33554432 20 14 3176 23 = true := by decide +kernel
theorem sieve29_12_3 : svRange 400 280 33554432 20 14 3199 1 = true := by decide +kernel
theorem sieve29_12_4 : svRange 400 280 33554432 20 14 3200 27 = true := by decide +kernel
theorem sieve29_12_5 : svRange 400 280 33554432 20 14 3227 1 = true := by decide +kernel
theorem sieve29_12_6 : svRange 400 280 33554432 20 14 3228 3 = true := by decide +kernel
theorem sieve29_12_7 : svRange 400 280 33554432 20 14 3231 1 = true := by decide +kernel
theorem sieve29_12_8 : svRange 400 280 33554432 20 14 3232 47 = true := by decide +kernel
theorem sieve29_12_9 : svRange 400 280 33554432 20 14 3279 32 = true := by decide +kernel
theorem sieve29_12_10 : svRange 400 280 33554432 20 14 3311 1 = true := by decide +kernel
theorem sieve29_12_11 : svRange 400 280 33554432 20 14 3312 14 = true := by decide +kernel
theorem sieve29_12_12 : svRange 400 280 33554432 20 14 3326 1 = true := by decide +kernel

theorem sieve29_part12 : RootsOK 400 280 33554432 20 14 3100 3327 :=
  rootsOK_cons sieve29_12_0 <|
  rootsOK_cons sieve29_12_1 <|
  rootsOK_cons sieve29_12_2 <|
  rootsOK_cons sieve29_12_3 <|
  rootsOK_cons sieve29_12_4 <|
  rootsOK_cons sieve29_12_5 <|
  rootsOK_cons sieve29_12_6 <|
  rootsOK_cons sieve29_12_7 <|
  rootsOK_cons sieve29_12_8 <|
  rootsOK_cons sieve29_12_9 <|
  rootsOK_cons sieve29_12_10 <|
  rootsOK_cons sieve29_12_11 <|
  rootsOK_cons sieve29_12_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_12_0
#print axioms CollatzSearch.sieve29_part12
