import CollatzSearch.Sieve

/-! Kernel certificate part 4 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [8359, 10409), 35 blocks,
  estimated cost 1186273 units. Generated by a script; `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve24_4_0 : svRange 400 16 2 20 14 8359 56 = true := by decide +kernel
theorem sieve24_4_1 : svRange 400 16 2 20 14 8415 60 = true := by decide +kernel
theorem sieve24_4_2 : svRange 400 16 2 20 14 8475 44 = true := by decide +kernel
theorem sieve24_4_3 : svRange 400 16 2 20 14 8519 120 = true := by decide +kernel
theorem sieve24_4_4 : svRange 400 16 2 20 14 8639 48 = true := by decide +kernel
theorem sieve24_4_5 : svRange 400 16 2 20 14 8687 64 = true := by decide +kernel
theorem sieve24_4_6 : svRange 400 16 2 20 14 8751 80 = true := by decide +kernel
theorem sieve24_4_7 : svRange 400 16 2 20 14 8831 42 = true := by decide +kernel
theorem sieve24_4_8 : svRange 400 16 2 20 14 8873 62 = true := by decide +kernel
theorem sieve24_4_9 : svRange 400 16 2 20 14 8935 24 = true := by decide +kernel
theorem sieve24_4_10 : svRange 400 16 2 20 14 8959 72 = true := by decide +kernel
theorem sieve24_4_11 : svRange 400 16 2 20 14 9031 98 = true := by decide +kernel
theorem sieve24_4_12 : svRange 400 16 2 20 14 9129 53 = true := by decide +kernel
theorem sieve24_4_13 : svRange 400 16 2 20 14 9182 32 = true := by decide +kernel
theorem sieve24_4_14 : svRange 400 16 2 20 14 9214 33 = true := by decide +kernel
theorem sieve24_4_15 : svRange 400 16 2 20 14 9247 106 = true := by decide +kernel
theorem sieve24_4_16 : svRange 400 16 2 20 14 9353 102 = true := by decide +kernel
theorem sieve24_4_17 : svRange 400 16 2 20 14 9455 44 = true := by decide +kernel
theorem sieve24_4_18 : svRange 400 16 2 20 14 9499 76 = true := by decide +kernel
theorem sieve24_4_19 : svRange 400 16 2 20 14 9575 88 = true := by decide +kernel
theorem sieve24_4_20 : svRange 400 16 2 20 14 9663 31 = true := by decide +kernel
theorem sieve24_4_21 : svRange 400 16 2 20 14 9694 17 = true := by decide +kernel
theorem sieve24_4_22 : svRange 400 16 2 20 14 9711 58 = true := by decide +kernel
theorem sieve24_4_23 : svRange 400 16 2 20 14 9769 50 = true := by decide +kernel
theorem sieve24_4_24 : svRange 400 16 2 20 14 9819 68 = true := by decide +kernel
theorem sieve24_4_25 : svRange 400 16 2 20 14 9887 66 = true := by decide +kernel
theorem sieve24_4_26 : svRange 400 16 2 20 14 9953 58 = true := by decide +kernel
theorem sieve24_4_27 : svRange 400 16 2 20 14 10011 76 = true := by decide +kernel
theorem sieve24_4_28 : svRange 400 16 2 20 14 10087 24 = true := by decide +kernel
theorem sieve24_4_29 : svRange 400 16 2 20 14 10111 124 = true := by decide +kernel
theorem sieve24_4_30 : svRange 400 16 2 20 14 10235 4 = true := by decide +kernel
theorem sieve24_4_31 : svRange 400 16 2 20 14 10239 63 = true := by decide +kernel
theorem sieve24_4_32 : svRange 400 16 2 20 14 10302 41 = true := by decide +kernel
theorem sieve24_4_33 : svRange 400 16 2 20 14 10343 56 = true := by decide +kernel
theorem sieve24_4_34 : svRange 400 16 2 20 14 10399 10 = true := by decide +kernel

theorem sieve24_part4 : RootsOK 400 16 2 20 14 8359 10409 :=
  rootsOK_cons sieve24_4_0 <|
  rootsOK_cons sieve24_4_1 <|
  rootsOK_cons sieve24_4_2 <|
  rootsOK_cons sieve24_4_3 <|
  rootsOK_cons sieve24_4_4 <|
  rootsOK_cons sieve24_4_5 <|
  rootsOK_cons sieve24_4_6 <|
  rootsOK_cons sieve24_4_7 <|
  rootsOK_cons sieve24_4_8 <|
  rootsOK_cons sieve24_4_9 <|
  rootsOK_cons sieve24_4_10 <|
  rootsOK_cons sieve24_4_11 <|
  rootsOK_cons sieve24_4_12 <|
  rootsOK_cons sieve24_4_13 <|
  rootsOK_cons sieve24_4_14 <|
  rootsOK_cons sieve24_4_15 <|
  rootsOK_cons sieve24_4_16 <|
  rootsOK_cons sieve24_4_17 <|
  rootsOK_cons sieve24_4_18 <|
  rootsOK_cons sieve24_4_19 <|
  rootsOK_cons sieve24_4_20 <|
  rootsOK_cons sieve24_4_21 <|
  rootsOK_cons sieve24_4_22 <|
  rootsOK_cons sieve24_4_23 <|
  rootsOK_cons sieve24_4_24 <|
  rootsOK_cons sieve24_4_25 <|
  rootsOK_cons sieve24_4_26 <|
  rootsOK_cons sieve24_4_27 <|
  rootsOK_cons sieve24_4_28 <|
  rootsOK_cons sieve24_4_29 <|
  rootsOK_cons sieve24_4_30 <|
  rootsOK_cons sieve24_4_31 <|
  rootsOK_cons sieve24_4_32 <|
  rootsOK_cons sieve24_4_33 <|
  rootsOK_cons sieve24_4_34 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve24_4_0
#print axioms CollatzSearch.sieve24_part4
