import CollatzSearch.Sieve

/-! Kernel certificate part 25 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [6472, 6826), 15 blocks, estimated cost 2161138 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_25_0 : svRange 400 280 33554432 20 14 6472 119 = true := by decide +kernel
theorem sieve29_25_1 : svRange 400 280 33554432 20 14 6591 1 = true := by decide +kernel
theorem sieve29_25_2 : svRange 400 280 33554432 20 14 6592 30 = true := by decide +kernel
theorem sieve29_25_3 : svRange 400 280 33554432 20 14 6622 1 = true := by decide +kernel
theorem sieve29_25_4 : svRange 400 280 33554432 20 14 6623 1 = true := by decide +kernel
theorem sieve29_25_5 : svRange 400 280 33554432 20 14 6624 30 = true := by decide +kernel
theorem sieve29_25_6 : svRange 400 280 33554432 20 14 6654 1 = true := by decide +kernel
theorem sieve29_25_7 : svRange 400 280 33554432 20 14 6655 1 = true := by decide +kernel
theorem sieve29_25_8 : svRange 400 280 33554432 20 14 6656 111 = true := by decide +kernel
theorem sieve29_25_9 : svRange 400 280 33554432 20 14 6767 15 = true := by decide +kernel
theorem sieve29_25_10 : svRange 400 280 33554432 20 14 6782 29 = true := by decide +kernel
theorem sieve29_25_11 : svRange 400 280 33554432 20 14 6811 12 = true := by decide +kernel
theorem sieve29_25_12 : svRange 400 280 33554432 20 14 6823 1 = true := by decide +kernel
theorem sieve29_25_13 : svRange 400 280 33554432 20 14 6824 1 = true := by decide +kernel
theorem sieve29_25_14 : svRange 400 280 33554432 20 14 6825 1 = true := by decide +kernel

theorem sieve29_part25 : RootsOK 400 280 33554432 20 14 6472 6826 :=
  rootsOK_cons sieve29_25_0 <|
  rootsOK_cons sieve29_25_1 <|
  rootsOK_cons sieve29_25_2 <|
  rootsOK_cons sieve29_25_3 <|
  rootsOK_cons sieve29_25_4 <|
  rootsOK_cons sieve29_25_5 <|
  rootsOK_cons sieve29_25_6 <|
  rootsOK_cons sieve29_25_7 <|
  rootsOK_cons sieve29_25_8 <|
  rootsOK_cons sieve29_25_9 <|
  rootsOK_cons sieve29_25_10 <|
  rootsOK_cons sieve29_25_11 <|
  rootsOK_cons sieve29_25_12 <|
  rootsOK_cons sieve29_25_13 <|
  rootsOK_cons sieve29_25_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_25_0
#print axioms CollatzSearch.sieve29_part25
