import CollatzSearch.Sieve

/-! Kernel certificate part 39 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [10154, 10400), 15 blocks, estimated cost 2376719 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_39_0 : svRange 400 280 33554432 20 14 10154 81 = true := by decide +kernel
theorem sieve29_39_1 : svRange 400 280 33554432 20 14 10235 3 = true := by decide +kernel
theorem sieve29_39_2 : svRange 400 280 33554432 20 14 10238 1 = true := by decide +kernel
theorem sieve29_39_3 : svRange 400 280 33554432 20 14 10239 1 = true := by decide +kernel
theorem sieve29_39_4 : svRange 400 280 33554432 20 14 10240 62 = true := by decide +kernel
theorem sieve29_39_5 : svRange 400 280 33554432 20 14 10302 1 = true := by decide +kernel
theorem sieve29_39_6 : svRange 400 280 33554432 20 14 10303 8 = true := by decide +kernel
theorem sieve29_39_7 : svRange 400 280 33554432 20 14 10311 20 = true := by decide +kernel
theorem sieve29_39_8 : svRange 400 280 33554432 20 14 10331 1 = true := by decide +kernel
theorem sieve29_39_9 : svRange 400 280 33554432 20 14 10332 19 = true := by decide +kernel
theorem sieve29_39_10 : svRange 400 280 33554432 20 14 10351 1 = true := by decide +kernel
theorem sieve29_39_11 : svRange 400 280 33554432 20 14 10352 15 = true := by decide +kernel
theorem sieve29_39_12 : svRange 400 280 33554432 20 14 10367 1 = true := by decide +kernel
theorem sieve29_39_13 : svRange 400 280 33554432 20 14 10368 31 = true := by decide +kernel
theorem sieve29_39_14 : svRange 400 280 33554432 20 14 10399 1 = true := by decide +kernel

theorem sieve29_part39 : RootsOK 400 280 33554432 20 14 10154 10400 :=
  rootsOK_cons sieve29_39_0 <|
  rootsOK_cons sieve29_39_1 <|
  rootsOK_cons sieve29_39_2 <|
  rootsOK_cons sieve29_39_3 <|
  rootsOK_cons sieve29_39_4 <|
  rootsOK_cons sieve29_39_5 <|
  rootsOK_cons sieve29_39_6 <|
  rootsOK_cons sieve29_39_7 <|
  rootsOK_cons sieve29_39_8 <|
  rootsOK_cons sieve29_39_9 <|
  rootsOK_cons sieve29_39_10 <|
  rootsOK_cons sieve29_39_11 <|
  rootsOK_cons sieve29_39_12 <|
  rootsOK_cons sieve29_39_13 <|
  rootsOK_cons sieve29_39_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_39_0
#print axioms CollatzSearch.sieve29_part39
