import CollatzSearch.Sieve

/-! Kernel certificate part 0 for `DescRange (2^24) (2^20 * 32)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^24, K = 20, N = 32, forced bits f = 14, fuel 400;
  patterns [0, 2047), 36 blocks, estimated cost 1286473 units.
  Generated by Scratch/sieve_gen/gen25.py; `decide +kernel` only (no native_decide). -/

namespace CollatzSearch

theorem sieve25_0_0 : svRange 400 32 16777216 20 14 0 62 = true := by decide +kernel
theorem sieve25_0_1 : svRange 400 32 16777216 20 14 62 49 = true := by decide +kernel
theorem sieve25_0_2 : svRange 400 32 16777216 20 14 111 48 = true := by decide +kernel
theorem sieve25_0_3 : svRange 400 32 16777216 20 14 159 64 = true := by decide +kernel
theorem sieve25_0_4 : svRange 400 32 16777216 20 14 223 60 = true := by decide +kernel
theorem sieve25_0_5 : svRange 400 32 16777216 20 14 283 44 = true := by decide +kernel
theorem sieve25_0_6 : svRange 400 32 16777216 20 14 327 120 = true := by decide +kernel
theorem sieve25_0_7 : svRange 400 32 16777216 20 14 447 64 = true := by decide +kernel
theorem sieve25_0_8 : svRange 400 32 16777216 20 14 511 127 = true := by decide +kernel
theorem sieve25_0_9 : svRange 400 32 16777216 20 14 638 29 = true := by decide +kernel
theorem sieve25_0_10 : svRange 400 32 16777216 20 14 667 36 = true := by decide +kernel
theorem sieve25_0_11 : svRange 400 32 16777216 20 14 703 42 = true := by decide +kernel
theorem sieve25_0_12 : svRange 400 32 16777216 20 14 745 85 = true := by decide +kernel
theorem sieve25_0_13 : svRange 400 32 16777216 20 14 830 64 = true := by decide +kernel
theorem sieve25_0_14 : svRange 400 32 16777216 20 14 894 65 = true := by decide +kernel
theorem sieve25_0_15 : svRange 400 32 16777216 20 14 959 42 = true := by decide +kernel
theorem sieve25_0_16 : svRange 400 32 16777216 20 14 1001 22 = true := by decide +kernel
theorem sieve25_0_17 : svRange 400 32 16777216 20 14 1023 32 = true := by decide +kernel
theorem sieve25_0_18 : svRange 400 32 16777216 20 14 1055 72 = true := by decide +kernel
theorem sieve25_0_19 : svRange 400 32 16777216 20 14 1127 56 = true := by decide +kernel
theorem sieve25_0_20 : svRange 400 32 16777216 20 14 1183 80 = true := by decide +kernel
theorem sieve25_0_21 : svRange 400 32 16777216 20 14 1263 15 = true := by decide +kernel
theorem sieve25_0_22 : svRange 400 32 16777216 20 14 1278 29 = true := by decide +kernel
theorem sieve25_0_23 : svRange 400 32 16777216 20 14 1307 99 = true := by decide +kernel
theorem sieve25_0_24 : svRange 400 32 16777216 20 14 1406 33 = true := by decide +kernel
theorem sieve25_0_25 : svRange 400 32 16777216 20 14 1439 48 = true := by decide +kernel
theorem sieve25_0_26 : svRange 400 32 16777216 20 14 1487 47 = true := by decide +kernel
theorem sieve25_0_27 : svRange 400 32 16777216 20 14 1534 105 = true := by decide +kernel
theorem sieve25_0_28 : svRange 400 32 16777216 20 14 1639 52 = true := by decide +kernel
theorem sieve25_0_29 : svRange 400 32 16777216 20 14 1691 76 = true := by decide +kernel
theorem sieve25_0_30 : svRange 400 32 16777216 20 14 1767 52 = true := by decide +kernel
theorem sieve25_0_31 : svRange 400 32 16777216 20 14 1819 64 = true := by decide +kernel
theorem sieve25_0_32 : svRange 400 32 16777216 20 14 1883 35 = true := by decide +kernel
theorem sieve25_0_33 : svRange 400 32 16777216 20 14 1918 41 = true := by decide +kernel
theorem sieve25_0_34 : svRange 400 32 16777216 20 14 1959 66 = true := by decide +kernel
theorem sieve25_0_35 : svRange 400 32 16777216 20 14 2025 22 = true := by decide +kernel

theorem sieve25_part0 : RootsOK 400 32 16777216 20 14 0 2047 :=
  rootsOK_cons sieve25_0_0 <|
  rootsOK_cons sieve25_0_1 <|
  rootsOK_cons sieve25_0_2 <|
  rootsOK_cons sieve25_0_3 <|
  rootsOK_cons sieve25_0_4 <|
  rootsOK_cons sieve25_0_5 <|
  rootsOK_cons sieve25_0_6 <|
  rootsOK_cons sieve25_0_7 <|
  rootsOK_cons sieve25_0_8 <|
  rootsOK_cons sieve25_0_9 <|
  rootsOK_cons sieve25_0_10 <|
  rootsOK_cons sieve25_0_11 <|
  rootsOK_cons sieve25_0_12 <|
  rootsOK_cons sieve25_0_13 <|
  rootsOK_cons sieve25_0_14 <|
  rootsOK_cons sieve25_0_15 <|
  rootsOK_cons sieve25_0_16 <|
  rootsOK_cons sieve25_0_17 <|
  rootsOK_cons sieve25_0_18 <|
  rootsOK_cons sieve25_0_19 <|
  rootsOK_cons sieve25_0_20 <|
  rootsOK_cons sieve25_0_21 <|
  rootsOK_cons sieve25_0_22 <|
  rootsOK_cons sieve25_0_23 <|
  rootsOK_cons sieve25_0_24 <|
  rootsOK_cons sieve25_0_25 <|
  rootsOK_cons sieve25_0_26 <|
  rootsOK_cons sieve25_0_27 <|
  rootsOK_cons sieve25_0_28 <|
  rootsOK_cons sieve25_0_29 <|
  rootsOK_cons sieve25_0_30 <|
  rootsOK_cons sieve25_0_31 <|
  rootsOK_cons sieve25_0_32 <|
  rootsOK_cons sieve25_0_33 <|
  rootsOK_cons sieve25_0_34 <|
  rootsOK_cons sieve25_0_35 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve25_0_0
#print axioms CollatzSearch.sieve25_part0
