import CollatzSearch.Sieve

/-! Kernel certificate part 11 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [2887, 3100), 15 blocks, estimated cost 2351431 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_11_0 : svRange 400 280 33554432 20 14 2887 32 = true := by decide +kernel
theorem sieve29_11_1 : svRange 400 280 33554432 20 14 2919 8 = true := by decide +kernel
theorem sieve29_11_2 : svRange 400 280 33554432 20 14 2927 15 = true := by decide +kernel
theorem sieve29_11_3 : svRange 400 280 33554432 20 14 2942 1 = true := by decide +kernel
theorem sieve29_11_4 : svRange 400 280 33554432 20 14 2943 1 = true := by decide +kernel
theorem sieve29_11_5 : svRange 400 280 33554432 20 14 2944 63 = true := by decide +kernel
theorem sieve29_11_6 : svRange 400 280 33554432 20 14 3007 1 = true := by decide +kernel
theorem sieve29_11_7 : svRange 400 280 33554432 20 14 3008 41 = true := by decide +kernel
theorem sieve29_11_8 : svRange 400 280 33554432 20 14 3049 1 = true := by decide +kernel
theorem sieve29_11_9 : svRange 400 280 33554432 20 14 3050 5 = true := by decide +kernel
theorem sieve29_11_10 : svRange 400 280 33554432 20 14 3055 1 = true := by decide +kernel
theorem sieve29_11_11 : svRange 400 280 33554432 20 14 3056 15 = true := by decide +kernel
theorem sieve29_11_12 : svRange 400 280 33554432 20 14 3071 1 = true := by decide +kernel
theorem sieve29_11_13 : svRange 400 280 33554432 20 14 3072 27 = true := by decide +kernel
theorem sieve29_11_14 : svRange 400 280 33554432 20 14 3099 1 = true := by decide +kernel

theorem sieve29_part11 : RootsOK 400 280 33554432 20 14 2887 3100 :=
  rootsOK_cons sieve29_11_0 <|
  rootsOK_cons sieve29_11_1 <|
  rootsOK_cons sieve29_11_2 <|
  rootsOK_cons sieve29_11_3 <|
  rootsOK_cons sieve29_11_4 <|
  rootsOK_cons sieve29_11_5 <|
  rootsOK_cons sieve29_11_6 <|
  rootsOK_cons sieve29_11_7 <|
  rootsOK_cons sieve29_11_8 <|
  rootsOK_cons sieve29_11_9 <|
  rootsOK_cons sieve29_11_10 <|
  rootsOK_cons sieve29_11_11 <|
  rootsOK_cons sieve29_11_12 <|
  rootsOK_cons sieve29_11_13 <|
  rootsOK_cons sieve29_11_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_11_0
#print axioms CollatzSearch.sieve29_part11
