import CollatzSearch.Sieve

/-! Kernel certificate part 36 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [9386, 9695), 16 blocks, estimated cost 2310501 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_36_0 : svRange 400 280 33554432 20 14 9386 69 = true := by decide +kernel
theorem sieve29_36_1 : svRange 400 280 33554432 20 14 9455 1 = true := by decide +kernel
theorem sieve29_36_2 : svRange 400 280 33554432 20 14 9456 14 = true := by decide +kernel
theorem sieve29_36_3 : svRange 400 280 33554432 20 14 9470 1 = true := by decide +kernel
theorem sieve29_36_4 : svRange 400 280 33554432 20 14 9471 28 = true := by decide +kernel
theorem sieve29_36_5 : svRange 400 280 33554432 20 14 9499 1 = true := by decide +kernel
theorem sieve29_36_6 : svRange 400 280 33554432 20 14 9500 35 = true := by decide +kernel
theorem sieve29_36_7 : svRange 400 280 33554432 20 14 9535 8 = true := by decide +kernel
theorem sieve29_36_8 : svRange 400 280 33554432 20 14 9543 32 = true := by decide +kernel
theorem sieve29_36_9 : svRange 400 280 33554432 20 14 9575 23 = true := by decide +kernel
theorem sieve29_36_10 : svRange 400 280 33554432 20 14 9598 1 = true := by decide +kernel
theorem sieve29_36_11 : svRange 400 280 33554432 20 14 9599 32 = true := by decide +kernel
theorem sieve29_36_12 : svRange 400 280 33554432 20 14 9631 32 = true := by decide +kernel
theorem sieve29_36_13 : svRange 400 280 33554432 20 14 9663 1 = true := by decide +kernel
theorem sieve29_36_14 : svRange 400 280 33554432 20 14 9664 30 = true := by decide +kernel
theorem sieve29_36_15 : svRange 400 280 33554432 20 14 9694 1 = true := by decide +kernel

theorem sieve29_part36 : RootsOK 400 280 33554432 20 14 9386 9695 :=
  rootsOK_cons sieve29_36_0 <|
  rootsOK_cons sieve29_36_1 <|
  rootsOK_cons sieve29_36_2 <|
  rootsOK_cons sieve29_36_3 <|
  rootsOK_cons sieve29_36_4 <|
  rootsOK_cons sieve29_36_5 <|
  rootsOK_cons sieve29_36_6 <|
  rootsOK_cons sieve29_36_7 <|
  rootsOK_cons sieve29_36_8 <|
  rootsOK_cons sieve29_36_9 <|
  rootsOK_cons sieve29_36_10 <|
  rootsOK_cons sieve29_36_11 <|
  rootsOK_cons sieve29_36_12 <|
  rootsOK_cons sieve29_36_13 <|
  rootsOK_cons sieve29_36_14 <|
  rootsOK_cons sieve29_36_15 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_36_0
#print axioms CollatzSearch.sieve29_part36
