import CollatzSearch.Sieve

/-! Kernel certificate part 27 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [7145, 7336), 12 blocks, estimated cost 2208026 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_27_0 : svRange 400 280 33554432 20 14 7145 1 = true := by decide +kernel
theorem sieve29_27_1 : svRange 400 280 33554432 20 14 7146 20 = true := by decide +kernel
theorem sieve29_27_2 : svRange 400 280 33554432 20 14 7166 1 = true := by decide +kernel
theorem sieve29_27_3 : svRange 400 280 33554432 20 14 7167 1 = true := by decide +kernel
theorem sieve29_27_4 : svRange 400 280 33554432 20 14 7168 103 = true := by decide +kernel
theorem sieve29_27_5 : svRange 400 280 33554432 20 14 7271 8 = true := by decide +kernel
theorem sieve29_27_6 : svRange 400 280 33554432 20 14 7279 16 = true := by decide +kernel
theorem sieve29_27_7 : svRange 400 280 33554432 20 14 7295 1 = true := by decide +kernel
theorem sieve29_27_8 : svRange 400 280 33554432 20 14 7296 27 = true := by decide +kernel
theorem sieve29_27_9 : svRange 400 280 33554432 20 14 7323 4 = true := by decide +kernel
theorem sieve29_27_10 : svRange 400 280 33554432 20 14 7327 8 = true := by decide +kernel
theorem sieve29_27_11 : svRange 400 280 33554432 20 14 7335 1 = true := by decide +kernel

theorem sieve29_part27 : RootsOK 400 280 33554432 20 14 7145 7336 :=
  rootsOK_cons sieve29_27_0 <|
  rootsOK_cons sieve29_27_1 <|
  rootsOK_cons sieve29_27_2 <|
  rootsOK_cons sieve29_27_3 <|
  rootsOK_cons sieve29_27_4 <|
  rootsOK_cons sieve29_27_5 <|
  rootsOK_cons sieve29_27_6 <|
  rootsOK_cons sieve29_27_7 <|
  rootsOK_cons sieve29_27_8 <|
  rootsOK_cons sieve29_27_9 <|
  rootsOK_cons sieve29_27_10 <|
  rootsOK_cons sieve29_27_11 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_27_0
#print axioms CollatzSearch.sieve29_part27
