import CollatzSearch.Sieve

/-! Kernel certificate part 15 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [3871, 4137), 12 blocks, estimated cost 2309412 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_15_0 : svRange 400 280 33554432 20 14 3871 60 = true := by decide +kernel
theorem sieve29_15_1 : svRange 400 280 33554432 20 14 3931 1 = true := by decide +kernel
theorem sieve29_15_2 : svRange 400 280 33554432 20 14 3932 11 = true := by decide +kernel
theorem sieve29_15_3 : svRange 400 280 33554432 20 14 3943 1 = true := by decide +kernel
theorem sieve29_15_4 : svRange 400 280 33554432 20 14 3944 55 = true := by decide +kernel
theorem sieve29_15_5 : svRange 400 280 33554432 20 14 3999 1 = true := by decide +kernel
theorem sieve29_15_6 : svRange 400 280 33554432 20 14 4000 65 = true := by decide +kernel
theorem sieve29_15_7 : svRange 400 280 33554432 20 14 4065 1 = true := by decide +kernel
theorem sieve29_15_8 : svRange 400 280 33554432 20 14 4066 28 = true := by decide +kernel
theorem sieve29_15_9 : svRange 400 280 33554432 20 14 4094 1 = true := by decide +kernel
theorem sieve29_15_10 : svRange 400 280 33554432 20 14 4095 1 = true := by decide +kernel
theorem sieve29_15_11 : svRange 400 280 33554432 20 14 4096 41 = true := by decide +kernel

theorem sieve29_part15 : RootsOK 400 280 33554432 20 14 3871 4137 :=
  rootsOK_cons sieve29_15_0 <|
  rootsOK_cons sieve29_15_1 <|
  rootsOK_cons sieve29_15_2 <|
  rootsOK_cons sieve29_15_3 <|
  rootsOK_cons sieve29_15_4 <|
  rootsOK_cons sieve29_15_5 <|
  rootsOK_cons sieve29_15_6 <|
  rootsOK_cons sieve29_15_7 <|
  rootsOK_cons sieve29_15_8 <|
  rootsOK_cons sieve29_15_9 <|
  rootsOK_cons sieve29_15_10 <|
  rootsOK_cons sieve29_15_11 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_15_0
#print axioms CollatzSearch.sieve29_part15
