import CollatzSearch.Sieve

/-! Kernel certificate part 30 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [7850, 8128), 13 blocks, estimated cost 2322396 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_30_0 : svRange 400 280 33554432 20 14 7850 37 = true := by decide +kernel
theorem sieve29_30_1 : svRange 400 280 33554432 20 14 7887 1 = true := by decide +kernel
theorem sieve29_30_2 : svRange 400 280 33554432 20 14 7888 47 = true := by decide +kernel
theorem sieve29_30_3 : svRange 400 280 33554432 20 14 7935 1 = true := by decide +kernel
theorem sieve29_30_4 : svRange 400 280 33554432 20 14 7936 27 = true := by decide +kernel
theorem sieve29_30_5 : svRange 400 280 33554432 20 14 7963 1 = true := by decide +kernel
theorem sieve29_30_6 : svRange 400 280 33554432 20 14 7964 35 = true := by decide +kernel
theorem sieve29_30_7 : svRange 400 280 33554432 20 14 7999 28 = true := by decide +kernel
theorem sieve29_30_8 : svRange 400 280 33554432 20 14 8027 12 = true := by decide +kernel
theorem sieve29_30_9 : svRange 400 280 33554432 20 14 8039 1 = true := by decide +kernel
theorem sieve29_30_10 : svRange 400 280 33554432 20 14 8040 55 = true := by decide +kernel
theorem sieve29_30_11 : svRange 400 280 33554432 20 14 8095 32 = true := by decide +kernel
theorem sieve29_30_12 : svRange 400 280 33554432 20 14 8127 1 = true := by decide +kernel

theorem sieve29_part30 : RootsOK 400 280 33554432 20 14 7850 8128 :=
  rootsOK_cons sieve29_30_0 <|
  rootsOK_cons sieve29_30_1 <|
  rootsOK_cons sieve29_30_2 <|
  rootsOK_cons sieve29_30_3 <|
  rootsOK_cons sieve29_30_4 <|
  rootsOK_cons sieve29_30_5 <|
  rootsOK_cons sieve29_30_6 <|
  rootsOK_cons sieve29_30_7 <|
  rootsOK_cons sieve29_30_8 <|
  rootsOK_cons sieve29_30_9 <|
  rootsOK_cons sieve29_30_10 <|
  rootsOK_cons sieve29_30_11 <|
  rootsOK_cons sieve29_30_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_30_0
#print axioms CollatzSearch.sieve29_part30
