import CollatzSearch.Sieve

/-! Kernel certificate part 19 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [4935, 5223), 14 blocks, estimated cost 2261347 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_19_0 : svRange 400 280 33554432 20 14 4935 1 = true := by decide +kernel
theorem sieve29_19_1 : svRange 400 280 33554432 20 14 4936 54 = true := by decide +kernel
theorem sieve29_19_2 : svRange 400 280 33554432 20 14 4990 1 = true := by decide +kernel
theorem sieve29_19_3 : svRange 400 280 33554432 20 14 4991 42 = true := by decide +kernel
theorem sieve29_19_4 : svRange 400 280 33554432 20 14 5033 22 = true := by decide +kernel
theorem sieve29_19_5 : svRange 400 280 33554432 20 14 5055 1 = true := by decide +kernel
theorem sieve29_19_6 : svRange 400 280 33554432 20 14 5056 62 = true := by decide +kernel
theorem sieve29_19_7 : svRange 400 280 33554432 20 14 5118 1 = true := by decide +kernel
theorem sieve29_19_8 : svRange 400 280 33554432 20 14 5119 1 = true := by decide +kernel
theorem sieve29_19_9 : svRange 400 280 33554432 20 14 5120 27 = true := by decide +kernel
theorem sieve29_19_10 : svRange 400 280 33554432 20 14 5147 1 = true := by decide +kernel
theorem sieve29_19_11 : svRange 400 280 33554432 20 14 5148 19 = true := by decide +kernel
theorem sieve29_19_12 : svRange 400 280 33554432 20 14 5167 44 = true := by decide +kernel
theorem sieve29_19_13 : svRange 400 280 33554432 20 14 5211 12 = true := by decide +kernel

theorem sieve29_part19 : RootsOK 400 280 33554432 20 14 4935 5223 :=
  rootsOK_cons sieve29_19_0 <|
  rootsOK_cons sieve29_19_1 <|
  rootsOK_cons sieve29_19_2 <|
  rootsOK_cons sieve29_19_3 <|
  rootsOK_cons sieve29_19_4 <|
  rootsOK_cons sieve29_19_5 <|
  rootsOK_cons sieve29_19_6 <|
  rootsOK_cons sieve29_19_7 <|
  rootsOK_cons sieve29_19_8 <|
  rootsOK_cons sieve29_19_9 <|
  rootsOK_cons sieve29_19_10 <|
  rootsOK_cons sieve29_19_11 <|
  rootsOK_cons sieve29_19_12 <|
  rootsOK_cons sieve29_19_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_19_0
#print axioms CollatzSearch.sieve29_part19
