import CollatzSearch.Sieve

/-! Kernel certificate part 62 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [15904, 16156), 13 blocks, estimated cost 2342757 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_62_0 : svRange 400 280 33554432 20 14 15904 71 = true := by decide +kernel
theorem sieve29_62_1 : svRange 400 280 33554432 20 14 15975 24 = true := by decide +kernel
theorem sieve29_62_2 : svRange 400 280 33554432 20 14 15999 1 = true := by decide +kernel
theorem sieve29_62_3 : svRange 400 280 33554432 20 14 16000 41 = true := by decide +kernel
theorem sieve29_62_4 : svRange 400 280 33554432 20 14 16041 1 = true := by decide +kernel
theorem sieve29_62_5 : svRange 400 280 33554432 20 14 16042 21 = true := by decide +kernel
theorem sieve29_62_6 : svRange 400 280 33554432 20 14 16063 1 = true := by decide +kernel
theorem sieve29_62_7 : svRange 400 280 33554432 20 14 16064 15 = true := by decide +kernel
theorem sieve29_62_8 : svRange 400 280 33554432 20 14 16079 1 = true := by decide +kernel
theorem sieve29_62_9 : svRange 400 280 33554432 20 14 16080 47 = true := by decide +kernel
theorem sieve29_62_10 : svRange 400 280 33554432 20 14 16127 1 = true := by decide +kernel
theorem sieve29_62_11 : svRange 400 280 33554432 20 14 16128 27 = true := by decide +kernel
theorem sieve29_62_12 : svRange 400 280 33554432 20 14 16155 1 = true := by decide +kernel

theorem sieve29_part62 : RootsOK 400 280 33554432 20 14 15904 16156 :=
  rootsOK_cons sieve29_62_0 <|
  rootsOK_cons sieve29_62_1 <|
  rootsOK_cons sieve29_62_2 <|
  rootsOK_cons sieve29_62_3 <|
  rootsOK_cons sieve29_62_4 <|
  rootsOK_cons sieve29_62_5 <|
  rootsOK_cons sieve29_62_6 <|
  rootsOK_cons sieve29_62_7 <|
  rootsOK_cons sieve29_62_8 <|
  rootsOK_cons sieve29_62_9 <|
  rootsOK_cons sieve29_62_10 <|
  rootsOK_cons sieve29_62_11 <|
  rootsOK_cons sieve29_62_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_62_0
#print axioms CollatzSearch.sieve29_part62
