import CollatzSearch.Sieve

/-! Kernel certificate part 48 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [12330, 12540), 13 blocks, estimated cost 2175976 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_48_0 : svRange 400 280 33554432 20 14 12330 29 = true := by decide +kernel
theorem sieve29_48_1 : svRange 400 280 33554432 20 14 12359 1 = true := by decide +kernel
theorem sieve29_48_2 : svRange 400 280 33554432 20 14 12360 39 = true := by decide +kernel
theorem sieve29_48_3 : svRange 400 280 33554432 20 14 12399 1 = true := by decide +kernel
theorem sieve29_48_4 : svRange 400 280 33554432 20 14 12400 47 = true := by decide +kernel
theorem sieve29_48_5 : svRange 400 280 33554432 20 14 12447 1 = true := by decide +kernel
theorem sieve29_48_6 : svRange 400 280 33554432 20 14 12448 9 = true := by decide +kernel
theorem sieve29_48_7 : svRange 400 280 33554432 20 14 12457 22 = true := by decide +kernel
theorem sieve29_48_8 : svRange 400 280 33554432 20 14 12479 34 = true := by decide +kernel
theorem sieve29_48_9 : svRange 400 280 33554432 20 14 12513 14 = true := by decide +kernel
theorem sieve29_48_10 : svRange 400 280 33554432 20 14 12527 1 = true := by decide +kernel
theorem sieve29_48_11 : svRange 400 280 33554432 20 14 12528 11 = true := by decide +kernel
theorem sieve29_48_12 : svRange 400 280 33554432 20 14 12539 1 = true := by decide +kernel

theorem sieve29_part48 : RootsOK 400 280 33554432 20 14 12330 12540 :=
  rootsOK_cons sieve29_48_0 <|
  rootsOK_cons sieve29_48_1 <|
  rootsOK_cons sieve29_48_2 <|
  rootsOK_cons sieve29_48_3 <|
  rootsOK_cons sieve29_48_4 <|
  rootsOK_cons sieve29_48_5 <|
  rootsOK_cons sieve29_48_6 <|
  rootsOK_cons sieve29_48_7 <|
  rootsOK_cons sieve29_48_8 <|
  rootsOK_cons sieve29_48_9 <|
  rootsOK_cons sieve29_48_10 <|
  rootsOK_cons sieve29_48_11 <|
  rootsOK_cons sieve29_48_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_48_0
#print axioms CollatzSearch.sieve29_part48
