import CollatzSearch.Sieve

/-! Kernel certificate part 61 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [15663, 15904), 14 blocks, estimated cost 2321750 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_61_0 : svRange 400 280 33554432 20 14 15663 1 = true := by decide +kernel
theorem sieve29_61_1 : svRange 400 280 33554432 20 14 15664 15 = true := by decide +kernel
theorem sieve29_61_2 : svRange 400 280 33554432 20 14 15679 40 = true := by decide +kernel
theorem sieve29_61_3 : svRange 400 280 33554432 20 14 15719 23 = true := by decide +kernel
theorem sieve29_61_4 : svRange 400 280 33554432 20 14 15742 1 = true := by decide +kernel
theorem sieve29_61_5 : svRange 400 280 33554432 20 14 15743 32 = true := by decide +kernel
theorem sieve29_61_6 : svRange 400 280 33554432 20 14 15775 1 = true := by decide +kernel
theorem sieve29_61_7 : svRange 400 280 33554432 20 14 15776 31 = true := by decide +kernel
theorem sieve29_61_8 : svRange 400 280 33554432 20 14 15807 1 = true := by decide +kernel
theorem sieve29_61_9 : svRange 400 280 33554432 20 14 15808 62 = true := by decide +kernel
theorem sieve29_61_10 : svRange 400 280 33554432 20 14 15870 1 = true := by decide +kernel
theorem sieve29_61_11 : svRange 400 280 33554432 20 14 15871 1 = true := by decide +kernel
theorem sieve29_61_12 : svRange 400 280 33554432 20 14 15872 31 = true := by decide +kernel
theorem sieve29_61_13 : svRange 400 280 33554432 20 14 15903 1 = true := by decide +kernel

theorem sieve29_part61 : RootsOK 400 280 33554432 20 14 15663 15904 :=
  rootsOK_cons sieve29_61_0 <|
  rootsOK_cons sieve29_61_1 <|
  rootsOK_cons sieve29_61_2 <|
  rootsOK_cons sieve29_61_3 <|
  rootsOK_cons sieve29_61_4 <|
  rootsOK_cons sieve29_61_5 <|
  rootsOK_cons sieve29_61_6 <|
  rootsOK_cons sieve29_61_7 <|
  rootsOK_cons sieve29_61_8 <|
  rootsOK_cons sieve29_61_9 <|
  rootsOK_cons sieve29_61_10 <|
  rootsOK_cons sieve29_61_11 <|
  rootsOK_cons sieve29_61_12 <|
  rootsOK_cons sieve29_61_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_61_0
#print axioms CollatzSearch.sieve29_part61
