import CollatzSearch.Sieve

/-! Kernel certificate part 55 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [14090, 14428), 14 blocks, estimated cost 2372609 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_55_0 : svRange 400 280 33554432 20 14 14090 17 = true := by decide +kernel
theorem sieve29_55_1 : svRange 400 280 33554432 20 14 14107 1 = true := by decide +kernel
theorem sieve29_55_2 : svRange 400 280 33554432 20 14 14108 83 = true := by decide +kernel
theorem sieve29_55_3 : svRange 400 280 33554432 20 14 14191 56 = true := by decide +kernel
theorem sieve29_55_4 : svRange 400 280 33554432 20 14 14247 1 = true := by decide +kernel
theorem sieve29_55_5 : svRange 400 280 33554432 20 14 14248 1 = true := by decide +kernel
theorem sieve29_55_6 : svRange 400 280 33554432 20 14 14249 1 = true := by decide +kernel
theorem sieve29_55_7 : svRange 400 280 33554432 20 14 14250 81 = true := by decide +kernel
theorem sieve29_55_8 : svRange 400 280 33554432 20 14 14331 3 = true := by decide +kernel
theorem sieve29_55_9 : svRange 400 280 33554432 20 14 14334 1 = true := by decide +kernel
theorem sieve29_55_10 : svRange 400 280 33554432 20 14 14335 1 = true := by decide +kernel
theorem sieve29_55_11 : svRange 400 280 33554432 20 14 14336 63 = true := by decide +kernel
theorem sieve29_55_12 : svRange 400 280 33554432 20 14 14399 28 = true := by decide +kernel
theorem sieve29_55_13 : svRange 400 280 33554432 20 14 14427 1 = true := by decide +kernel

theorem sieve29_part55 : RootsOK 400 280 33554432 20 14 14090 14428 :=
  rootsOK_cons sieve29_55_0 <|
  rootsOK_cons sieve29_55_1 <|
  rootsOK_cons sieve29_55_2 <|
  rootsOK_cons sieve29_55_3 <|
  rootsOK_cons sieve29_55_4 <|
  rootsOK_cons sieve29_55_5 <|
  rootsOK_cons sieve29_55_6 <|
  rootsOK_cons sieve29_55_7 <|
  rootsOK_cons sieve29_55_8 <|
  rootsOK_cons sieve29_55_9 <|
  rootsOK_cons sieve29_55_10 <|
  rootsOK_cons sieve29_55_11 <|
  rootsOK_cons sieve29_55_12 <|
  rootsOK_cons sieve29_55_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_55_0
#print axioms CollatzSearch.sieve29_part55
