import CollatzSearch.Sieve

/-! Kernel certificate part 43 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [11071, 11296), 15 blocks, estimated cost 2290497 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_43_0 : svRange 400 280 33554432 20 14 11071 1 = true := by decide +kernel
theorem sieve29_43_1 : svRange 400 280 33554432 20 14 11072 39 = true := by decide +kernel
theorem sieve29_43_2 : svRange 400 280 33554432 20 14 11111 1 = true := by decide +kernel
theorem sieve29_43_3 : svRange 400 280 33554432 20 14 11112 22 = true := by decide +kernel
theorem sieve29_43_4 : svRange 400 280 33554432 20 14 11134 1 = true := by decide +kernel
theorem sieve29_43_5 : svRange 400 280 33554432 20 14 11135 1 = true := by decide +kernel
theorem sieve29_43_6 : svRange 400 280 33554432 20 14 11136 9 = true := by decide +kernel
theorem sieve29_43_7 : svRange 400 280 33554432 20 14 11145 1 = true := by decide +kernel
theorem sieve29_43_8 : svRange 400 280 33554432 20 14 11146 53 = true := by decide +kernel
theorem sieve29_43_9 : svRange 400 280 33554432 20 14 11199 42 = true := by decide +kernel
theorem sieve29_43_10 : svRange 400 280 33554432 20 14 11241 6 = true := by decide +kernel
theorem sieve29_43_11 : svRange 400 280 33554432 20 14 11247 16 = true := by decide +kernel
theorem sieve29_43_12 : svRange 400 280 33554432 20 14 11263 1 = true := by decide +kernel
theorem sieve29_43_13 : svRange 400 280 33554432 20 14 11264 31 = true := by decide +kernel
theorem sieve29_43_14 : svRange 400 280 33554432 20 14 11295 1 = true := by decide +kernel

theorem sieve29_part43 : RootsOK 400 280 33554432 20 14 11071 11296 :=
  rootsOK_cons sieve29_43_0 <|
  rootsOK_cons sieve29_43_1 <|
  rootsOK_cons sieve29_43_2 <|
  rootsOK_cons sieve29_43_3 <|
  rootsOK_cons sieve29_43_4 <|
  rootsOK_cons sieve29_43_5 <|
  rootsOK_cons sieve29_43_6 <|
  rootsOK_cons sieve29_43_7 <|
  rootsOK_cons sieve29_43_8 <|
  rootsOK_cons sieve29_43_9 <|
  rootsOK_cons sieve29_43_10 <|
  rootsOK_cons sieve29_43_11 <|
  rootsOK_cons sieve29_43_12 <|
  rootsOK_cons sieve29_43_13 <|
  rootsOK_cons sieve29_43_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_43_0
#print axioms CollatzSearch.sieve29_part43
