import CollatzSearch.Sieve

/-! Kernel certificate part 2 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [603, 796), 15 blocks, estimated cost 2342898 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_2_0 : svRange 400 280 33554432 20 14 603 35 = true := by decide +kernel
theorem sieve29_2_1 : svRange 400 280 33554432 20 14 638 1 = true := by decide +kernel
theorem sieve29_2_2 : svRange 400 280 33554432 20 14 639 1 = true := by decide +kernel
theorem sieve29_2_3 : svRange 400 280 33554432 20 14 640 27 = true := by decide +kernel
theorem sieve29_2_4 : svRange 400 280 33554432 20 14 667 1 = true := by decide +kernel
theorem sieve29_2_5 : svRange 400 280 33554432 20 14 668 13 = true := by decide +kernel
theorem sieve29_2_6 : svRange 400 280 33554432 20 14 681 1 = true := by decide +kernel
theorem sieve29_2_7 : svRange 400 280 33554432 20 14 682 21 = true := by decide +kernel
theorem sieve29_2_8 : svRange 400 280 33554432 20 14 703 1 = true := by decide +kernel
theorem sieve29_2_9 : svRange 400 280 33554432 20 14 704 39 = true := by decide +kernel
theorem sieve29_2_10 : svRange 400 280 33554432 20 14 743 2 = true := by decide +kernel
theorem sieve29_2_11 : svRange 400 280 33554432 20 14 745 6 = true := by decide +kernel
theorem sieve29_2_12 : svRange 400 280 33554432 20 14 751 16 = true := by decide +kernel
theorem sieve29_2_13 : svRange 400 280 33554432 20 14 767 28 = true := by decide +kernel
theorem sieve29_2_14 : svRange 400 280 33554432 20 14 795 1 = true := by decide +kernel

theorem sieve29_part2 : RootsOK 400 280 33554432 20 14 603 796 :=
  rootsOK_cons sieve29_2_0 <|
  rootsOK_cons sieve29_2_1 <|
  rootsOK_cons sieve29_2_2 <|
  rootsOK_cons sieve29_2_3 <|
  rootsOK_cons sieve29_2_4 <|
  rootsOK_cons sieve29_2_5 <|
  rootsOK_cons sieve29_2_6 <|
  rootsOK_cons sieve29_2_7 <|
  rootsOK_cons sieve29_2_8 <|
  rootsOK_cons sieve29_2_9 <|
  rootsOK_cons sieve29_2_10 <|
  rootsOK_cons sieve29_2_11 <|
  rootsOK_cons sieve29_2_12 <|
  rootsOK_cons sieve29_2_13 <|
  rootsOK_cons sieve29_2_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_2_0
#print axioms CollatzSearch.sieve29_part2
