import CollatzSearch.Sieve

/-! Kernel certificate part 2 for `DescRange 2 (2^20 * 16)`: residue-tree sieve,
  K = 20, N = 16, forced bits f = 14, fuel 400; patterns [4167, 6313), 36 blocks,
  estimated cost 1198045 units. Generated by a script; `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve24_2_0 : svRange 400 16 2 20 14 4167 88 = true := by decide +kernel
theorem sieve24_2_1 : svRange 400 16 2 20 14 4255 10 = true := by decide +kernel
theorem sieve24_2_2 : svRange 400 16 2 20 14 4265 70 = true := by decide +kernel
theorem sieve24_2_3 : svRange 400 16 2 20 14 4335 44 = true := by decide +kernel
theorem sieve24_2_4 : svRange 400 16 2 20 14 4379 44 = true := by decide +kernel
theorem sieve24_2_5 : svRange 400 16 2 20 14 4423 151 = true := by decide +kernel
theorem sieve24_2_6 : svRange 400 16 2 20 14 4574 9 = true := by decide +kernel
theorem sieve24_2_7 : svRange 400 16 2 20 14 4583 24 = true := by decide +kernel
theorem sieve24_2_8 : svRange 400 16 2 20 14 4607 112 = true := by decide +kernel
theorem sieve24_2_9 : svRange 400 16 2 20 14 4719 56 = true := by decide +kernel
theorem sieve24_2_10 : svRange 400 16 2 20 14 4775 58 = true := by decide +kernel
theorem sieve24_2_11 : svRange 400 16 2 20 14 4833 30 = true := by decide +kernel
theorem sieve24_2_12 : svRange 400 16 2 20 14 4863 72 = true := by decide +kernel
theorem sieve24_2_13 : svRange 400 16 2 20 14 4935 98 = true := by decide +kernel
theorem sieve24_2_14 : svRange 400 16 2 20 14 5033 85 = true := by decide +kernel
theorem sieve24_2_15 : svRange 400 16 2 20 14 5118 1 = true := by decide +kernel
theorem sieve24_2_16 : svRange 400 16 2 20 14 5119 32 = true := by decide +kernel
theorem sieve24_2_17 : svRange 400 16 2 20 14 5151 96 = true := by decide +kernel
theorem sieve24_2_18 : svRange 400 16 2 20 14 5247 32 = true := by decide +kernel
theorem sieve24_2_19 : svRange 400 16 2 20 14 5279 80 = true := by decide +kernel
theorem sieve24_2_20 : svRange 400 16 2 20 14 5359 44 = true := by decide +kernel
theorem sieve24_2_21 : svRange 400 16 2 20 14 5403 99 = true := by decide +kernel
theorem sieve24_2_22 : svRange 400 16 2 20 14 5502 65 = true := by decide +kernel
theorem sieve24_2_23 : svRange 400 16 2 20 14 5567 63 = true := by decide +kernel
theorem sieve24_2_24 : svRange 400 16 2 20 14 5630 49 = true := by decide +kernel
theorem sieve24_2_25 : svRange 400 16 2 20 14 5679 80 = true := by decide +kernel
theorem sieve24_2_26 : svRange 400 16 2 20 14 5759 104 = true := by decide +kernel
theorem sieve24_2_27 : svRange 400 16 2 20 14 5863 24 = true := by decide +kernel
theorem sieve24_2_28 : svRange 400 16 2 20 14 5887 28 = true := by decide +kernel
theorem sieve24_2_29 : svRange 400 16 2 20 14 5915 84 = true := by decide +kernel
theorem sieve24_2_30 : svRange 400 16 2 20 14 5999 58 = true := by decide +kernel
theorem sieve24_2_31 : svRange 400 16 2 20 14 6057 64 = true := by decide +kernel
theorem sieve24_2_32 : svRange 400 16 2 20 14 6121 22 = true := by decide +kernel
theorem sieve24_2_33 : svRange 400 16 2 20 14 6143 64 = true := by decide +kernel
theorem sieve24_2_34 : svRange 400 16 2 20 14 6207 96 = true := by decide +kernel
theorem sieve24_2_35 : svRange 400 16 2 20 14 6303 10 = true := by decide +kernel

theorem sieve24_part2 : RootsOK 400 16 2 20 14 4167 6313 :=
  rootsOK_cons sieve24_2_0 <|
  rootsOK_cons sieve24_2_1 <|
  rootsOK_cons sieve24_2_2 <|
  rootsOK_cons sieve24_2_3 <|
  rootsOK_cons sieve24_2_4 <|
  rootsOK_cons sieve24_2_5 <|
  rootsOK_cons sieve24_2_6 <|
  rootsOK_cons sieve24_2_7 <|
  rootsOK_cons sieve24_2_8 <|
  rootsOK_cons sieve24_2_9 <|
  rootsOK_cons sieve24_2_10 <|
  rootsOK_cons sieve24_2_11 <|
  rootsOK_cons sieve24_2_12 <|
  rootsOK_cons sieve24_2_13 <|
  rootsOK_cons sieve24_2_14 <|
  rootsOK_cons sieve24_2_15 <|
  rootsOK_cons sieve24_2_16 <|
  rootsOK_cons sieve24_2_17 <|
  rootsOK_cons sieve24_2_18 <|
  rootsOK_cons sieve24_2_19 <|
  rootsOK_cons sieve24_2_20 <|
  rootsOK_cons sieve24_2_21 <|
  rootsOK_cons sieve24_2_22 <|
  rootsOK_cons sieve24_2_23 <|
  rootsOK_cons sieve24_2_24 <|
  rootsOK_cons sieve24_2_25 <|
  rootsOK_cons sieve24_2_26 <|
  rootsOK_cons sieve24_2_27 <|
  rootsOK_cons sieve24_2_28 <|
  rootsOK_cons sieve24_2_29 <|
  rootsOK_cons sieve24_2_30 <|
  rootsOK_cons sieve24_2_31 <|
  rootsOK_cons sieve24_2_32 <|
  rootsOK_cons sieve24_2_33 <|
  rootsOK_cons sieve24_2_34 <|
  rootsOK_cons sieve24_2_35 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve24_2_0
#print axioms CollatzSearch.sieve24_part2
