import CollatzSearch.Sieve

/-! Kernel certificate part 24 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [6304, 6472), 16 blocks, estimated cost 2408918 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_24_0 : svRange 400 280 33554432 20 14 6304 9 = true := by decide +kernel
theorem sieve29_24_1 : svRange 400 280 33554432 20 14 6313 1 = true := by decide +kernel
theorem sieve29_24_2 : svRange 400 280 33554432 20 14 6314 37 = true := by decide +kernel
theorem sieve29_24_3 : svRange 400 280 33554432 20 14 6351 1 = true := by decide +kernel
theorem sieve29_24_4 : svRange 400 280 33554432 20 14 6352 17 = true := by decide +kernel
theorem sieve29_24_5 : svRange 400 280 33554432 20 14 6369 1 = true := by decide +kernel
theorem sieve29_24_6 : svRange 400 280 33554432 20 14 6370 25 = true := by decide +kernel
theorem sieve29_24_7 : svRange 400 280 33554432 20 14 6395 1 = true := by decide +kernel
theorem sieve29_24_8 : svRange 400 280 33554432 20 14 6396 2 = true := by decide +kernel
theorem sieve29_24_9 : svRange 400 280 33554432 20 14 6398 1 = true := by decide +kernel
theorem sieve29_24_10 : svRange 400 280 33554432 20 14 6399 1 = true := by decide +kernel
theorem sieve29_24_11 : svRange 400 280 33554432 20 14 6400 62 = true := by decide +kernel
theorem sieve29_24_12 : svRange 400 280 33554432 20 14 6462 1 = true := by decide +kernel
theorem sieve29_24_13 : svRange 400 280 33554432 20 14 6463 1 = true := by decide +kernel
theorem sieve29_24_14 : svRange 400 280 33554432 20 14 6464 7 = true := by decide +kernel
theorem sieve29_24_15 : svRange 400 280 33554432 20 14 6471 1 = true := by decide +kernel

theorem sieve29_part24 : RootsOK 400 280 33554432 20 14 6304 6472 :=
  rootsOK_cons sieve29_24_0 <|
  rootsOK_cons sieve29_24_1 <|
  rootsOK_cons sieve29_24_2 <|
  rootsOK_cons sieve29_24_3 <|
  rootsOK_cons sieve29_24_4 <|
  rootsOK_cons sieve29_24_5 <|
  rootsOK_cons sieve29_24_6 <|
  rootsOK_cons sieve29_24_7 <|
  rootsOK_cons sieve29_24_8 <|
  rootsOK_cons sieve29_24_9 <|
  rootsOK_cons sieve29_24_10 <|
  rootsOK_cons sieve29_24_11 <|
  rootsOK_cons sieve29_24_12 <|
  rootsOK_cons sieve29_24_13 <|
  rootsOK_cons sieve29_24_14 <|
  rootsOK_cons sieve29_24_15 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_24_0
#print axioms CollatzSearch.sieve29_part24
