import CollatzSearch.Sieve

/-! Kernel certificate part 1 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [224, 603), 16 blocks, estimated cost 2231008 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_1_0 : svRange 400 280 33554432 20 14 224 15 = true := by decide +kernel
theorem sieve29_1_1 : svRange 400 280 33554432 20 14 239 12 = true := by decide +kernel
theorem sieve29_1_2 : svRange 400 280 33554432 20 14 251 32 = true := by decide +kernel
theorem sieve29_1_3 : svRange 400 280 33554432 20 14 283 1 = true := by decide +kernel
theorem sieve29_1_4 : svRange 400 280 33554432 20 14 284 34 = true := by decide +kernel
theorem sieve29_1_5 : svRange 400 280 33554432 20 14 318 1 = true := by decide +kernel
theorem sieve29_1_6 : svRange 400 280 33554432 20 14 319 8 = true := by decide +kernel
theorem sieve29_1_7 : svRange 400 280 33554432 20 14 327 1 = true := by decide +kernel
theorem sieve29_1_8 : svRange 400 280 33554432 20 14 328 97 = true := by decide +kernel
theorem sieve29_1_9 : svRange 400 280 33554432 20 14 425 1 = true := by decide +kernel
theorem sieve29_1_10 : svRange 400 280 33554432 20 14 426 69 = true := by decide +kernel
theorem sieve29_1_11 : svRange 400 280 33554432 20 14 495 1 = true := by decide +kernel
theorem sieve29_1_12 : svRange 400 280 33554432 20 14 496 15 = true := by decide +kernel
theorem sieve29_1_13 : svRange 400 280 33554432 20 14 511 1 = true := by decide +kernel
theorem sieve29_1_14 : svRange 400 280 33554432 20 14 512 47 = true := by decide +kernel
theorem sieve29_1_15 : svRange 400 280 33554432 20 14 559 44 = true := by decide +kernel

theorem sieve29_part1 : RootsOK 400 280 33554432 20 14 224 603 :=
  rootsOK_cons sieve29_1_0 <|
  rootsOK_cons sieve29_1_1 <|
  rootsOK_cons sieve29_1_2 <|
  rootsOK_cons sieve29_1_3 <|
  rootsOK_cons sieve29_1_4 <|
  rootsOK_cons sieve29_1_5 <|
  rootsOK_cons sieve29_1_6 <|
  rootsOK_cons sieve29_1_7 <|
  rootsOK_cons sieve29_1_8 <|
  rootsOK_cons sieve29_1_9 <|
  rootsOK_cons sieve29_1_10 <|
  rootsOK_cons sieve29_1_11 <|
  rootsOK_cons sieve29_1_12 <|
  rootsOK_cons sieve29_1_13 <|
  rootsOK_cons sieve29_1_14 <|
  rootsOK_cons sieve29_1_15 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_1_0
#print axioms CollatzSearch.sieve29_part1
