import CollatzSearch.Sieve

/-! Kernel certificate part 35 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [9152, 9386), 14 blocks, estimated cost 2142889 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_35_0 : svRange 400 280 33554432 20 14 9152 30 = true := by decide +kernel
theorem sieve29_35_1 : svRange 400 280 33554432 20 14 9182 1 = true := by decide +kernel
theorem sieve29_35_2 : svRange 400 280 33554432 20 14 9183 1 = true := by decide +kernel
theorem sieve29_35_3 : svRange 400 280 33554432 20 14 9184 30 = true := by decide +kernel
theorem sieve29_35_4 : svRange 400 280 33554432 20 14 9214 1 = true := by decide +kernel
theorem sieve29_35_5 : svRange 400 280 33554432 20 14 9215 28 = true := by decide +kernel
theorem sieve29_35_6 : svRange 400 280 33554432 20 14 9243 1 = true := by decide +kernel
theorem sieve29_35_7 : svRange 400 280 33554432 20 14 9244 3 = true := by decide +kernel
theorem sieve29_35_8 : svRange 400 280 33554432 20 14 9247 1 = true := by decide +kernel
theorem sieve29_35_9 : svRange 400 280 33554432 20 14 9248 39 = true := by decide +kernel
theorem sieve29_35_10 : svRange 400 280 33554432 20 14 9287 56 = true := by decide +kernel
theorem sieve29_35_11 : svRange 400 280 33554432 20 14 9343 10 = true := by decide +kernel
theorem sieve29_35_12 : svRange 400 280 33554432 20 14 9353 32 = true := by decide +kernel
theorem sieve29_35_13 : svRange 400 280 33554432 20 14 9385 1 = true := by decide +kernel

theorem sieve29_part35 : RootsOK 400 280 33554432 20 14 9152 9386 :=
  rootsOK_cons sieve29_35_0 <|
  rootsOK_cons sieve29_35_1 <|
  rootsOK_cons sieve29_35_2 <|
  rootsOK_cons sieve29_35_3 <|
  rootsOK_cons sieve29_35_4 <|
  rootsOK_cons sieve29_35_5 <|
  rootsOK_cons sieve29_35_6 <|
  rootsOK_cons sieve29_35_7 <|
  rootsOK_cons sieve29_35_8 <|
  rootsOK_cons sieve29_35_9 <|
  rootsOK_cons sieve29_35_10 <|
  rootsOK_cons sieve29_35_11 <|
  rootsOK_cons sieve29_35_12 <|
  rootsOK_cons sieve29_35_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_35_0
#print axioms CollatzSearch.sieve29_part35
