import CollatzSearch.Sieve

/-! Kernel certificate part 53 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [13552, 13823), 14 blocks, estimated cost 1973269 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_53_0 : svRange 400 280 33554432 20 14 13552 43 = true := by decide +kernel
theorem sieve29_53_1 : svRange 400 280 33554432 20 14 13595 1 = true := by decide +kernel
theorem sieve29_53_2 : svRange 400 280 33554432 20 14 13596 43 = true := by decide +kernel
theorem sieve29_53_3 : svRange 400 280 33554432 20 14 13639 32 = true := by decide +kernel
theorem sieve29_53_4 : svRange 400 280 33554432 20 14 13671 56 = true := by decide +kernel
theorem sieve29_53_5 : svRange 400 280 33554432 20 14 13727 1 = true := by decide +kernel
theorem sieve29_53_6 : svRange 400 280 33554432 20 14 13728 31 = true := by decide +kernel
theorem sieve29_53_7 : svRange 400 280 33554432 20 14 13759 1 = true := by decide +kernel
theorem sieve29_53_8 : svRange 400 280 33554432 20 14 13760 15 = true := by decide +kernel
theorem sieve29_53_9 : svRange 400 280 33554432 20 14 13775 1 = true := by decide +kernel
theorem sieve29_53_10 : svRange 400 280 33554432 20 14 13776 15 = true := by decide +kernel
theorem sieve29_53_11 : svRange 400 280 33554432 20 14 13791 10 = true := by decide +kernel
theorem sieve29_53_12 : svRange 400 280 33554432 20 14 13801 21 = true := by decide +kernel
theorem sieve29_53_13 : svRange 400 280 33554432 20 14 13822 1 = true := by decide +kernel

theorem sieve29_part53 : RootsOK 400 280 33554432 20 14 13552 13823 :=
  rootsOK_cons sieve29_53_0 <|
  rootsOK_cons sieve29_53_1 <|
  rootsOK_cons sieve29_53_2 <|
  rootsOK_cons sieve29_53_3 <|
  rootsOK_cons sieve29_53_4 <|
  rootsOK_cons sieve29_53_5 <|
  rootsOK_cons sieve29_53_6 <|
  rootsOK_cons sieve29_53_7 <|
  rootsOK_cons sieve29_53_8 <|
  rootsOK_cons sieve29_53_9 <|
  rootsOK_cons sieve29_53_10 <|
  rootsOK_cons sieve29_53_11 <|
  rootsOK_cons sieve29_53_12 <|
  rootsOK_cons sieve29_53_13 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_53_0
#print axioms CollatzSearch.sieve29_part53
