import CollatzSearch.Sieve

/-! Kernel certificate part 46 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [11887, 12060), 13 blocks, estimated cost 2296817 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_46_0 : svRange 400 280 33554432 20 14 11887 16 = true := by decide +kernel
theorem sieve29_46_1 : svRange 400 280 33554432 20 14 11903 1 = true := by decide +kernel
theorem sieve29_46_2 : svRange 400 280 33554432 20 14 11904 27 = true := by decide +kernel
theorem sieve29_46_3 : svRange 400 280 33554432 20 14 11931 4 = true := by decide +kernel
theorem sieve29_46_4 : svRange 400 280 33554432 20 14 11935 10 = true := by decide +kernel
theorem sieve29_46_5 : svRange 400 280 33554432 20 14 11945 1 = true := by decide +kernel
theorem sieve29_46_6 : svRange 400 280 33554432 20 14 11946 61 = true := by decide +kernel
theorem sieve29_46_7 : svRange 400 280 33554432 20 14 12007 8 = true := by decide +kernel
theorem sieve29_46_8 : svRange 400 280 33554432 20 14 12015 1 = true := by decide +kernel
theorem sieve29_46_9 : svRange 400 280 33554432 20 14 12016 15 = true := by decide +kernel
theorem sieve29_46_10 : svRange 400 280 33554432 20 14 12031 1 = true := by decide +kernel
theorem sieve29_46_11 : svRange 400 280 33554432 20 14 12032 27 = true := by decide +kernel
theorem sieve29_46_12 : svRange 400 280 33554432 20 14 12059 1 = true := by decide +kernel

theorem sieve29_part46 : RootsOK 400 280 33554432 20 14 11887 12060 :=
  rootsOK_cons sieve29_46_0 <|
  rootsOK_cons sieve29_46_1 <|
  rootsOK_cons sieve29_46_2 <|
  rootsOK_cons sieve29_46_3 <|
  rootsOK_cons sieve29_46_4 <|
  rootsOK_cons sieve29_46_5 <|
  rootsOK_cons sieve29_46_6 <|
  rootsOK_cons sieve29_46_7 <|
  rootsOK_cons sieve29_46_8 <|
  rootsOK_cons sieve29_46_9 <|
  rootsOK_cons sieve29_46_10 <|
  rootsOK_cons sieve29_46_11 <|
  rootsOK_cons sieve29_46_12 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_46_0
#print axioms CollatzSearch.sieve29_part46
