import CollatzSearch.Sieve

/-! Kernel certificate part 38 for `DescRange (2^25) (2^20 * 280)`: residue-tree sieve
  (Sieve.lean, unchanged), lo = 2^25, K = 20, N = 280, forced bits f = 14, fuel 400;
  patterns [9888, 10154), 15 blocks, estimated cost 2249275 units.
  Generated by Scratch/sieve_gen/gen29.py; kernel reduction via `decide +kernel` only. -/

namespace CollatzSearch

theorem sieve29_38_0 : svRange 400 280 33554432 20 14 9888 9 = true := by decide +kernel
theorem sieve29_38_1 : svRange 400 280 33554432 20 14 9897 1 = true := by decide +kernel
theorem sieve29_38_2 : svRange 400 280 33554432 20 14 9898 55 = true := by decide +kernel
theorem sieve29_38_3 : svRange 400 280 33554432 20 14 9953 8 = true := by decide +kernel
theorem sieve29_38_4 : svRange 400 280 33554432 20 14 9961 6 = true := by decide +kernel
theorem sieve29_38_5 : svRange 400 280 33554432 20 14 9967 15 = true := by decide +kernel
theorem sieve29_38_6 : svRange 400 280 33554432 20 14 9982 1 = true := by decide +kernel
theorem sieve29_38_7 : svRange 400 280 33554432 20 14 9983 28 = true := by decide +kernel
theorem sieve29_38_8 : svRange 400 280 33554432 20 14 10011 1 = true := by decide +kernel
theorem sieve29_38_9 : svRange 400 280 33554432 20 14 10012 75 = true := by decide +kernel
theorem sieve29_38_10 : svRange 400 280 33554432 20 14 10087 1 = true := by decide +kernel
theorem sieve29_38_11 : svRange 400 280 33554432 20 14 10088 22 = true := by decide +kernel
theorem sieve29_38_12 : svRange 400 280 33554432 20 14 10110 1 = true := by decide +kernel
theorem sieve29_38_13 : svRange 400 280 33554432 20 14 10111 42 = true := by decide +kernel
theorem sieve29_38_14 : svRange 400 280 33554432 20 14 10153 1 = true := by decide +kernel

theorem sieve29_part38 : RootsOK 400 280 33554432 20 14 9888 10154 :=
  rootsOK_cons sieve29_38_0 <|
  rootsOK_cons sieve29_38_1 <|
  rootsOK_cons sieve29_38_2 <|
  rootsOK_cons sieve29_38_3 <|
  rootsOK_cons sieve29_38_4 <|
  rootsOK_cons sieve29_38_5 <|
  rootsOK_cons sieve29_38_6 <|
  rootsOK_cons sieve29_38_7 <|
  rootsOK_cons sieve29_38_8 <|
  rootsOK_cons sieve29_38_9 <|
  rootsOK_cons sieve29_38_10 <|
  rootsOK_cons sieve29_38_11 <|
  rootsOK_cons sieve29_38_12 <|
  rootsOK_cons sieve29_38_13 <|
  rootsOK_cons sieve29_38_14 <|
  rootsOK_nil _ _ _ _ _ _

end CollatzSearch

#print axioms CollatzSearch.sieve29_38_0
#print axioms CollatzSearch.sieve29_part38
